### ISSUE TITLE
Deal with misleading storage rewards in Inflation struct

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#10092]
This field is now dead code
https://github.com/solana-labs/solana/blob/58ef02f02b48f9f25a79a25c1356f89d6b7b8a84/sdk/src/inflation.rs#L21-L22
as of https://github.com/solana-labs/solana/pull/9992.

Removing it entirely would likely cause a snapshot ABI change, so renaming it to `__unused` would be an alternative.    It should be removed from the `getInflation` RPC API AS well

**Comment by CriesofCarrots** [comment]
Storage should also be removed from this calculation as well, correct?
https://github.com/solana-labs/solana/blob/c600cfc65506e4cc669e9c00430e228f4c4db641/sdk/src/inflation.rs#L69
(Right now, in epochs after the foundation term:
- total inflation = 0.015
- validator inflation = 0.0135
...due to this)

**Comment by mvines** [comment]
Yeah.  Might need @ericlwilliams's help

**Comment by ryoqun** [comment]
> Removing it entirely would likely cause a snapshot ABI change, so renaming it to __unused would be an alternative. It should be removed from the getInflation RPC API AS well

Hm, snapshot 1.3 should remove these fields at once, then? :)

**Comment by ericlwilliams** [comment]
Yeah seems like that can/should be killed. Unless @aeyakovenko, or anyone else, sees Archivers on the horizon.  For the foreseeable future, inflation should be divvied out just between validators and Foundation/Grant pools
