### ISSUE TITLE
v1.0 panic at "Buffer not large enough to fit nonce"

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#10251]
This panic is reachable during normal validator operations:
https://github.com/solana-labs/solana/blob/8cde8a54ac6c27c648a505d8eccae05fbdc88af6/core/src/repair_response.rs#L48

Log:
[panic.txt](https://github.com/solana-labs/solana/files/4684188/panic.txt)

**Comment by mvines** [comment]
Looks like this needs to be wrapped with a `if size_of_nonce > 0` check
```rust
    if let Some(nonce) = nonce {
        bincode::serialize_into(&mut wr, &nonce).expect("Buffer not large enough to fit nonce");
    }
```

**Comment by carllin** [comment]
So for reference, this was the stack trace:
```
15: solana_core::repair_response::repair_response_packet_from_shred
May 26 16:54:13 li1251-182 solana-validator[7235]:   16: solana_core::repair_response::repair_response_packet
May 26 16:54:13 li1251-182 solana-validator[7235]:   17: solana_core::serve_repair::ServeRepair::run_window_request
May 26 16:54:13 li1251-182 solana-validator[7235]:   18: solana_core::serve_repair::ServeRepair::run_listen
```
`repair_response_packet`  which is called before `repair_response_packet_from_shred ` guarantees that if it's called with a shred for `slot > UNLOCK_NONCE_SLOT`, then the `nonce.is_some()`:  https://github.com/solana-labs/solana/blob/v1.0/core/src/repair_response.rs#L16-L20.

Thus by the time we reach the panicking line here: https://github.com/solana-labs/solana/blob/v1.0/core/src/repair_response.rs#L48, because we know `none.is_some()`, the slot for the shred > `UNLOCK_NONCE_SLOT`, i.e. based on this: https://github.com/solana-labs/solana/blob/v1.0/core/src/repair_response.rs#L34-L36, it must be `size_of_nonce == SIZE_OF_NONCE`.

This leaves me to conclude that in order for that panic to happen, the size of the data shred itself, for some slot > `UNLOCK_NONCE_SLOT` was bigger than `NONCE_SHRED_PAYLOAD_SIZE`, which would leave insufficient space for the nonce. 

This most likely means the validator hadn't upgrade before `UNLOCK_NONCE_SLOT` and stored in their own blockstore a shred with slot `> UNLOCK_NONCE_SLOT` a payload that was too large. 

We know this because had they had upgraded, any non-conforming incoming shreds would have had to gone through this call in `window_service` here: https://github.com/solana-labs/solana/blob/v1.0/core/src/window_service.rs#L195, and been truncated here: https://github.com/solana-labs/solana/blob/v1.0/ledger/src/shred.rs#L262-L270

**Comment by mvines** [comment]
> This most likely means the validator hadn't upgrade before UNLOCK_NONCE_SLOT and stored in their own blockstore a shred with slot > UNLOCK_NONCE_SLOT a payload that was too large.

This is almost certainly what happened.   "Fix": nuke the local ledger?
