### ISSUE TITLE
Evaluate Rust BPF options

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#1133]
You mentioned rbpf. Are there others to consider?

https://github.com/qmonnet/rbpf

rbpf isn't under active development anymore. It looks well-tested and nice CI. I was able to run all tests locally with no trouble. Biggest red flag is the number of errors (not warnings) that Clippy reports.  Specifically, ones like:

```
casting from `*const u8` to a more-strictly-aligned pointer `*const u16`)`
```

You might consider fixing a few of those on a fork, making a Pull Request and seeing if anybody's still around to review and merge it.

**Comment by jackcmay** [comment]
From what I can tell all the clippy errors are coming from unsafe blocks

**Comment by jackcmay** [comment]
## BPF:

[rBPF](https://github.com/qmonnet/rbpf) provides a VM that is capable of both interpreting and jitting rust.  rBPF is a rust port of uBPF written in C (https://github.com/rlane/ubpf).  The author of rBPF is quite prolific online in the realm of BPF and has contributed to various other BPF projects as well as created good documentation and example projects.

In addition to all tests passing, I was able to build my own BPF program with LLVM 6.x and run it both as interpreted and jitted.  BPF also allows for a BPF program to call 'helper' functions.  Helper functions are provided by the system and are called by index (function pointer interpreted as an index into a known list).  These helper calls are probably what we could use for signaling and any other 'system' calls we need to expose to BPF programs.  I've verified and tested that rBPF supports calling helper functions correctly

Three main concerns with rBP at this time:  
1. There are a lot of clippy warnings and errors.  It looks to me that the code producing the errors was written intentionally.  This may be to improve speed or it may be just a roll-over from the C port which did direct pointer manipulation.  I've fixed one of these errors and submitted a pull request to elicit comments from the author.  Some of the errors could be addressed simply but others require broader re-work of the surrounding code or changing the mutability of some publicly exposed parameters.
2. rBPF is geared toward the Linux kernel's use of BPF so there may be some rework required to accommodate our use case.  It does provide the ability to call a BPF program with an arbitrary data buffer so that might be sufficient as is for now but we will also want to customize the BPF verification function.
3. rBPF will need to be evaluated further from a security perspective.  This is something we can do as phase X.

## ELF Loading:

rBPF does not provide any ELF loading functionality.  Instead, it just takes the raw BPF bytecode.  So in addition to a BPF VM like rBPF we also need basic ELF loading.  

1. [rust-elf](https://github.com/cole14/rust-elf)
    * MIT license
    * All tests pass buy very limited test coverage
    * 0 releases
    * latest relevant activity 2 years ago
    * Most generic use case, read-only, no section parsing (also maybe most popular)
    * Used by rBPF to parse its example ELFs
    * Worked for me to extract the .text section so that I could pass it to rBPF.
    * There are a few minor warnings when running the tests (unused variables) and some minor warnings when running clippy (casting u32 to u64 may become silently lossy if types change)
    *  Overall it seems to adhere to good rust practice and does not contain any 'unsafe' blocks.

2. [elfkit](https://github.com/aep/elfkit)
    * MIT license
    * All tests pass, good test coverage, lots of clippy warnings/errors
    * Latest relevant activity 2 months ago

3. [goblin](https://github.com/m4b/goblin)
    * MIT license
    * All tests pass, good coverage, lots and lots of clippy warnings, no errors
    * Latest relevant activity 2 months ago
    * Probably way overkill for our needs

4. [xmas-elf](https://github.com/nrc/xmas-elf)
    * Apache v2 or MIT license
    * Only one test, passes, but clippy errors and warnings
    * Latest relevant activity 6 months ago
    * Similar to rust-elf

5. [Rustep](https://github.com/Escapingbug/Rustep)
    * MIT license
    * Did not compile
    * Latest relevant activity 6 months ago

## Dynamic loading:

Dynamic modules can be written in rust and built with cargo.  This is a good starting point to load contracts dynamically and even after adding support for BPF can provide a good mechanism for us to unit test the contract mechanisms.

There are a number of ELF loading crates available, for completeness below is a list of the options I found.  These crates operate on native modules (macho-o on mac, elf on linux, dll on windows) using rust's libc crate which exports native dlopen, dlsym, etc...   We will probably want to wrap one in order to support both native as well as BPF modules under the same interface depending on the module type being loaded.

Feel free to add any additional ones I may have missed.  All the below are implemented on top of rust's libc crate which exports native dlopen, dlsym, etc...

1.  [rust_libloading](https://github.com/nagisa/rust_libloading).
    * ISC license
    * All tests pass and pretty good coverage
    * Latest relevant activity 1 month ago
    * This is the officially sanctioned rust method to load dynamic modules (https://michael-f-bryan.github.io/rust-ffi-guide/dynamic_loading.html).  
    * There are some lifetime and thread safety issues with libloading that though not inherently dangerous but violates rust safety practices and are ripe for misuse.  One example is that the lifetime of a symbol obtained from a library is not tied to the lifetime of the loaded library.  Two other crates address this (sharedlib and  rust-dlopen) address these issues.

2. [shared_library](https://github.com/tomaka/shared_library/) 
    * Apache v2 and MIT license
    * Tests pass but very limited coverage
    * Latest relevant activity 2 months ago
    * This looks like its attempting a similar mechanism as rust-dlopen where it creates a 'container' to hold both the library and the symbols.  The interface is clean and simple but due to me being a rust noob I'm not quite following its implementation yet (especially the shared_library!() macro).  This interface looks like the cleanest.

3. [sharedlib](https://github.com/Tyleo/sharedlib) (this project's test failed for me, plan to follow up with the author)
    * ISC license
    * Tests failed but fairly good coverage
    * Latest relevant activity 2 years ago
    * Similar and based on rust_libloading but provides lifetime-bound and ref-counted libraries as well as allows the caller to 'dlsym' both functions and data.  For more information, the lifetime and reference counting see the [Choosing your gaurantees](https://tyleo.github.io/sharedlib/index.html#choosing-your-guarantees) section in the docs.

4. [rust-dlopen](https://github.com/szymonwieloch/rust-dlopen) 
    * MIT license
    * Tests failed but fairly good coverage
    * Latest relevant activity 9 months ago
    * Attempts to make things simpler and avoid the direct use of 'unsafe'.  Also allows the user to pass a structure of functions and data that should be resolved by the module and will return the populated structure.
    * Handles lifetime via a container that contains both the library and the symbols acquired from it.

5. [dl_api](https://github.com/plopgrizzly/dl_api)
    * MIT license
    * Only one test and it fails
    * Latest relevant activity 3 months ago]
    * Another very thing wrapper over libc and provides a more complicated but similar mechanism as shared_library.

6. dylib crate(no git found)
    * Another very thin wrapper over libc, provides direct and access to open, sym without any protections.

7. std:dynamic_lib - deprecated since Rust 1.5

## Misc

Also found [bingrep](https://github.com/m4b/bingrep) which is like readelf but writen in rust and for ELF, Mach, Unix and BSP archive, and PE.
