### ISSUE TITLE
Duplicate transaction detection for failed transactions

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#1157]
Transactions may fail in the following ways:

1. fail to afford the fee to execute
2. fail in the contract's internal implementation
3. the result of contract execution may create an invalid state

Current implementation does the following:

Schedule the transaction to execute if it can afford to pay the fee.  If the Transaction fails 2 or 3, the transaction is not written to the ledger, its signature is still stored and a duplicate request is dropped.  This is part of #953

Its not clear that this behavior is bad.  Bad transactions only execute once, and the ledger only contains fully executed transactions.

**Comment by garious** [comment]
@aeyakovenko, the bank currently collects the fee before executing the transaction, but then doesn't store it if the program fails. I think that it should clone that account before execution, and store only that one if there's a failure. After that, it should put the transaction on the ledger so that way the validators know to collect the fee as well.

**Comment by garious** [comment]
Per your comment, assigning you here. If it doesn't turn out to fix it, feel free to unassign it and move it back to the Future milestone.

**Comment by pgarg66** [comment]
Fixed in #2847
