### ISSUE TITLE
error code -32004

### ISSUE THREAD

**Issue by hu7777chenyi** [solana-labs/solana#12208]
#### Problem
The following error is reported when starting, is there any way to solve it?
curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0","id":1,"method":"getConfirmedBlock","params":[5, "json"]}' localhost:28188
{"jsonrpc":"2.0","error":{"code":-32004,"message":"Block not available for slot 5"},"id":1}

**Comment by CriesofCarrots** [comment]
Hi, @hu7777chenyi . I need some more information in order to help. How are you starting your localnet? What slot is it at when you attempt to query `getConfirmedBlock`?
Without knowning more, my best guess is that the local node has not yet rooted slot 5, hence the confirmed block is not yet available.
