### ISSUE TITLE
Pocket and Solana Integration Bounty

### ISSUE THREAD

**Issue by rmshea** [solana-labs/solana#12592]
#### Challenge description:

Pocket is a decentralized API solution for developers that incentivizes participants to run full nodes for blockchain for developers who need data for their applications.

This bounty intends to incentivize the creation of Pocket's web-provider for Solana. We're looking to make it easy for any Solana developer to use Pocket's web-provider. 

#### Submission deadline:

November 1

#### Judging criteria:

Best submission
Elegance of the solution
Performance of the solution
Contributions to other open-source packages will be appreciated

#### Judging Date:

November 1st

#### Bounty:

$2000 USD delivered in your token of choice

#### Communication

Find us on Discord and/or drop your questions here.

**Comment by Arrowana** [comment]
Are we talking about https://pokt.network/ ?
Because the website says: "Currently supporting: [...] Solana" and in the doc https://docs.pokt.network/docs/supported-networks-on-testnet Solana is in on their pocket testnet support list.
What does this bounty exactly entails? Is it about spinning up some examples?
