### ISSUE TITLE
question for benchmark test

### ISSUE THREAD

**Issue by guagualvcha** [solana-labs/solana#13828]
#### Problem
I have read a post which describe:
```
On current iterations of the Solana Testnet, a network of 200 physically distinct nodes supports a sustained throughput of more than 50,000 transactions per second when running with GPUs
```
Can I ask how many accounts are in the store and how many accounts are involved for this benchmark test?

**Comment by sakridge** [comment]
In bench-tps, 8x multiplier is used for --tx_count parameter set at 50,000, so the benchmark rotates through 400,000 accounts:
https://github.com/solana-labs/solana/blob/761499dfbfdafe159f54a700447fbb354709d325/bench-tps/src/cli.rs#L44

It actually creates a total of about 1.4 million accounts due to alignment in the funding algorithm:
https://github.com/solana-labs/solana/blob/761499dfbfdafe159f54a700447fbb354709d325/bench-tps/src/bench.rs#L866
