### ISSUE TITLE
`--no-snapshot-fetch`  should still fetch a snapshot if there is no existing ledger

### ISSUE THREAD

**Issue by nyetwurk** [solana-labs/solana#13834]
#### Problem
`--no-snapshot-fetch` is tricky to use, since you need a snapshot when there is no ledger yet (on a clean install), but once you have a ledger, you have to change the command line the next time you run the validator. This makes automating validator start (via systemd for example) overly complex.

#### Proposed Solution
`--no-snapshot-fetch` should still try to fetch a snapshot if there is no existing ledger. This way, it can always be set on the command line.

**Comment by mvines** [comment]
Can you please explain more why you want `--no-snapshot-fetch` set?  Is this because you're running with no `--trusted-validator`s?

**Comment by nyetwurk** [comment]
I could have sworn it was advised to use it after the validator had been properly synced once. Perhaps I misunderstood? If so, under what circumstances should it be used?

**Comment by nyetwurk** [comment]
@mvines Here is the context:
https://discord.com/channels/428295358100013066/670512312339398668/776921457343201283
Ping me in discord to discuss further, perhaps I misunderstood the option.

**Comment by mvines** [comment]
There's two main reasons I can think of:
1. You want to ensure ledger continuity.  This is important for RPC nodes (api.mainnet-beta.solana.com) that want to have the full history for clients, or archival nodes that aim to store the entire ledger for posterity. 
2. You really don't want to trust any other node to serve you a snapshot.  Some exchanges run this way because they're rightfully paranoid.

For a normal validator node, if the network is progressing along then you really do alway want a recent snapshot to catch up as quickly as possible.  

The third reason to use `--no-snapshot-fetch` was that sometimes it can take minutes or worse to download a snapshot, and the software was dumb and downloading a new snapshot even if there was a reasonably fresh snapshot already present locally.  To mitigate this, I recently made this change: https://github.com/solana-labs/solana/pull/13842

**Comment by nyetwurk** [comment]
Yes, I misspoke, specifically this would be used in non-voting node, not a validator, for the purposes of RPC access.
