### ISSUE TITLE
100% Traffic increase after upgrade to v1.5.6

### ISSUE THREAD

**Issue by stakeconomy** [solana-labs/solana#15268]
#### Problem
We see a 100% traffic increase on our mainnet-node after upgrading from 1.4.26 to 1.5.6.
![traffic_increase](https://user-images.githubusercontent.com/25040379/107671814-8bb84100-6c94-11eb-9e45-43a2bdb55808.png)

If needed we can try to upgrade again and see what ports are using more traffic than before the upgrade.

**Comment by behzadnouri** [comment]
@stakeconomy can you please confirm which ports have seen the increased traffic?

**Comment by behzadnouri** [comment]
There was https://github.com/solana-labs/solana/pull/14699 which so far has doubled the crds table size (on TDS). But the actual network traffic increase is _not_ proportional to crds table size, but it is a function of how often duplicate shreds happen.

If the **inbound** traffic reverses to previous levels when downgrading to 1.4 then i doubt that this is caused by gossip (I could be wrong though). So it would be very helpful if we can see which ports are seeing higher traffic especially on the inbound side.

**Comment by behzadnouri** [comment]
from discord:
https://discord.com/channels/428295358100013066/689412830075551748/809498231217586196

![ports](https://user-images.githubusercontent.com/1288998/107687044-e30edf00-6c9d-11eb-8ab4-813f0187b588.png)

**Comment by behzadnouri** [comment]
This is my _guess_ of why when reverting to v1.4 incoming traffic drops.

With https://github.com/solana-labs/solana/pull/14699 this number:
https://github.com/solana-labs/solana/blob/762bab775/core/src/crds_gossip_pull.rs#L448-L451
has crossed 330k, which means that there will be twice as many crds-filters/pull-requests (512 vs 256 before).

Given the number of items, the filters target 10% false rate:
https://github.com/solana-labs/solana/blob/762bab775/core/src/crds_gossip_pull.rs#L36
but because v1.4 gets the number of items wrong:
https://github.com/solana-labs/solana/blob/762bab775/core/src/crds_gossip_pull.rs#L64-L76
and sends half as many requests as it should, there will be a lot more false negatives,
and the node will see lower traffic compared to v1.5.

**Comment by sakridge** [comment]
@behzadnouri how many duplicate entries are we seeing?

**Comment by behzadnouri** [comment]
> @behzadnouri how many duplicate entries are we seeing?

@sakridge Do you mean the duplicate-shred values?
When I checked on TDS yesterday it was ~130 times number of nodes.

**Comment by sakridge** [comment]
> > @behzadnouri how many duplicate entries are we seeing?
> 
> @sakridge Do you mean the duplicate-shred values?
> When I checked on TDS yesterday it was ~130 times number of nodes.

So each node had reported 130 duplicate shreds? How old are the slots of those shreds?

**Comment by behzadnouri** [comment]
> So each node had reported 130 duplicate shreds? How old are the slots of those shreds?

I did not check the slots. But duplicate shred payloads are broken into chunks, and for a sample duplicate shred payload I tested it was taking 3 chunks.

So most likely this is ~40 slots per node on average.

The pruning logic is currently set to keep most recent 512 values for each pubkey.

**Comment by behzadnouri** [comment]
duplicate-shreds are not the problem. I mean they make the crds table larger but they are not the ones which take network bandwidth. When I tested on tds yesterday, this was what the packets were (roughly so):
```
ContactInfo: 4%
NodeInstance: 4%
EpochSlots: 31%
Vote: 59%
```
Then the question is that why downgrading to v1.4 reduces the inbound traffic, to which I only have this hypothesis: https://github.com/solana-labs/solana/issues/15268#issuecomment-777835847

**Comment by stakeconomy** [comment]
We upgraded to 1.5.7 again with 1 validator and we see our upload double up. No longer our download.

[cid:image001.png@01D7023E.0C34E520]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by behzadnouri** [comment]
Another commit which might have an impact on outbound traffic is https://github.com/solana-labs/solana/pull/14438

Previously every node effectively were only broadcasting 2 vote indices, despite maximum vote index being 32:
https://github.com/solana-labs/solana/blob/e403aeaf0/core/src/crds_value.rs#L33
and `MAX_LOCKOUT_HISTORY` of 31:
https://github.com/solana-labs/solana/blob/ab0f4c69a/programs/vote/src/vote_state/mod.rs#L30 

The other indices were occupied by oldest votes and were never overridden. So once propagated over the network, they would never get updated again. https://github.com/solana-labs/solana/pull/14438 fixed this, so now every node keeps 31 most recent votes (instead of only 2 in before). But a consequence of that might be the higher outbound traffic.

**Comment by stakeconomy** [comment]
I'm curious if the doubled outbound traffic is something we would want (speaking as a validator). 
160Mbit outbound traffic is much traffic and I surely hope that this can be mitigated.

**Comment by behzadnouri** [comment]
I added some metrics measuring size of packets received here:
https://github.com/solana-labs/solana/blob/13d55b708/core/src/cluster_info.rs#L2637-L2648
and it does not seem like the *inbound* traffic increase is from gossip. It is actually the other way around (i.e the traffic is less). That is likely because v1.4 cannot deserialize duplicate-shred values, and next pull-response will include those crds values again.

The left chunk is v1.4:
![gossip_inbound_traffic](https://user-images.githubusercontent.com/1288998/108536089-ede7f600-72d3-11eb-94aa-d87f01aa2629.png)

**Comment by behzadnouri** [comment]
From [this metrics dashboard](https://discord.com/channels/428295358100013066/478692221441409024/812422620967862293), the outbound network usage has been slowly dropping, possibly because of [this](https://discord.com/channels/428295358100013066/478692221441409024/812425062481264710):

![network_usage](https://user-images.githubusercontent.com/1288998/108729486-7b208a00-7522-11eb-9b43-28877a9e5b73.png)

**Comment by sakridge** [comment]
@behzadnouri if we back out duplicate slots entirely how does it affect it?

**Comment by behzadnouri** [comment]
> @behzadnouri if we back out duplicate slots entirely how does it affect it?

I do not think it will impact much. Please see https://github.com/solana-labs/solana/issues/15268#issuecomment-778481190
Unless a significant portion of the traffic are pull-requests without any response, in which case droping duplicate shreds will help _indirectly_ by reducing number of pull-requests (not pull responses or push messages). https://github.com/solana-labs/solana/pull/15407 would probably help to investigate that. But I do not think that is a good solution because inevitably crds table will become larger as the cluster gets bigger. 

Another issue might be that staked nodes are getting too much weight in pull/push options. Might need to reduce the impact of stake there.

https://github.com/solana-labs/solana/issues/15268#issuecomment-778880026 might have had more impact than the duplicate shreds.

**Comment by mvines** [comment]
I feel this issue has gone stale, if there's an actionable left here then please open a new issue
