### ISSUE TITLE
cli: Program deploy creates too large buffer

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#15431]
#### Problem
The doubling logic for upgradeable program data length gets applied to the buffer but the temp buffer should ever be as big as the deployed executable binary. This means deployers need to pay rent for really big buffers and there appears to be a downstream bug that causes the final program data to be over allocated with SOL

**Comment by jackcmay** [comment]
The original idea was to fund the programdata account from the buffer account.  The latest implementation funds the programdata account from the payer since the buffer is not a signer and the system program would reject the creation. The intermediate buffer account is then drained back to the payer.  The side effect of this is that the total funds required to be available to deploy the program must be enough for two buffer accounts even though the final result is enough for one.  The implementation could correct this by draining the buffer account to the payer before calling the system program to create the programdata account.

@jstarry Can you provide more info on how you saw the program data account to be over-allocated with SOL?

**Comment by jstarry** [comment]
@jackcmay sorry haven't had a time to wrap this up yet. Here's the transaction that the cli created when retrying a deploy: https://explorer.solana.com/tx/4d5XYHrmA41nVDC83Us7aEip9umbKrUMKfHE2Y5QA9WmcE113eu6qSr9vZNVHe7goLALV6HiCbgEsDUyWii5MvuD which was caused by a buffer account that was double sized. This resulted in a program data account that was 4x the executable binary which can be found here: https://explorer.solana.com/address/5s4R9BYyUpzv2a7PwMaKDsk9iWtkHMcUrBFC6zuGEidC
