### ISSUE TITLE
SimulateTransaction Json-RPC response error not consistently

### ISSUE THREAD

**Issue by yihau** [solana-labs/solana#15553]
#### Problem

I encounter problems with SimulateTransaction json-rpc.

The scenario is that:

If I transfer with not enough balance, the response is 
```
{
   "jsonrpc":"2.0",
   "result":{
      "context":{
         "slot":65340475
      },
      "value":{
         "err":{
            "InstructionError":[
               0,
               {
                  "Custom":1
               }
            ]
         },
         "logs":[
            "Program 11111111111111111111111111111111 invoke [1]",
            "Program 11111111111111111111111111111111 failed: custom program error: 0x1"
         ]
      }
   },
   "id":0
}
```
The error message is in the `result.value.err`

If I transfer with enough balance but mismatch signature, the response is
```
{
   "jsonrpc":"2.0",
   "error":{
      "code":-32003,
      "message":"Transaction signature verification failure"
   },
   "id":0
}
```
The error message is in the `error`

I think the both are simulating tx fail, but i have no idea why the error behavior is not consistent.

#### Proposed Solution

maybe create a new consistent error behavior simulate tx api to avoid breaking changes

**Comment by mvines** [comment]
There's a subtle difference between these two errors.  

The first error, "InstructionError", is from the program itself.  That is, RPC successfully accepted the transaction and executed it.  The "error" comes from the on-chain program itself.   Essentially the on-chain program was successfully simulated (so no RPC error) but it returned an error result (hence the error information in the result object).

The second error is an RPC error.  RPC rejected the transaction because it wasn't signed properly.  

I know this is slightly confusing but it actually is consistent across the RPC API as a whole.

**Comment by yihau** [comment]
If I use the wrong method in rpc, the response is 

```
{"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found"},"id":0}
```

it seems like the error level of `Transaction signature verification failure` is same as the server error level.

**Comment by mvines** [comment]
> I just ask for the tx is legal or not

The transaction that returned "InstructionError" is 100% legal.  It will pay the fee and execute if you were to broadcast it to the network.   The "InstructionError" is a runtime error is returned by the program itself as it executed.   This is very different than a "Transaction signature verification failure" error, which means that the tx is not legal, would be completely rejected by the. network and not pay any fee

**Comment by mvines** [comment]
> it seems like the error level of Transaction signature verification failure is same as the server error level.

Yep, this is correct.  The RPC server rejected the transaction. 

The difference is subtle, but there is a difference :)

**Comment by yihau** [comment]
Got it, but the current situation make me confused.

I can't not just check the `result.value.err` for the simulating result.
I also need to check the rpc error.
Although there is rpc error, not represent the tx must be fail, maybe it just some other rpc error.
I need to check the code, too.

btw, there is a same discuss in the discord developer-support channel.

**Comment by yihau** [comment]
I try to turn off the `skipPreflight` and send the tx with mismatch signature.
It seems like not cause the rpc error. I can send and get a not found signature back.

**Comment by yihau** [comment]
would @jstarry willing join the discuss ?

**Comment by jstarry** [comment]
The `simulateTransaction` and `sendTransaction` endpoints behave differently when a transaction fails during simulation. `sendTransaction` returns an rpc error and `simulateTransaction` returns an rpc success with error embedded inside the result. I think it makes more sense for them to both return rpc errors

**Comment by yihau** [comment]
hi @mvines 
is there any updates?

**Comment by mvines** [comment]
Re-examining `sendTransaction` at the same time would be good, it currently returns the transaction signature unnecessarily.  The caller already has this info.  Instead of the transaction signature, `sendTransaction` could return the transaction simulation output the same way that `simulateTransaction` does.

Seems worthwhile considering in the future sometime, if anybody has the time and desire.   This is pretty low priority for now though, as I have no desire to unnecessarily create new variants of `simulateTransaction` and `sendTransaction` that don't add any new features but instead rework the existing inputs and outputs.
