### ISSUE TITLE
RpcRequestError("Failed to deserialize RPC error response

### ISSUE THREAD

**Issue by brianlong** [solana-labs/solana#15576]
#### Problem
When using the CLI to check a vote-account on mainnet, I receive an RPC parsing error:

```
$ solana --url [MAINNET] vote-account 5m2h5u5gaCb8d4iG2K1oKGrxDu99UZ1GJbFMJNFbCPmV
Failed to fetch epoch rewards: ClientError { request: Some(GetConfirmedBlock), kind: RpcError(RpcRequestError("Failed to deserialize RPC error response: {\"code\":-32004,\"message\":\"Block not available for slot 66960001\"} [missing field `data`]")) }
```

This validator uses the same pubkey & vote account on both mainnet & testnet. I do not receive that error on testnet, just mainnet.

#### Proposed Solution
I identify the cause of the parsing error. It looks like we are missing the 'data' element.

**Comment by brianlong** [comment]
P.S. That is not my vote account. One of the validators used the same pubkey & vote account on both mainnet & testnet. So, it makes an interesting case. That request above seems to work using the testnet RPC server, but not the mainnet RPC server.

**Comment by CriesofCarrots** [comment]
This is almost certainly due to an unhealthy rpc node (`solana vote-account 5m2h5u5gaCb8d4iG2K1oKGrxDu99UZ1GJbFMJNFbCPmV -u m` returns correctly now). But the error message isn't very helpful, is it?

**Comment by brson** [comment]
I see this "failed to deserialize" error frequently when testing RpcClient against TestValidator.

The problem is that `HttpSender` expects all RPC errors to contain a `data` element, and some or many of them do not. It's not clear to me whether the server is wrong to not be including an empty `data` field, or if the client is wrong to be expecting `data` to always exist.

In `http_sender` `RpcErrorObject` is defined as:

```
#[derive(Deserialize, Debug)]
struct RpcErrorObject {
    code: i64,
    message: String,
    data: serde_json::Value,
}
```

Adding `#[serde(default)]` to the `data` field makes the problem go away without introducing any API breakage. Changing the field to `data: Option<serde_json::Value>` would probably also work.

**Comment by brson** [comment]
Considering that the jsonrpc-core `Error` type (https://docs.rs/jsonrpc-core/18.0.0/jsonrpc_core/types/error/struct.Error.html) is

```
pub struct Error {
    pub code: ErrorCode,
    pub message: String,
    pub data: Option<Value>,
}
```

The `data` field in HttpSender is probably incorrect and should be an Option.
