### ISSUE TITLE
rpc: Add options for limiting getConfirmedBlock response data

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#15817]
#### Problem
The `getConfirmedBlock` RPC response can be quite massive when considering transaction details and metadata as well as a ton of reward information for blocks on the epoch boundary. Not all consumers will need this information but currently everyone has to pay the cost of bandwidth and response time.

#### Proposed Solution
1. Add an option to not return reward info
2. Add an option to return either full tx details, only signatures, or nothing at all.

**Comment by mvines** [comment]
The "nothing at all" case for transactions in a block would speed up the rewards output in `solana vote-account` and `solana stake-account` -- these two commands are getting slower and slower for each new epoch post-inflation.   This is probably worth spinning off into another issue, once this issue is fixed, assuming it doesn't happen at the same time
