### ISSUE TITLE
explorer: Account and instruction deserialization and labelling is manual

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#16180]
#### Problem
Account and instruction deserialization and labelling is done manually and is not scalable to all community created programs

#### Proposed Solution
- Leverage an IDL spec to automatically label and deserialize account state and instruction params
- Review the IDL under development in https://github.com/project-serum/anchor

**Comment by jstarry** [comment]
@armaniferrante could you share the status of the IDL you've developed as part of Anchor and whether you think it would be a good solution to this issue?

**Comment by armaniferrante** [comment]
The anchor IDL is defined by the JSON serialization of the struct [here](https://github.com/project-serum/anchor/blob/master/lang/syn/src/idl.rs#L4). Some examples can be found [here](https://github.com/project-serum/serum-ts/tree/master/packages/stake-ui/src/idl). It's currently used to generate clients with [@project-serum/anchor](https://www.npmjs.com/package/@project-serum/anchor).

It could definitely be used for this issue. To start, one might want to trim down the IDL linked above (which has some anchor specific concepts like events, state, and errors) and begin with the basics, e.g., something like,

```rust
pub struct Idl {
    pub version: String,
    pub name: String,
    pub instructions: Vec<IdlIx>,
    pub accounts: Vec<IdlTypeDef>,
    pub types: Vec<IdlTypeDef>,
}
```

Other than bike shedding the nitty details of exact JSON format, I think the main thing missing for this issue would be a serialization format field, because currently the IDL assumes everything is borsh serialized. Depending on what current programs on Solana are doing, we might want to allow other formats. The main challenge that comes to mind is what to do about programs with custom serialization, like the Serum DEX.

**Comment by jstarry** [comment]
Thanks @armaniferrante for the details!

+1 to a serialization format field

Starting with borsh support sounds like a good start. Not sure the best route for bincode / custom deserialization. Could leverage wasm for this?

I like the idea of a deterministic place for IDL's! If we included it in the bytecode, then we might lose the ability to deserialize historical transactions whenever a program is upgraded. Because of upgrades, I think the seed should include both the program id as well as the program's last upgraded slot.

**Comment by oJshua** [comment]
Tracking this issue. @bartosz-lipinski and I have also been discussing an associated IDL / ABI-type program. This would help our Explorer efforts immensely. We've also considered include some additional metadata e.g. project name, github url.

**Comment by armaniferrante** [comment]
Some additional details that may or may not be relevant.

* Anchor uses sighash based method dispatch (rather than enum based dispatch). So anchor instruction data looks like `sha256(rust-ix-struct-ident)[..8] || borsh(rust-ix-struct)`. Sighash is important to be able to support features like program interfaces (example [definition](https://github.com/project-serum/anchor/blob/master/examples/interface/programs/counter/src/lib.rs#L64) and [impl](https://github.com/project-serum/anchor/blob/master/examples/interface/programs/counter-auth/src/lib.rs#L18)), where a program wants to call another program, without assuming anything other than it implements the interface. This isn't possible with enum based dispatch, since there may be a collision in the enum variant discriminator. Sighash allows namespacing methods, e.g., by prefacing the `#[interface]` trait name in the sha256 pre-image).
* To support IDL versioning, we may also want to adopt a convention to prepend a version number to the instruction data. So that the explorer can look at at transaction, see the version, fetch the idl with the version as one of the seeds, and then decode the data. If such a versioning scheme would be embedded into all new instructions, how would the explorer be able to tell the difference between the old world and new world? One way would be prepend a magic number prefix, signalling new world.

**Comment by ngundotra** [comment]
Existing Anchor IDLs are used to deserialize account data in the explorer (as of #23972 and #24239).

Would love to revive this conversation and set out some concrete steps to go further. 

Low hanging fruit:
- How should we differentiate between known program names & program names deserialized from the Anchor IDL?
- How should we display decoded Anchor events found in the program logs?

@jstarry  @armaniferrante @oJshua  @bartosz-lipinski
