### ISSUE TITLE
cargo-build-bpf: BPF SDK install loader prompt spans many lines

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#16449]
#### Problem
BPF SDK install loader prompt spans many terminal lines

![Screen Shot 2021-04-09 at 12 33 23 PM](https://user-images.githubusercontent.com/1076145/114128807-c99db280-992f-11eb-86c3-269ee825c005.png)

cc @mvines

**Comment by dmakarov** [comment]
Would it be better to disable the download progress tracking?

**Comment by mvines** [comment]
Weird, it doesn't span multiple lines in my terminal.  Disabling the progress sucks because you then have a command that sits there for potentially minutes or worse with no output.   

A `--silent` flag could be one option here, or alternatively we just drop the separate download all together and instead bundle the bpf toolchain in the primary release installed by `solana-install`.

**Comment by t-nelson** [comment]
Is this a line wrap thing?  The screenshot is overcropped, so I can't tell.

I'd like to think indicatif would auto-truncate the message text to the terminal width, but maybe not?  It definitely prefixes the message with `\r` for the animation, so that will hide any wrapped text

**Comment by mvines** [comment]
Maybe we can just print the url once, and then only use the string `Downloading ...` for the progress to make accidental wrapping less likely

**Comment by jstarry** [comment]
> Is this a line wrap thing? The screenshot is overcropped, so I can't tell.

Ah yeah, you're right. Definitely a line wrap thing, it looks fine on a wider terminal.

**Comment by t-nelson** [comment]
> Maybe we can just print the url once, and then...

Don't wanna just update the message width on `SIGWINCH`? :slightly_smiling_face:
