### ISSUE TITLE
README doesn't have the list of install paths

### ISSUE THREAD

**Issue by yurivict** [solana-labs/solana#16801]
#### Problem
```README``` only mentions the ```build``` command, and doesn't mention ```install```.

Arch linux runs ```install``` for multiple paths: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=solana

Is the list correct? Where does this list come from? Is there a shorter way to do the same?

**Comment by rmanosuthi** [comment]
Disclaimer: I don't have an Arch installation on hand.

From what I can gather [here](https://wiki.archlinux.org/title/PKGBUILD) and your linked pkgbuild, `install` is simply used to copy the binaries into the *temporary* build folder, which is `$pkgdir` and will become `/` upon installation of the package.

So no fixes should be made to README since this is a distro-specific behavior.

**Comment by t-nelson** [comment]
> So no fixes should be made to README since this is a distro-specific behavior.

Correct.  That package is maintained by a third party.  We don't support it here

**Comment by yurivict** [comment]
> Correct. That package is maintained by a third party. We don't support it here

I didn't ask to support it.

I asked what is the correct way to install ```solana```.

**Comment by rmanosuthi** [comment]
If you're on arch, use that PKGBUILD.

If not, after `cargo build --release` copy binaries from `target/release/` to wherever you want to put them. Usually `/usr/bin/`.
