### ISSUE TITLE
AccountsDb replication for RPC

### ISSUE THREAD

**Issue by carllin** [solana-labs/solana#16986]
#### Problem
Validators fall behind the network when bogged down by heavy RPC load.

Tag @aeyakovenko, @sakridge, @t-nelson, @ryoqun, @CriesofCarrots 

#### Proposed Solution: AccountsDb Streaming

Create replicas that stream per-slot accounts updates from a validator, and otherwise just manage AccountsDb and AccountsBackgroundService clean + shrink.

The protocol would look roughly like:

1) Validator maintains some TCP connections to backing replicas.

2) On replica starts up and establishes a connection to the validator, they do one of the following:
       a) Grab a snapshot for root `S` from the validator, along with all the rooted + *unrooted* `Storage(storage_entry)` for frozen slots `T >  S` up to the to the `last_cleaned_root` by the validator. After sending the storage entry for `last_cleaned_root`, the validator starts sending `Frozen(storage_entry)` or `Frozen(cache_entry)` for future slots `F`, which means the replica after applying `F` should be consistent up to slot `F` (because those have not been cleaned yet).

      b) In the future it may also be possible to stream the startup data from `a)` from other replicas to lessen the burden on the validator. 

3) After the startup process, the replica gets a constant stream of `(Frozen(cache_entry)` from the validator's replication background thread. The validator's replication background thread receives a clone of the `Arc<SlotCacheInner>` for each slot on bank freeze and forwards this info to the replica. In the future, we could also build a Turbine-like structure such that the validator does not have the burden of propagating all of these updates to every replica

The validator also streams roots + optimistic confirmation so that the replica's clean + shrink logic can prune outdated data, and also answer RPC queries about rooted + optimistically confirmed accounts.

I think if we want to support `Confirmation` levels outside of `root + optimistically confirmed` we may also need to stream parent slots so that the replica can know the fork structure on queries

Bandwidth estimate of streaming:
https://metrics.solana.com:8888/sources/3/chronograf/data-explorer?query=SELECT%20mean%28%22total_unique_writes_size%22%29%20AS%20%22mean_total_unique_writes_size%22%2C%20mean%28%22num_slots%22%29%20AS%20%22mean_num_slots%22%20FROM%20%22mainnet-beta%22.%22autogen%22.%22accounts_cache_size%22%20WHERE%20time%20%3E%20now%28%29%20-%201h%20GROUP%20BY%20time%28%3Ainterval%3A%29%20FILL%28null%29

Right now 100 slots in the cache are roughly 3-5 GB, so each slot is on average 30-50 MB?

One additional benefit is that without rent collection the `AccountsIndex` lock on these maps don't need to be sorted. This opens the possibility of experimenting with something like this: https://github.com/jonhoo/left-right

#### Proposed Solution 2: Ledger Streaming

An alternative is to stream the ledger shreds instead of the account updates, run replay, and do replication that way with a more fully fledged validator. Replay is more CPU intensive and may cause more conflict on the AccountsIndex lock, but streaming the ledger shreds may require less bandwidth than streaming all the Accounts per slot.  Please comment on thoughts on this vs streaming the Accounts.

**Comment by brianlong** [comment]
A read-only replica for some of the RPC calls is a great idea.

**Comment by sakridge** [comment]
Prototype code: https://github.com/solana-labs/solana/pull/17275

Doesn't add any new interfaces, just some boilerplate code to download genesis/snapshot independent of the validator entrypoint.

I think a pull model is probably a good idea. Otherwise the validator itself has to keep some state to track different subscriptions to these RPC nodes which could be dynamically being started/stopped being pointed at different validators.

Then you would have an interface of getting all the slot updates which the RPC replica uses to put new updates into it's own bank. It does something like an RPC call, using bincode or borsh encoding would be preferable to JSON though.

It's relatively easy for the validator to construct the response to this when the updates are in the slot cache. Once they are not in the cache, it becomes harder it has to recover from the AppendVecs, and once the updates have been flushed to disk and cleaned then the requisite update set may not even be available, although at that point there should be new updates to update the replica with, so maybe it  could have some wrong information temporarily because it's going to retrieve the newer ones shortly once it catches up to the node's cached slots.

**Comment by CriesofCarrots** [comment]
We replaced this effort with the geyser plugin system.
