### ISSUE TITLE
Transaction size restriction limits program composability

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#17102]
#### Problem
Since each account input in a transaction uses up 32 bytes, the 1232 size limit for each transaction can be used up very quickly when composing programs in complex transactions. For example, many defi protocols interact with the serum dex and then those defi protocols are composed together for things like flash loans, arbitrage, pools, etc.

Keeping the 1232 byte limit for transaction is highly desirable because it simplifies and speeds up the networking / gossip layer used by validators.

#### Proposed Solutions
1. Compress account inputs

Implement a compression scheme which allows account inputs to be compressed into small integers before being sent to the cluster. Validators will know how to decompress inputs and will verify transactions signatures using a fully decompressed transaction.

A proposal should be written to cover the design of how compressed transactions will be handled and how we guarantee consistency of compression across all nodes.

2. Load transactions on-chain

Use standard MTU limited transactions to build a larger transaction piece by piece on-chain. Then use a special instruction to execute that transaction when it's valid and ready to be executed.

**Comment by jon-chuang** [comment]
I guess the idea is to use say a `Map<u16, Pubkey>` that is out of band for compression? How do the validators agree on this? 
Further, is the idea that an RPC node knows how to compress the tx message?

**Comment by SebastianBor** [comment]
What about making it possible to specify an account range using a query instead of an explicit account list?
The query could work in similar way to the RPC memcmp filter.

I find it to be quite a common scenario when the required accounts are selected using some predicate, and that predicate could be passed to the transaction.

Once particular scenario I have in mind is voting in the `Governance` program. Once a proposal is decided the staked tokens could be automatically distributed back to all voters. Currently it's not possible due to the accounts limit and each voter has to manually reclaimed the tokens.

**Comment by sakridge** [comment]
> What about making it possible to specify an account range using a query instead of an explicit account list?
> The query could work in similar way to the RPC memcmp filter.
> 
> I find it to be quite a common scenario when the required accounts are selected using some predicate, and that predicate could be passed to the transaction.
> 
> One particular scenario I have in mind is voting in the `Governance` program. Once a proposal is decided the staked tokens could be automatically distributed back to all voters. Currently it's not possible due to the accounts limit and each voter has to manually reclaimed the tokens.

Locks us into a specific implementation to make that type of query fast.

**Comment by SebastianBor** [comment]
> > What about making it possible to specify an account range using a query instead of an explicit account list?
> > The query could work in similar way to the RPC memcmp filter.
> > I find it to be quite a common scenario when the required accounts are selected using some predicate, and that predicate could be passed to the transaction.
> > One particular scenario I have in mind is voting in the `Governance` program. Once a proposal is decided the staked tokens could be automatically distributed back to all voters. Currently it's not possible due to the accounts limit and each voter has to manually reclaimed the tokens.
> 
> Locks us into a specific implementation to make that type of query fast.

Well, it's not about making it fast but rather making it possible because instructions operating on a larger range of similar accounts are not possible at present. I'm not saying it should be the only solution, but if we are considering alternative ways to select accounts for a transaction maybe we might as well support predicates for ranges.

**Comment by CriesofCarrots** [comment]
Solution #1 has been proposed, implemented, and activated: https://github.com/solana-labs/solana/issues/26391
If solution #2 seems necessary later, let's create a new issue
