### ISSUE TITLE
Panic in purge_exact in accounts_index

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#17756]
#### Problem

```
I was checking the alarms and I can see that the validator has panic crashing around 11:10 CET,
checking the logos I can see that there is indeed a panic version is v1.7.0

[2021-06-04T09:09:34.550452231Z INFO  solana_runtime::accounts_db] remove_dead_slots_metadata: slots [81348084]
[2021-06-04T09:09:34.551454704Z INFO  solana_runtime::accounts_db] remove_dead_slots_metadata: slots [81348098]
thread 'solana-bg-accounts' panicked at 'called `Option::unwrap()` on a `None` value', runtime/src/accounts_index.rs:1022:80

note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2021-06-04T09:09:34.572353278Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="solana-bg-accounts" one=1i message="panicked at 'called `Option::unwrap()` on a `None` value', runtime/src/accounts_index.rs:1022:80" location="runtime/src/accounts_index.rs:1022:80"
```

Presumably this unwrap:

`let mut write_account_map_entry = self.get_account_write_entry(pubkey).unwrap()`

#### Proposed Solution

Check unwrap? But I think it should not happen.

Keys can get removed by:
clean_rooted_entries - called by clean_accounts -> clean_accounts_older_than_root
handle_dead_keys - only called by purge_exact

**Comment by sakridge** [comment]
reclaims tracked here:
```
let (purged_account_slots, removed_accounts) =
    self.clean_accounts_older_than_root(purges_old_accounts, max_clean_root);
```

Purges are pruned by reclaims:
```
let was_reclaimed = removed_accounts
    .get(&account_info.store_id)
    .map(|store_removed| store_removed.contains(&account_info.offset))
    .unwrap_or(false);
if was_reclaimed {
    return false;
}
```

Yet.. account_infos must have contained the pubkey which is already removed from the index.

**Comment by carllin** [comment]
Ick, I think I introduced this bug in 

The call path from `purge_slots_from_cache_and_store() -> purge_slot_storage -> purge_keys_exact()` can experience this panic I think

**Comment by carllin** [comment]
Hmmm on further investigation, I *think* this path should be fine because for `clean_accounts` to have removed a pubkey `P` from the index, that pubkey needed to have:
1) Be zero lamports
2) All storage entries that contained `P` from any other slot are empty and thus have been removed/moved to the recycler. That means because there's only one storage entry per slot, it must be that any slots that have written to `P` must be dead.

So if we assume clean removed `P`, then when the scan in  `purge_slot_storage(slot)` should not have found any storage entries for  the slot with the pubkey `P` in it, otherwise the earlier clean could not have removed `P` from the index...
