### ISSUE TITLE
windows系统安装完cli包后提示'solana-test-validator' 不是内部或外部命令，也不是可运行的程序

### ISSUE THREAD

**Issue by cl510804194** [solana-labs/solana#17977]
#### Problem
windows系统安装完cli包后提示'solana-test-validator' 不是内部或外部命令，也不是可运行的程序

#### Proposed Solution

![image](https://user-images.githubusercontent.com/42998038/122094715-09f14380-ce3f-11eb-8733-366e62abebc4.png)

**Comment by steviez** [comment]
Google translate detected the written problem statement as Chinese (which I cannot read or write); here is the output from Google translate:
> After the system installs the cli package, it prompts `solana-test-validator`. Not an internal or external command, nor an executable program

@cl510804194 - There are currently issues with fully running a validator on Windows; see https://github.com/solana-labs/solana/issues/4608 which is still open. With this in mind, we only distribute a subset of the CLI tools on Windows: 
https://github.com/solana-labs/solana/blob/master/scripts/cargo-install-all.sh#L69-L81
```
if [[ $CI_OS_NAME = windows ]]; then
  # Limit windows to end-user command-line tools.  Full validator support is not
  # yet available on windows
  BINS=(
    cargo-build-bpf
    cargo-test-bpf
    solana
    solana-install
    solana-install-init
    solana-keygen
    solana-stake-accounts
    solana-tokens
  )
```
If you download and extract `solana-release-x86_64-pc-windows-msvc.tar.bz2` from https://github.com/solana-labs/solana/releases/tag/v1.6.12, you'll see `solana-test-validator` is not included.

The comment about full validator support is kind of hidden; currently checking to see if we document this in any of the higher level documentation anywhere.

**Comment by steviez** [comment]
@cl510804194 - I believe that Windows Subsystem for Linux (WSL) may be an option for you:
https://docs.microsoft.com/en-us/windows/wsl/about

**Comment by steviez** [comment]
Closing this out - hopefully the issue / alternatives are apparent, but feel free to re-open if you disagree

**Comment by cl510804194** [comment]
thanks

**Comment by CockyCat** [comment]
Still not provide a solution. @steviez

**Comment by CockyCat** [comment]
Pls reopen this issue, because not a solution now.

**Comment by steviez** [comment]
> Still not provide a solution. @steviez

@CockyCat - You're right, this doesn't solve the underlying issue. However, it offers some alternatives if you're tied to Windows (ie WSL) on your host.

https://github.com/solana-labs/solana/issues/4608 captures the underlying issue as to why we don't ship Windows binaries (because they won't work), so I'm going to leave this item (and the one you opened) closed as I'd consider it a duplicate. Whenever we get things working on Windows, we'll start shipping the binaries. As you could have probably surmised from the age of that issue, Windows support isn't a huge priority for us
