### ISSUE TITLE
Reduce latency by considering physical location in the leader schedule

### ISSUE THREAD

**Issue by ruuda** [solana-labs/solana#18044]
#### Problem

The leader schedule is currently pseudorandom. Light takes about 30ms to travel from Amsterdam to New York in a fiber. If the leader schedule alternates between validators located in a data center in New York and in Amsterdam, it adds 30ms to the block time on every leader switch, because the leader needs to first receive the hash of the previous block before it can start working on its block.

Block times could be reduced by ensuring that validators who are neighbors in the leader schedule, are also physically close. This introduces other risks (what if they are in the same data center, and it suffers an outage), but if you have some objective function that considers physical location and other aspects to rank different leader schedules, a pseudorandom schedule would not likely be optimal.

#### Proposed Solution

There are some things I can think of, but I haven’t thought any of them through seriously.

**Comment by jon-chuang** [comment]
Although this would probably be impractical due to the security risk in such an "unimpartial" leader schedule algorithm, I do have an alternative idea: how long the next leader waits should depend on their ping, where they wait a maximum ping. For instance, if their measured ping is 30ms, the next leader ought to wait an extra 30ms. This may increase block time. But at least it could reduce forks.

**Comment by ruuda** [comment]
A complication since I opened this issue is that it is now possible to do failover, so the physical location of a server can change at any time during the epoch. If the leader schedule needs to take location into account, the leader should only be chosen briefly before the slot, not an entire epoch in advance.
