### ISSUE TITLE
Re-enable optimistic-confirmation local-cluster tests

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/solana#18279]
#### Problem
 #18278 ignores 2 local-cluster tests failing consistently in CI

#### Proposed Solution
Identify root cause of test failures, fix, and re-enable them

**Comment by CriesofCarrots** [comment]
Reverting https://github.com/solana-labs/solana/pull/18072 seems to fix the flakiness

**Comment by AshwinSekar** [comment]
Seems after #18072 we are skipping pull responses from validator D during the restart of validator C.
```
➜  solana git:(flake) ✗ grep -o skip_pull_response_shred_version=... golden-excerpt
skip_pull_response_shred_version=0i
skip_pull_response_shred_version=0i
skip_pull_response_shred_version=0i
➜  solana git:(flake) ✗ grep -o skip_pull_response_shred_version=... flaky-excerpt
skip_pull_response_shred_version=0i
skip_pull_response_shred_version=50i
skip_pull_response_shred_version=0i
skip_pull_response_shred_version=0i
skip_pull_response_shred_version=0i
skip_pull_response_shred_version=0i
```

Further debugging shows that validator D is responding to validator C's requests, however because it is relaying A and B's votes, C complains because it is not aware of A and B's shred versions thus failing [this check](https://github.com/solana-labs/solana/blob/master/gossip/src/cluster_info.rs#L3066)
```
incompatible shred versions None for public key Bz8byUe5bFKcQZWMdU1NQZuJ2GAN3vZvzkahcynXQi5S vs msg sender 40585
incompatible shred versions None for public key AqEWUK8pdsfY2CTrBQLGS8w8ndMeuFcDpCkFwWaicaLL vs msg sender 40585
```

It seems in the flaky tests, we don't receive the ContactInfo gossip message for A and B soon enough, so we are stuck skipping the responses from D.

**Comment by AshwinSekar** [comment]
It seems to have to do with ordering of the pull response that C receives. In the first two rounds of gossip, C receives the contact info for nodes A and B as well as all the voting information. 
In successful runs the contact info is processed quite early resulting in < 25 votes to be missed which doesn't seem to impact fork choice.
However in bad runs  we miss as many as 45 votes because the contact info ends up being towards the tail of the packets received. 

What's curious is that in both of these cases we send no other pull requests to D, so we never get a chance to reprocess these votes after getting the contact infos.

**Comment by AshwinSekar** [comment]
The reason why we are no longer seeing pull requests to D is due to the weighting when choosing samples to send pull requests to [here](https://github.com/solana-labs/solana/blob/master/gossip/src/crds_gossip_pull.rs#L304). We base the weight of each peer validator on the timestamp at which we last sent a pull request.

Because of this, both validator A and B (offline currently) have enormous weight proportionate to validator D. Since we haven't received any pings from these validators, [we never actually send out a pull request](https://github.com/solana-labs/solana/blob/master/gossip/src/crds_gossip_pull.rs#L254), and are unable to reset the timestamp. 

A solution could be to repeatedly sample the peers, removing peers that we haven't received pings from. Or even check the ping cache when computing the weights so that we don't end up in a lopsided scenario with offline nodes.

**Comment by ryoqun** [comment]
@AshwinSekar thanks for working on fixing this flaky tests. :) Well, it seems you're making good progress into delving into the gossip than me already... ;)
