### ISSUE TITLE
SPL token txs fail on master debug solana-test-validator

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/solana#18918]
#### Problem
STR:
Macos, on master
```
cargo run --bin solana-test-validator
spl-token create-token <-- hangs indefinitely
```
spl-memo transactions process successfully (so it's not all bpf programs).

Reverting https://github.com/solana-labs/solana/commit/8d5c04e25704df0788d7a9808fd9d7594cd3ca8f fixes the issue
Adding `noop_instruction_ratio: 0.0` to Config options https://github.com/solana-labs/solana/blob/f26451158540d9ef4103b3f2c905df8fddeaa408/programs/bpf_loader/src/lib.rs#L82 also fixes the issue.

Based on runtime logging, it appears the runtime performs `load_and_execute_transactions()` successfully, then fails here
https://github.com/solana-labs/solana/blob/93c20d0a472333bf233d7fa6ae5ea3192fe221bc/core/src/banking_stage.rs#L849
on a `MaxHeightReached` error.

#### Proposed Solution
Identify root problem and fix

**Comment by Lichtso** [comment]
## Observation

#### Normal / expected behavior
```
$ target/debug/spl-token --url http://127.0.0.1:8899 create-token
Creating token CJxw6Y9pbezHQ8re3DyatiPyBTH5p34rpNjRbN8c59JY

Signature: woPM1cGmg3QRep4PLaWag4tPJfmr9iGrLta9YHwnFHHYyVwxR8CmDVUF5GKuenM4rtLzq7uCdTe4mgWixvmsLBc

$
```

#### Buggy / unexpected behavior
```
$ target/debug/spl-token --url http://127.0.0.1:8899 create-token
Creating token FPGjqBk5W8gXfh2PruvAq2FcZvdndEwfUdhzwLtrAUpP
⠙ [0/1] Finalizing transaction 53LNbNQWWmWuB36cB5cVvVouYqGLCZT2G2iyDz8LJsCVnR4i218hTydsZFLjFH25LBKMXkjmfU7VcRc6z5UcmnB5
```

Attaching a debugger to the solana-test-validator and stepping through the JITed epilogue shows that the VM successfully exits the BPF program (it does not run into an infinite loop). However, the transaction is stuck and gets retried over and over again according to the log.

## Reproduction
So far it could only be reproduced if the following conditions are met:
* Running a solana-test-validator in debug mode on macOS.
* Leaving `noop_instruction_ratio=1.0/256.0` (the default) works sometimes but `noop_instruction_ratio=0.5` is more reliable.
* The solana-test-validator runs on a version of [solana_rbpf](https://github.com/solana-labs/rbpf) from the following range of commits:
  * Inclusive begin: https://github.com/solana-labs/rbpf/commit/608a756110111eccfee463f7def896e7f1ce6a38
  * Exclusive end: https://github.com/solana-labs/rbpf/commit/558f567a8e0832cc756061504e6389465922499f

If the `noop_instruction_ratio` config is set to `0.0` or `1.0`, which makes the emitted code more symmetric / systematic, the phenomenon stops happening.

## Hypothesis
So, I think neither the begin of the range introduced the bug nor the end fixed it. My hypothesis:
The begin commit introduces jitter to the machine code addresses (as intended), so the bug gets detected by fuzzing.
The end commit massively reduces the compiled code size, so the bug has less space to unfold and goes undetected again.

**Comment by Lichtso** [comment]
I addressed the first of the three problem points mentioned above here: https://github.com/solana-labs/rbpf/pull/211

@CriesofCarrots @t-nelson, not sure who is familiar / best fit for the other two cache related problems.

**Comment by mvines** [comment]
@jackcmay is probably the best person for the executor cache issue, although @Lichtso debugging this further would also be a good excuse for you to get more experience in the runtime as well

**Comment by jackcmay** [comment]
So the suggestion is to cache the executor even if the transactions fails with the thought that even if it fails the program will probably be run at time point again and therefore we should cache it?

**Comment by Lichtso** [comment]
The thing is: The transactions do not fail, even if the bug occurs the log still says: `[solana_runtime::bank] store executor`.
Yet, the executor is not stored or stored in the wrong place. Either way it is not used in the next transaction.

**Comment by jackcmay** [comment]
The long slot completes and the executor is added to that bank's cache, but because it took so long another slot is started and the transaction is tried again there.  Since the cache is copy-on-write the new forks never get a copy of the newly cached executor.  Not sure we should be using an executor from a slot that went way over its time anyway and instead the cost model should probably get feedback on how long this bad transaction is taking and incorporate it into the future slot batches so that the slot does go over budget
