### ISSUE TITLE
On-chain block timestamps are wildly incorrect, due to max allowable drift

### ISSUE THREAD

**Issue by ruuda** [solana-labs/solana#18992]
#### Problem

This is a screenshot of explorer.solana.com, a few minutes after I created transaction `2DB1cpBvt7beU9RkhRMY34FfBYLbDAVTS5kjFwKKpoqVMMZkk9wUazrkLBJ5N4YGswMXR2g989g1fKxE4xjbmzVg` on testnet.

![2021-07-31-solana-testnet-transaction-history](https://user-images.githubusercontent.com/506953/127645510-230b47ec-bca3-40fa-abfc-e3b9c38d8003.png)

The transaction page says

> Timestamp: Jul 24, 2021 at 16:58:39 Central European Summer Time

This is very wrong, but what’s much worse, is that there no way to know *how* wrong this time is. For blocks produced by Solana versions where the timstamp drift cap is in place, the timestamps cannot be trusted.

I ran into a similar issue when I tried to plot historical block times of mainnet-beta, by querying blocks from the RPC, and plotting the `time_elapsed / slots_elapsed` for 100k-slot windows:

![solana-block-times](https://user-images.githubusercontent.com/506953/127646180-58fcd01d-0603-45fc-98b3-b4f3f0b1b630.png)

Note the plateaus of exactly 0.5s in January, 0.6s in February, and 0.72s in March. The 0.72s coincides exactly with the new drift limit introduced in https://github.com/solana-labs/solana/pull/15204. It’s not that the block times were _actually_ that steady, what happened is the max allowable drift capping the timestamp increment, so the above graph is misleading, it shows mostly garbage. But it is very difficult to know when it shows something useful and when it shows garbage, because we can’t tell for sure in hindsight if the timestamp in a block was the true stake-weighted median timestamp, or if it was altered due to the max allowable drift.

#### Proposed Solution

Delete the max allowable drift. Just store the stake-weighted median timestamp.

**Comment by CriesofCarrots** [comment]
The max-allowable drift is in place to prevent particular kinds of validator attacks via timestamp manipulation.
The fundamental problem causing the drift is that testnet blocks have been far too slow; we prefer to attack that underlying issue instead. v1.7.8 has improved block times significantly, and we're already seeing the time-drift start to correct to real time, as the max-allowable allows. But it's going to take a while to catch back up. And there's more work to be done, since 550ms blocks are still a ways off from the goal 400ms.

**Comment by kklas** [comment]
> This is very wrong, but what’s much worse, is that there no way to know how wrong this time is

Since the stake-weighted timestamp is calculated based off of the timestamps reported in the vote instructions capped by the max allowable drift, I believe you could get a stake-weighted median timestamp of a block by looking up the vote transactions in there and calculating the median timestamp yourself.

Maybe there should be a rpc method for that, or at least a method in the blockstore. I could see it being useful for monitoring the drift of the `unix_timestamp` in the clock sysvar at the very least.

cc @CriesofCarrots, any thoughts?

**Comment by CriesofCarrots** [comment]
> Maybe there should be a rpc method for that, or at least a method in the blockstore.

@kklas I think what you're suggesting is have an RPC method that returns the stake-weighted median timestamp *without* capping the amount of drift. Do I have that right?

I think it's probably too much to ask RPC nodes and long-term storage to store such an informal timestamp in order to be able to serve it for every block, and I'm a little concerned about how it might be accidentally misused if exposed. But I could see adding a log for that data.

You can also calculate it yourself, client-side, by calling `getBlock` and examining the Votes. This way you'd have more control over what you consider the reasonable approximation of real-world time -- you could add outlier elimination, or even just look at the votes by a small subset of known validators.

**Comment by kklas** [comment]
Yea, I think that logging it would definitely be a good start. This needs to be monitored IMO so that corrective action can be taken in time if the discrepancy becomes too big. 

The reason I got thinking about it is because I believe the `clock.unix_timestamp` discrepancy is a security concern and a footgun for smart contracts which rely on it for implementing lockups, vesting and such. Most smart contract developers are not aware of the inner workings of the `unix_timestamp` (and shouldn't have to be IMO) and could potentially (falsely) rely on the fact that `unix_timestamp` is somewhat accurate representation of slot wall time, while in reality a discrepancy of days and more is possible.

From my understanding, and correct me if I'm wrong, this is how it's currently implemented:
- each validator's most recent vote in the current epoch are collected and the *implied timestamp* for the current slot is calculated based off of the vote's slot offset and targeted time per slot (400ms): `implied_timestamp = validator_recent_vote.timestamp + (current_slot - validator_recent_vote.slot) * target_time_per_slot`
- based on all the implied timestamps we take the stake-weighted median value as the correct `unix_timestamp` for the current slot
- the resulting timestamp is capped to `max_allowable_drift` so that it doesn't deviate much from the timestamp expected from epoch start and targeted time per slot (400 ms) `(current_slot - epoch_start) * target_time_per_slot`

The problem occurs when the actual times per slot are slower or faster than the target of 400 ms. This is due to the fact that the actual time per slot is determined by the PoH clock which depends on the hashing speed and is variable. So when the PoH clock ticks (hashes) faster, then the actual wall time durations of the slots are going to be lower (slot duration is defined through number of PoH ticks).
When this goes on for a sustained period of time, the discrepancy accumulates, the max allowable drift cap is hit, and the `clock.unix_timestamp` of the block starts lagging or leading the actual wall time of the block.

This implementation works around two issues:
1) The block timestamp needs to be present in the state (through the `clock.unix_timestamp` sysvar) before transactions get applied on to it so that it can be referenced from inside the transaction instructions, while the block votes (which contain the validators' timestamps) start arriving only after the block has been published by the leader. 
That's why in the current implementation the unix_timestamp of the block is only *estimated* based off of validators' votes on recent blocks.
2) Validators can, either maliciously or non-maliciously, submit erroneous timestamps in their votes causing the block `unix_timestamp` be off from the actual wall time of the block. Due to this the *max allowable drift* was introduced to cap the block timestamp to a certain limit.

The issues with the current implementation are:
- if the blocks become too slow or fast and it persists for a while, the block timestamps will drift from the actual due to the capping of the max allowable drift  (as highlighted by the OP)
- there nothing to disincentivize validators from sending erroneous timestamps in their votes anyways so the *max allowable drift* cap isn't actually solving the issue of potentially malicious validators causing the drift, it just alleviates it to a degree 

There's no pressure for the block timestamps to converge to the real time and it has happened in the past that the timestamp had to be corrected using manual intervention (#15204).

A similar discussion has been had by the ethereum team here https://ethresear.ch/t/network-adjusted-timestamps/4187. Vitalik proposed two possible approaches that could be adopted:
1) Instead of taking the 50th percentile for the timestamp, the leader takes the 67th in the direction of it's own clock.
2) Have the validators adjust their clocks based on implied timestamps of recent votes. So for example if the majority's implied timestamp is within 10 minutes of validators actual clock, it shifts to that timestamp. In order to shift to a timestamp that's within 20 minutes of validator's clock, it requires that 55% of implied timestamps be at that value and so on.
I guess this is in some sense similar to the *max allowable drift* but instead of it being capped by PoH clock, it's capped by validators wall time.

That way there is pressure for validators to converge to actual time.

To solve the problem of malicious validators sending wrong timestamps, maybe there could be slashing for votes whose timestamps were too far away from the median? This would incentivize validators to keep their clock in sync.

**Comment by jstarry** [comment]
I think we need to rethink the maximum allowable drift. It doesn't work for outages and it's not great that accurate wallclock time is tied to whether slots take a long time or there are many consecutive skipped slots. I agree that it would be great if we had fast slots, no skipped slots, and never had an outage again but I don't think we're in a position to make that bet right now given the cluster's track record. So I think it's important to decouple the task of fixing the clock from the general health of the cluster.

I think we can get a pretty accurate clock from taking the stake weighted median timestamp of blocks and then enforce that it's monotonic.

**Comment by imprfekt** [comment]
Thank you @jstarry and @CriesofCarrots for pushing this change.

Time-based protocols like Streamflow have a **really hard time** with the current setup.
Time drifts can get really big and we've been getting a lot of heat from customers that use our protocol for token vesting.

So just wanted to publicly thank you. :)
