### ISSUE TITLE
Build fails when building solana-ledger binary

### ISSUE THREAD

**Issue by ivanmlerner** [solana-labs/solana#19666]
#### Problem
Build fails when building from source, specifically when building solana-ledger binary.
The error thrown is: "an inner attribute is not permitted in this context"
Where: "#![allow(clippy::cast_ptr_alignment)]"
Solana version: 1.6.22

**Comment by steviez** [comment]
Hi @ivanmlerner, can you please check which version of rust you're building with? Ie, run:
```
rustc --version
```
Check that against what our CI infrastructure is building the 1.6 release branch with (note that this version is a bit older since the 1.6 release branch has been around for a while):
https://github.com/solana-labs/solana/blob/53f8e5830098448da2f8c10bead2b981416799e6/ci/docker-rust/Dockerfile#L3

**Comment by switchbrad** [comment]
I just ran into the same error with Rust v1.54.0. The `README.md` is confusing because it indicates you should build against the latest Rust version, but I'm guessing that at the time that was correct... but not for stable currently. The quickest fix is to just build with the version in `ci/rust-version.sh` from stable (v1.51.0).

The other option is to remove the exclamation point from `#![allow(clippy::cast_ptr_alignment)]` in `ledger/src/sigverify_shreds.rs` like in the `master` branch. I have no idea if building stable using rust v1.54.0 may cause undesired issues, hopefully not, but maybe someone else can weigh in.

**Comment by steviez** [comment]
Fair enough on the README; I just added a note to it about looking up the version when you're not building the latest.

>I have no idea if building stable using rust v1.54.0 may cause undesired issues, hopefully not, but maybe someone else can weigh in.

I can't think of anything immediately, but regardless, I'd still recommend using v1.51.0.

**Comment by mvines** [comment]
If you run `./cargo` from the release branch then you'll build with version of Rust that's "supported" for that branch automatically.

**Comment by ivanmlerner** [comment]
I am also using Rust v1.54.0.

> If you run `./cargo` from the release branch then you'll build with version of Rust that's "supported" for that branch automatically.

I downloaded the sources from the releases page, and I am running cargo with the --release argument, but I still get the error.

**Comment by steviez** [comment]
> I am also using Rust v1.54.0.

Cool, well at least we can explain the error then; you need to use v1.51.0

> I downloaded the sources from the releases page, and I am running cargo with the --release argument, but I still get the error.

So, to confirm, you ran the `./cargo` script in the downloaded/expanded source directory? Alternatively, you can manually install a version like this:
```
$ rustup toolchain install 1.51.0
```
Assuming you have v1.51.0 on your system, you also need to make sure that version gets used in the build. If you just run `cargo build`, the default toolchain / rust version is used. Given that you had v1.54.0 installed, it is unlikely that downloading an older version will update the default (this was the case on my system, the default remained v1.55.0). When building, you can explicitly specify a version such as below.
```
/solana/ledger$ cargo +1.51.0 build
    ...
    Finished dev [unoptimized + debuginfo] target(s) in 0.45s
```
You could also update the default toolchain to v1.51.0 such that `cargo build` uses v1.51.0. You can check out the [docs](https://rust-lang.github.io/rustup/index.html) here to learn more about the tooling.

**Comment by steviez** [comment]
@ivanmlerner & @switchbrad - I'm going to assume the 👍 means you were able to get things building (comment back if this isn't the case). We may still tweak the README a bit further (per mvine's comments), but hopefully the updates I made at least steer people in the right direction with `cargo` & `rustup`. In any case, thanks for making the issue & chiming in!
