### ISSUE TITLE
Fail to download v1.7.11 on mac

### ISSUE THREAD

**Issue by swagzhang** [solana-labs/solana#19735]
When I run 
`sh -c "$(curl -sSfL https://release.solana.com/v1.7.11/install)"`
it reported Error

> Error: error decoding response body: invalid type: map, expected a sequence at line 1 column 0

But `sh -c "$(curl -sSfL https://release.solana.com/stable/install)"` works normally. 
I just wonder why this happened?

**Comment by tayab2468** [comment]
facing same issue but on Ubuntu

**Comment by steveluscher** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Solana itself.

Questions like yours deserve a purpose-built Q&A forum. Unless you have evidence that this is a bug with Solana itself, please post your question to the Solana Stack Exchange using this link: https://solana.stackexchange.com/questions/ask

**Comment by Henry-E** [comment]
Just noting that our CI also is having this issue quite a lot lately.

https://solana.stackexchange.com/questions/4957/downloading-solana-cli-failing

An example of the failing CI that happens seemingly at random
 https://github.com/coral-xyz/anchor/actions/runs/3707102076/jobs/6283336731

**Comment by lorisleiva** [comment]
Hi there 👋 

I'm experiencing the same issue and I'm not sure there is any post to track this as:
- this issue was labelled as a question, requesting a Stack Exchange post instead.
- the replies on the [relevant Stack Exchange post](https://solana.stackexchange.com/questions/4957/downloading-solana-cli-failing) asked to open an issue on GitHub.


This is causing CI/CD to fail at random times, making it difficult to create stable pipelines.
