### ISSUE TITLE
I wanted to update docs, but github version is different from docs.solana.com

### ISSUE THREAD

**Issue by slrslr** [solana-labs/solana#19792]
#### Problem

https://docs.solana.com/wallet-guide/web-wallets
is different from 
https://github.com/solana-labs/solana/blob/master/docs/src/wallet-guide/web-wallets.md

The first one shows "Phantom is a non-custodial, chrome extension," which is outdated description, it also works on Firefox etc.

I do not understand why these pages are different and how to update the docs.solana.com it is confusing, i would expect docs.solana.com links directly to github sub-page where one can edit.

**Comment by steviez** [comment]
> I do not understand why these pages are different and how to update the docs.solana.com 

@slrslr - docs.solana.com get updated from the files in GitHub each time we drop a release on our latest branch. That change was made to master in https://github.com/solana-labs/solana/pull/19004, and backported to 1.7 in https://github.com/solana-labs/solana/pull/19725. The backport to 1.7 just went in several days ago, and we haven't had a release since then so docs.solana.com do not reflect this particular change yet.

You may have noticed the backport trailed the original commit by more than a month; we probably could have updated sooner (and typically do) but it just slipped through the cracks.

> i would expect docs.solana.com links directly to github sub-page where one can edit.

Our doc source in GitHub gets built into the end product at docs.solana.com. Building it gives the docs more of a book/manual feel (navigation to next/previous page, sidebar table of contents, etc) at the expense of updates to the manual lagging slightly behind the updates to the source.
