### ISSUE TITLE
Docs: please clarify difference between pubkey and wallet address

### ISSUE THREAD

**Issue by tredondo** [solana-labs/solana#20235]
#### Problem

On the [paper wallet](https://docs.solana.com/wallet-guide/paper-wallet) page, if you follow the Seed Phrase Generation instructions (`solana-keygen new --no-outfile`), "The value shown after pubkey: is your wallet address."

Then there is this,

> Note: In working with paper wallets and file system wallets, the terms "pubkey" and "wallet address" are sometimes used interchangably.

This is confusing. (Also, "interchangably" is a typo.)

1. The Public Key Derivation instructions (`solana-keygen pubkey prompt://`) produce "the derived solana BIP44 wallet address", which is different from the pubkey at the first step. To get *that* pubkey, the user must use `solana-keygen pubkey ASK`.
2. To [verify](https://docs.solana.com/wallet-guide/paper-wallet#verifying-the-keypair) with `solana-keygen verify <PUBKEY> prompt://`, the user must enter that "derived solana BIP44 wallet address", not the pubkey from the first step (that would produce "Failed".

#### Proposed Solution

I don't know, I'm confused. This is probably stupid simple for experienced devs, but I'm new to crypto.

What's the point of `solana-keygen new` even displaying the pubkey? Why doesn't it display the wallet address? Because more than one could be derived? Why not display the default one then?

**Comment by rlora** [comment]
Agree, I'm confused as well. The documentation says **The value shown after pubkey: is your wallet address.**.
However `pupkey prompt` will yield a different address that is successfully validated, when in contrast the **pubkey** shown after **new** fails validation.

I would send funds to the wallet that is successfully verified but the docs would point me in the wrong direction. What happens if someone send funds to the pubkey printed after new? Can they be recovered with the seed phrase?

Thanks!

<img width="848" alt="wallet" src="https://user-images.githubusercontent.com/1533339/147372183-0e147066-0ac7-4ae7-94ac-986089b8baba.png">

**Comment by stepanglamin** [comment]
The mnemonic phrase and keypair are seem to be generated for separate wallets and it's the public address for keypair that is printed right next to mnemonic phrase.
https://github.com/solana-labs/solana/issues/23796

**Comment by sarkarshubhanshuk** [comment]
Hello, any explanation for this question?
