### ISSUE TITLE
Support for BLS12 based signature verification

### ISSUE THREAD

**Issue by sudesh-supraoracles** [solana-labs/solana#20241]
Hi Team!

Since many protocols are putting BLS12 to use for digital signatures.
I want to verify BLS 12 based signature from Solana smart contract.

Hoping for some positive inputs/response on this.

**Comment by jon-chuang** [comment]
Currently the VM layer is still a little slow, BLS12 pairings would probably blow up to 40ms I reckon. (Ref: https://github.com/solana-labs/rbpf/pull/196). 40ms is too slow for the Solana runtime, as it slows down an entire batch of transactions.

Largely, for cryptography, this is due to the lack of a u64xu64->u128 mul instruction which exists on x86 but not in bpf. If you could come up with benchmarks for a rust BLS12 library that supports optimised u32 representation and field arithmetic, and benched the results, that could provide insight.

One could further think of batching BLS12 sigverify via random coefficients.

Else for the time being one might need precompiles, but you’d need to prove your specific use case and need.

**Comment by ryoqun** [comment]
> u64xu64->u128 mul instruction which exists on x86 but not in bpf.

I wonder this could be improved upon with #20323 ? (CC: @Lichtso)
