### ISSUE TITLE
Documentation deployment painpoints

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#20281]
#### Problem
It's hard to discover the correct docs. Devs should typically use https://docs.solana.com to know what it is live on the testnet cluster, for upcoming testnet changes they can go to https://beta.docs.solana.com and cutting edge changes from master are hosted at https://edge.docs.solana.com. These mappings aren't very intuitive, there's no way to see the docs for the latest mainnet cluster version, and it's also difficult to discover the beta and edge docs.

The current deployment of the Solana docs is split into 3 apps, one for each subdomain. For edge, we deploy from the tip of the master branch, beta is deployed from the tip of the latest release branch (currently v1.7), and docs.solana.com is updated whenever a new patch release on the latest release branch is cut (e.g 1.7.12).

Our release branch system is setup so that new features land in master first, and then can be optionally backported to one or both of the release branches (beta and stable). This includes changes to docs currently. But it's a pain to always remember to backport those changes since most of the docs changes (besides RPC API changes) apply to all versions of Solana.

#### Proposed Solution
- Add a version dropdown to docs.solana.com which makes it easy to go to the appropriate docs
- Accessible versions should include (using the current minor release versions):
    - `v1.8.0-alpha`: tip of master
    - `v1.7.13-beta`: tip of beta (v1.7)
    - `v1.7.12`: latest beta release
    - `v1.6.27-beta`: tip of stable (v1.6)
    - `v1.6.26`: latest stable release
- Ideally both past minor and patch releases are viewable as well

##### RPC API Docs
I think it would be a good idea if only the RPC API docs were versioned and we added a new section for new runtime features and fixes that get updated in new releases. But the main chunk of documentation which describes how Solana works can be static and unversioned.

**Comment by Josh-Cena** [comment]
@jstarry The doc versioning system of Docusaurus itself allows you to do that pretty easily, and yeah, having three identical-looking domains is pretty confusing. Making part of the documentation unversioned won't be too much trouble either, as long as they don't share the same sidebar. So per your description I don't see any blocker.

The only problem on top of my head is the domain name mapping. Are you giving up on the https://beta.docs.solana.com domain, or will you redirect that to https://docs.solana.com/1.7.13-beta/? Not sure how the site is deployed, and solutions can vary.

**Comment by jstarry** [comment]
> Making part of the documentation unversioned won't be too much trouble either, as long as they don't share the same sidebar. So per your description I don't see any blocker.

@Josh-Cena What do you think the best way to architect this in docusaurus would be? Maybe host a separate versioned docusaurus app at a subroute like docs.solana.com/rpc? And then link to that from the main unversioned docusaurus app?

> The only problem on top of my head is the domain name mapping. Are you giving up on the https://beta.docs.solana.com domain, or will you redirect that to https://docs.solana.com/1.7.13-beta/? Not sure how the site is deployed, and solutions can vary.

Dropping the subdomain is fine, I think we could have https://docs.solana.com/v/beta/* redirect to https://docs.solana.com/v/v1.7/* and https://docs.solana.com/v/edge/* redirect to https://docs.solana.com/v/1.7.13-beta/*

**Comment by t-nelson** [comment]
> Dropping the subdomain is fine
Agreed

Can we stick to the existing edge, beta, stable channels that tract the tip of each branch?  Use these as the preferred entrypoints, then the user is allowed to choose a specific version.

**Comment by Josh-Cena** [comment]
> Maybe host a separate versioned docusaurus app at a subroute like docs.solana.com/rpc?

You can use different docs plugins: https://docusaurus.io/docs/next/docs-multi-instance#versioned-and-unversioned-doc Usually there isn't much need for a separate Docusaurus app

> Can we stick to the existing edge, beta, stable channels that tract the tip of each branch?

We would need to do server-side redirects first, I don't think Docusaurus handles subdomains very well while treating them as the same site. The subdomain would continue to work, just that users don't _stay_ there. I think Vercel supports redirect patterns like `beta.docs.solana.com/*` -> `docs.solana.com/beta/*`? Haven't checked your exact docs structure so not sure how hard that would be.

Setting the deploy action would be a bit hard since we are merging three branch heads into one Docusaurus app, but I think that's manageable. Not sure if Crowdin would work with that, though, I would need to check how Crowdin pulls and pushes translations

**Comment by slorber** [comment]
> Most of the docs changes (besides RPC API changes) apply to all versions of Solana.

For docs that are "common" across versions, you'd rather use a separate unversioned docs plugin instance, as we do on the Docusaurus community docs:

https://docusaurus.io/community/support

And you can still keep the RFC part versioned

> But it's a pain to always remember to backport those changes

If backporting docs is painful due to applying to multiple versions (I assume it is more frequent than code...), then you may prefer only using the `master` branch to manage your doc

It would require less work as you would not need to handle multiple git branches and PRs to do the backporting: just copy/paste the content in `versioned_docs_rpc/version-1.6/` and a single PR can contain all the docs changes at once.

This also means that by default:
- all RPC versions will be on subpath instead of subdomains by default, so need to redirect old urls
- a single SPA will be built for all the RPC versions
- if RPC doc is large and you have a lot of versions, it will take longer to build (Docusaurus and in general babel/webpack/mdx are not the fastest tools, hopefully we'll improve this)

If you still want to deploy one app per subdomain, the docs plugin has a `onlyIncludeVersions: ["1.6"]` that would allow you to deploy just the prod doc with the prod RPC version (you can use env variables on Vercel/Netlify for each project).

> Not sure if Crowdin would work with that, though, I would need to check how Crowdin pulls and pushes translations

I'm not sure either, we didn't test Crowdin much with its branching system considering all Docusaurus docs are usually on a single branch.

**Comment by t-nelson** [comment]
> We would need to do server-side redirects first

Sorry, I wasn't referring to keeping subdomains.  Those can die in a fire.  I'm more interested in keeping the docs version meta reference naming consistent with what we use elsewhere in tooling.

**Comment by slorber** [comment]
I don't understand what docs version meta reference naming means 😅

**Comment by Josh-Cena** [comment]
> I don't understand what docs version meta reference naming means 😅

`beta` and `edge` I guess, that would be achievable through version settings

**Comment by CriesofCarrots** [comment]
Just catching up here. I love the idea of a version dropdown.
I agree with Trent that'd be less confusing to keep the stable/beta/edge terminology, rather than adding new alpha/beta definitions.

I'm not sure what the proposal is for the default docs version users, but if it's something similar to what's currently published to docs.solana.com, I'd like to see if we can make a change. As noted above, docs.solana.com currently publishes from the most recently tagged patch of the solana beta channel, including pre-releases. This means that the CLI docs seem to be recommending installing a software version that we haven't actually decided to recommend yet. I think ideally the default doc version should be the latest non-pre-release. Hopefully, that won't be too tricky to automate.
