### ISSUE TITLE
Solana BPF v2

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#20323]
#### Problem

Solana Bytecode Format is a variation of eBPF.  Some of the architectural requirements are different from eBPF and what Solana needs.  A new version 2 is needed to move away from BPF and meet the specific needs of Solana

#### Proposed Solution
- [x] #34258
  - [ ] BTF ELF-section parsing
  - [ ] Static type inference
  - [ ] Instruction stream verification
- [ ] Dynamic linking / dynamic dispatch
- [ ] Decide about implicit vs explicit sign extension in 32bit ALU operations (https://github.com/solana-labs/solana/issues/32924)
- [ ] ISA changes: #34250
- [x] Reduce the overhead for the loader at runtime, by letting the linker concatenate sections to become consecutive in virtual address space (https://github.com/solana-labs/rbpf/pull/284 and https://github.com/solana-labs/rbpf/pull/301)
- [x] Restrict the control flow:
  - [x] Only symbols registered in the ELF or referenced by `call` are valid destinations for `callx`. (https://github.com/solana-labs/rbpf/pull/397 and https://github.com/solana-labs/rbpf/pull/439)
  - [x] Functions can not start in the middle of a `lddw` instruction (https://github.com/solana-labs/rbpf/pull/440)
  - [x] Jumps have to stay within a function, only `call` / `callx` can reach other functions. (https://github.com/solana-labs/rbpf/pull/454)
  - [x] Forbids the fall-through at the end of a function, which now must be a unconditional-jump back into the function. (https://github.com/solana-labs/rbpf/pull/522)
- [x] toolchain administration
  - [x] New target triple SBFv2
  - [x] New or featurized llvm backend
  - [x] New tool `cargo-build-sbf`
  - [x] Tooling changes to specify version (default to v1 for now, eventually to v2), eg. `cargo build-sbf --arch=sbfv2`

From a documentation perspective SBFv2 will still be referred to as "SBF" and when calling tools like `cargo build-sbf` a default arch will be provided, v1 initially, then a switch over to v2.

**Comment by jackcmay** [comment]
FYI @Lichtso @dmakarov

**Comment by Lichtso** [comment]
I have been thinking, that instead of adding a few new instructions and removing some others from BPF, it might be better to go with a p-code approach directly.

We are breaking compatibility with BPF in a major anyway and we want to support other native architectures besides x86-64, such as ARMv8 AArch64 and maybe SPIR-V. These would require an entire data flow analysis and register allocation at least, because they are so different from x86-64 in their data-flow style and would not work as well as the current BPF to x86-64 conversion.

Furthermore, we could think a lot more about the final conversion steps and e.g. do things which BPF is not meant for like:
* Staying in SSA or implicit operand addressing to simplify register allocation and avoid the need for data flow analysis
* Staying in structured programming to avoid the need for control flow analysis
* Variable length instruction encoding and text section compression
* Prefetch-like hits for address translation
* Hints for loop vectorization
* Wide range of data encodings such as 128-, 256-, 512-bit values and vectors

**Comment by Lichtso** [comment]
> What does this mean in practical terms?
> redefine the BPF instruction set completely?

What I suggest is not to fork & modify BPF any further but use something else entirely.
So far I looked at [WASM](https://webassembly.org/) and [GNU lightning](https://www.gnu.org/software/lightning/manual/html_node/index.html). Designing our own from scratch is also possible.

**Comment by dmakarov** [comment]
> > What does this mean in practical terms?
> > redefine the BPF instruction set completely?
> 
> What I suggest is not to fork & modify BPF any further but use something else entirely. So far I looked at [WASM](https://webassembly.org/) and [GNU lightning](https://www.gnu.org/software/lightning/manual/html_node/index.html). Designing our own from scratch is also possible.

I agree this is indeed something to think about.

**Comment by dmakarov** [comment]
> You mean as a form of SSA, right? What about an implicit operand addressing like a stack (FILO) or queue (FIFO) 

Yes, this essentially echoes your suggestion of staying in SSA. By stack machine you mean we would redefine BPF abstract machine to be a stack machine the same as Java VM? I guess it's a possibility, but then we really need a good run-time binary translator (in rbpf) to optimize the code. I'm not sure why you're so concerned with instruction encoding -- is it to reduce the code size of on-chain programs?

**Comment by Lichtso** [comment]
> is it to reduce the code size of on-chain programs?

Yes, I think the BPF 8-byte fixed instruction size is terribly wasteful. It might not be a concern for the Linux kernel, for us however, program size is limited by account size.

> would redefine BPF abstract machine to be a stack machine

The queue (FIFO) variant might also do the trick and be more straight forward as the instruction schedule can stay in the same order.

Let's say we have a SSA form like this:
```LLVM
...
%3824 = add %3818, %3821
%3825 = add %3815, %3823
%3826 = mul %3824, %3825
```

To convert to the queue machine representation you simply:
- Remove the destination operand as that implicitly is defined by the instruction index.
- Encode the source operands as relative to the instruction index of the next instruction.

```LLVM
...
add %5, %2
add %9, %1
mul %1, %0
```

Not only does it need no destination operands, but also the numeric value of the source operands is bounded.
The instruction scheduler can achieve staying in the window of possible relative operand addresses with the same strategy as it uses for the window of possible short jumps.

**Comment by Lichtso** [comment]
It is already buried in the depths of this conversation:

> ARMv8 AArch64: It has almost double the registers (31) that x86-64 (16) and BPF (11) have.

The reason for register allocation is not spilling but simply utilizing all the registers ARM has, as we want to target that in the future as well.

**Comment by Lichtso** [comment]
We should try to get the linker to concatenate similar sections (such as all read-only sections) and place them consecutively in virtual address space, so that we don't need to allocate, copy and fill the gaps with zeros here: https://github.com/solana-labs/rbpf/blob/cd37c0bf61dcce22fa48b594005237eeb130af76/src/elf.rs#L430.

**Comment by bernieblume** [comment]
Very interesting discussion. Any update on that? Does anyone know the reason why the initial Solana design ended up being based on eBPF rather than WASM, given the fact that there are a bunch of other, pre-existing smart contract chains that are WASM-based. Was it just the Solana founders' familiarity with eBPF?

**Comment by Lichtso** [comment]
I finished the task "Restrict the callx jump targets to only allow known symbols": https://github.com/solana-labs/rbpf/pull/397

However, there are some new ideas what to add to SBFv2:
- BTF for type tracking at load time. Can potentially be used for skipping memory access checks at runtime.
- Restricting jumps to their local function.
- Removing `sub imm` or swapping the register and immediate operands roles.

**Comment by Lichtso** [comment]
In the last two weeks I spent some time refactoring, cleaning up and testing SBPFv2 in RBPF. During that I discovered multiple issues that we should consider changing.
I think points 1, 3 and 4 should definitely be implemented before releasing SBPFv2 in program-runtime-v1. The rest is only required for program-runtime-v2 but IMO it would still make sense to add it now so that we can get more testing exposure.

#### Proposed Solution

1. In order to speed up and harden the ELF parsing we would ignore relocations and instead apply all of them in `lld` beforehand. Relocations may still be emitted for debugging purposes or future use. The issue with relocations is that they can modify any byte in the ELF, including the headers and other sections and thus influence the rest of the parsing process.
Currently, if the output type is set to "shared" then `lld` outright refuses to `--apply-dynamic-relocs` and only supports `--emit-relocs`. This needs to be fixed.

2. In order to unify the target addressing scheme of `call` and `callx` and allow both to address internal and external functions,
we would switch from relative addressing to hash keys for internal calls too, just as we did for external calls (see static syscalls).

3. In `llvm` the code emitter for the `call` instructions encoding would be changed:
- from `src=1` to `offset=0` for internal function calls
- from `src=0` to `offset>0` for external function calls

That way the `offset` and `imm` fields together form an 56 bit function address:
- The MSB 16 bit (from `offset`) mark the program the address belongs to: `0` is `self` and everything higher is the index in the list of `DT_NEEDED` entries plus one.
- The LSB 32 bit (from `imm`) are the hash key inside the program

4. Previously the function registry was the unified set of addresses which are relative call targets and relocation targets. With both of these gone, we would instead build the function registry directly from the dynamic symbol table. For this, `lld` should build the dynamic symbol table from local and global functions and nothing else.

5. In order to avoid having to hash all symbol names when parsing the ELFs, we would instead encode the hashed value in the name field of the symbols in binary directly. This would only apply to the dynamic symbol table and the normal symbol table would still use string names for debugging.

6. In order to link against external programs `lld` would emit a list of `DT_NEEDED` entries with base58 encoded pubkeys (instead of file names).

**Comment by Lichtso** [comment]
> This forces a sequential dependency on a memory load for every function call (to look up hash=>destination). Since function calls are quite common, this may worsen performance and trash caches.

Good point, at least for interpreters I guess.

> Instead, I would go the other direction

We already do distinguish between what you refer to as call and farcall with the `src` field in the `call` instruction. Instead what we need is a way for dynamic calls (the `callx` instruction) to target external functions. How about the following slight modification: Use the 58-bit mixed address (`offset` and `imm`) and have the 16 MSBs zeros be encoded as absolute IP/PC and all others as hash keys. That would still unify `call` and `callx` instructions and avoid an additional lookup for internal function calls.

> Can you be more specific how this would work? Does the name field point to a hex representation of the hash? If both name and hash are specified, what is the behavior when the hash does not match the name?

We could either encode the `u32` key directly where the index into the string table would be, or Hex-ASCII encode it as 9 characters (including `NULL` termination) in the string table. The later would be slightly less efficient because of the indirection but keep compatibility with other tooling such as disassemblers, readelf etc.

> Perhaps we can save some performance using hex instead. A quick benchmark shows that the reference base58_decode_32 algorithm (used in bs58) takes about 1079ns, while fd_base58 takes 123ns. Not the end of the world, I guess.

Hex is fine too, base58 is just a bit nicer for debugging but probably not worth it.

> Let's use this opportunity to specify strict validation rules.
> Generally though, I would prefer a new Solana-specific object format instead of working around limitations in ELF. ELF lacks the features we need. I realize that the additional work required to make such a format may be impractical, but I want to at least give it a try.

I think the consensus with our team ATM is that we stick with ELF to keep the tooling reach, but restrict it down as much as possible for ease of parsing.

**Comment by Lichtso** [comment]
@alessandrod Pointed out to me, that we don't have to hack the symbol hashes into the symbol table or symbol strings directly. Instead we can use the [`DT_GNU_HASH`](https://flapenguin.me/elf-dt-gnu-hash) section to define hash values for the symbols in the ELF with almost no overhead. He also recommended the paper [Drepper, Ulrich. "How to write shared libraries."](https://akkadia.org/drepper/dsohowto.pdf) on the topic of linking and shared objects in ELF.
