### ISSUE TITLE
Proposals for long-running rewards computations

### ISSUE THREAD

**Issue by carllin** [solana-labs/solana#20384]
#### Problem
Rewards calculations scales linearly with the number of stake accounts and can take multiple seconds or even longer as the number of stake accounts grows. Right now all of these computations happen on bank creation, which stalls progress

#### Proposal 1: Sharding the computation over multiple slots in an epoch

Similar to rent, this would involve computing in every slot rewards for a given range of pubkeys. We could take the write locks for the stake keys at the beginning of the slot, and run the computation overlapping the slot so that the work doesn't accrue a bunch of latency at the end of a slot

###### Downsides 

* Different accounts will see their rewards at different times in the epoch, which may not be the greatest user experience
* Like rent, our index is not optimized for range queries, so finding for the stake accounts in a range may require scanning a large range of the sharded accounts index, which may stall other banking/replay operations touching the same range of sharded keys. This may not be a huge deal if we have a bunch of shards in our Accounts index.

#### Proposal 2: Long running background process that writes updates to a "future" slot

This proposal will require a lot more changes. The idea is to:

* Prevent any modifications to stake accounts for the first `N` slots of an epoch, where `N` is based on the estimated time we think the rewards calculation will take.

* Spin up a background computation that iterates over all the stake accounts and runs the rewards computation, writing the new stake accounts with rewards to a new AppendVec in AccountsDb called *rewards*

* After the computation is done, also hash all of the stake accounts changes. Call this hash `H`

* Any slot `M` that cross the boundary of slot `N` has to 
     - Wait for the background computation to finish
     - We page in the AppendVec containing all the changes into a different storage map, different than the slot based storage map. The background computation will write into the account index for all stake accounts a special entry that signals they need to check this storage for updates if the slot they are looking up is `> N`, the boundary slot
     - Incorporate the hash `H` of all these stake account changes  into the bank hash for slot `M`

**Comment by mvines** [comment]
> Different accounts will see their rewards at different times in the epoch, which may not be the greatest user experience

I feel this makes Proposal 1 a non-starter unfortunately.  We can't have epoch rewards happening at different times for different stake/vote accounts, this'll likely break all downstream reward integrations as well as user expectations about when rewards are delivered.

**Comment by ryoqun** [comment]
Well, I pondered on this to some extent.

considering recent staking account growth and the nature of staking as a pivotal instrument for Solana's network. I'm inclined to my variant of Proposal 1, which avoids the different timings across staking accounts. However the following my idea delays the staking reward distribution by a epoch.

Proposal 1a.

Over N+1 epoch, firstly slowly compute the staking rewards for individual stake accounts. At the start of N+2 epoch, all staking rewards for N epoch is _available_ (it will be reflected when touched by tx/rpc like rent; otherwise the distribution to untouched stake accounts are spread across the epoch, like rent again)

Pros
- no perf related worries for inflation code again
  - (at the cost of another hard req for ordered index..)
- current inflation math won't be changed much (so less risk)
- no more bank.stakes cache at the accountsdb write path (i never liked this... xD)
- the pubkey prefix scanning code is pretty robust, thanks to the eager rent collection.
- in the future, staking reward calc could be more complex (well, only vote_credits isn't ideal, i guess)

Cons
- delayed inflation reward payout across board by 1 epoch
- increased storage (3x) due to impl.

Implementation details

Simply put, pipeline with shadow copies over epochs.


- Step 0: (at epoch N): Create shadow copies of vote/stake accounts at pda(stake/vote account address, epoch, bank hash of last epoch's bank) _at every writes of all kinds to the accounts_ (pda-ing requires special purpose index or ranged calculation but this is desirable against pubkey prefix distribution imbalance)
  - I'm also thinking we also need this pda indirection for eager rent collection (= rent by pubkey prefix over an epoch)
  - Also, I'm assuming these additional index don't pressure mem with the new disk based index mechanism?
- Step 1: (at epoch N+1): calculate staking rewards using the last snapshot of accounts from Step 0 and write results to pda(stake account, epoch, "rewards") or something.
- Step 2: (at epoch N+2): like rent, reflect the rewards into the original stake account when touched or by pubkey prefix
- Step 3: (at epoch N+3): remove the temporary staking reward result account (again slowly)

Hope this uniform delay could be acceptable?

**Comment by ryoqun** [comment]
I wonder how's going with other pos blockchain's implementation, regarding staking reward calc./dist.. I'll check it later if no one can shed light on this. :)

**Comment by ryoqun** [comment]
hmm, interesting

- Polkadot: staking is limited?
  - https://support.polkadot.network/support/solutions/articles/65000168057-how-do-i-stake-nominate-on-polkadot-
  - https://polkadot.network/blog/polkadot-and-kusama-staking-changes/

**Comment by ryoqun** [comment]
more interesting, cardano are facing similar issue like us right now. let's get along with by overcoming the grow pains.... :)

https://github.com/input-output-hk/cardano-node/issues/2851

**Comment by mvines** [comment]
Of course the real solution is stake pools!

**Comment by jstarry** [comment]
I suggest that we do what most yield farming protocols do and use a redemption model which doesn't require writing to the accounts for each reward cycle. Balances are only updated when a user redeems their stake rewards for lamports. We could add a special runtime instruction for this which requires the user to pass all necessary historical stake data required for that delayed computation. All stake weighted parts of the protocol can continue making use of the stakes cache to determine the full delegated stake balance for each validator as if all stake accounts were redeemed.

**Comment by jstarry** [comment]
Sounds like lazy/manual redemption could work but there are a few big action items:
1) Determine what (if any) impact this has to validator operations and discuss with them
2) Propose how redemption will work for stake accounts since the program runtime doesn't support unbalanced instructions currently. At minimum I think we need a `last_redeemed` field for stake accounts for this to work.

**Comment by ryoqun** [comment]
late for the party.

> I suggest that we do what most yield farming protocols do and use a redemption model which doesn't require writing to the accounts for each reward cycle.

first of all, this redemption idea sounds a nice inspiration from the defi. note that I'm still the defi newbie. my understanding of the defi redemption mechanism is still only high level one...

here's some random thoughts:

- maybe we still need to run the heavy rewards calculation at epoch boundaries (now off-chain) for the `core`'s various staked weighted functionality and redemption by impatient users)
  - in that case, tx cost with stake::redempt should be handled differently (esp at the start of epoch like stalling if many?)
    - how about composability/compatibility with (existing) staking pools?
- rpc also needs to be updated? (also wallets and exchanges with staking support).
- the lazy calc. will necessitate to retain (potentially large) staking calc data or latest (actual) balance of all stake accounts? 
  - maybe we charge extra cost for this?
- slashing and total-/circulating supply calc also will need an update.

> Propose how redemption will work for stake accounts since the program runtime doesn't support unbalanced instructions currently. At minimum I think we need a last_redeemed field for stake accounts for this to work.

Come to think of it, we actually had this redemption mechanism partially but removed it due to gaming concern (different SOL rewards depending on timing). SysvarRewards and the normal `credits_observed` should work without the painful stake account versioning maybe?

**Comment by ryoqun** [comment]
oh, another wild idea is start to pre-calculate next epoch's pending rewards distribution early and then just swap it (at the stake cache layer?) at the start of new epoch after fine-tuning last bits of few slots before finalization?

**Comment by ryoqun** [comment]
> oh, another wild idea is start to pre-calculate next epoch's pending rewards distribution early and then just swap it (at the stake cache layer?) at the start of new epoch after fine-tuning last bits, regards the few last slots before finalization?

hhm, but this distinct 2 code path could be easily turned into a dos attack vector. ;)

**Comment by brooksprumo** [comment]
Can the stake rewards calculation be spread out over the whole epoch instead of occurring _at_ the new epoch's first slot?

I think this might delay receiving the stake rewards by one epoch, but maybe that latency doesn't really matter assuming stake likely remains delegated for multiple epochs and doesn't need to move often?

**Comment by joncinque** [comment]
I'm very late to this party as well!

> Propose how redemption will work for stake accounts since the program runtime doesn't support unbalanced instructions currently. At minimum I think we need a last_redeemed field for stake accounts for this to work.

How about going the lazy approach through a `RewardsPool`?  But not the one that currently exists. All of the rewards go into some pool, either a pool per vote account or a general pool.  A new `redeem` instruction on the stake program moves however much a stake account is entitled to from the pool and into the stake account.

> SysvarRewards and the normal credits_observed should work without the painful stake account versioning maybe?

As long as it goes back far enough, we should be able to properly figure out the rewards, even multiple epochs later, correct?  The `credits_observed` might actually be the saving grace here, since it can also tell us when we last received rewards.

> how about composability/compatibility with (existing) staking pools?

Stake pools require some sort of "accounting" at the start of epochs anyway, so it would actually be really easy to tack on some additional `redeem` instruction for all of the stakes in the pool.

Are there any other programs that directly use stake accounts?  Explorers and RPC providers could be updated to just do some math and show how much can be redeemed by the user.

**Comment by brooksprumo** [comment]
@aeyakovenko posted [an idea on Discord](https://discord.com/channels/428295358100013066/754723351389536348/936753005238292521) today that could solve this:

* Accounts pay for rent upfront
* Each account would now track when its rent expires (i.e. `rent_expiration_slot`)
* Accounts would need to pre-pay for the next rent duration before the next `rent_expiration_slot` (maybe this could be done automatically?)

This would help the validators, as now they'll be compensated for all accounts (instead of just rent-paying accounts, which are the minority).

This would help the runtime by removing the need to run rent collection by scanning all the accounts every epoch. I.e. `generate_index()` could clean up these accounts when starting up from a snapshot.

Some questions:

* How to handle the pre-paying for the next rent duration? Who checks that? We're trying to remove the need to scan all the accounts...
* How to handle the cleaning up of these accounts? Is generate_index() sufficient? What if a node never reboots? Will it be storing all these now-dead accounts indefinitely?

**Comment by brooksprumo** [comment]
To follow along from my comment above, I was thinking about how to tie in lazy rent collection (i.e. no scanning of accounts) with incentives to find-and-close accounts that should be rent collected.

There are parallels I see to how some DeFi programs that I've heard about do this (from what I remember). Specifically,  accounts that should be liquidated/closed are done via a transaction, not by a runtime. For example, lets say Account A should be closed. Other people (ex Account B) can _send transactions_ to query that account to identify it should be closed, then send _another_ transaction to tell the program to close the account. Then Account B would get some portion of the reward for closing Account A. The remaining portion goes to the program (or runtime/validators in our case).

Regular users are now incentivized to find and close accounts. These are regular transactions, so the economics of transactions already handles this. A new `CloseAccountsAndReapRewards` transaction would have a high enough cost to dissuade users from sending erroneous transactions without being sure the account should actually be closed.

What remains is how much rewards should be given to the user, and where those rewards come from. If accounts should only be closed-and-collected once they've reached a balance of 0 lamports, there would be no additional rewards to collect. 

If accounts can be closed below a threshold (i.e. rent exempt minimum), that could work, but traditionally those rewards have gone 100% to the validators; would the validators now get a smaller reward?

Maybe [creating new accounts should have a fixed upfront cost](https://github.com/solana-labs/solana/issues/21348#issuecomment-973296101) _in addition_ to rent? This way, validators get the rewards when accounts are created, and users get the rewards when accounts are closed?

Obviously still lots of details to nail down, but is this a feasible path to continue investigating?

**Comment by carllin** [comment]
@brooksprumo are your proposed solutions about rent? This issue was originally about the stakes rewards computation

**Comment by brooksprumo** [comment]
> @brooksprumo are your proposed solutions about rent? This issue was originally about the stakes rewards computation

Oops, thanks! Moved over to the correct issue now:
https://github.com/solana-labs/solana/issues/17178#issuecomment-1026229951
https://github.com/solana-labs/solana/issues/17178#issuecomment-1026230118

**Comment by sakridge** [comment]
@HaoranYi can you try to take a look?

**Comment by HaoranYi** [comment]
Sure. I will start looking at this.

**Comment by HaoranYi** [comment]
[joncinque](https://github.com/joncinque) The RewardsPool that you describe is some kind of on chain storage? Some thing like a map to store the available stakes reward for account? At the beginning of epoch, we update the on map with the new rewards. And later the stake account can use the "withdraw" instructions to withdraw the rewards. Is that what you are proposing?

**Comment by joncinque** [comment]
The general concept is to store the reward lamports "somewhere", either in a new cluster-wide account or the vote account, and then be able to calculate on-chain during withdrawal how much a stake account is entitled to

**Comment by HaoranYi** [comment]
A related proposal for partitioned epoch reward can be found here. 
https://github.com/solana-labs/solana/pull/27455
