### ISSUE TITLE
[storage mining] Validator doesn't pick what storage proofs it will verify

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#2048]
#### Problem

A validator needs to pick some set of proofs to verify each storage epoch and then submit a ProofValidation transaction which enumerates which proofs are chosen and valid. A single validator probably does not have the capacity to verify the full set of storage proofs on chain in a given epoch, and it needs to reduce this set.

#### Proposed Solution

Implement what is described in the storage RFC about signing the storage PoH value and then sampling a set based on matching bytes in the signature and the storage proofs on chain.

**Comment by sagar-solana** [comment]
@sakridge, I'm trying to figure out what I need to do here. Just thinking out aloud, maybe you can help clarify. 
Right now storage_stage stores the signatures and block segment of every `SubmitMiningProof` tx that it sees. It doesn't really perform any validation on this as far as I can tell. 
Is this what this issue needs? 
- sign the storage blockhash 
- based on some math on the signature of each tx verify those txs (I don't fully understand how to verify aka can you help me understand what's inside a SubmitMiningProof and how a validator can confirm it's real)
- instead of storing all proofs, just store the ones it verified
- send over all the verified ones in a new ProofValidation tx after the entry crossing occurs

**Comment by sakridge** [comment]
The validation is this thing in `process_entry_crossing` where it calls ` chacha_cbc_encrypt_file_many_keys`:
https://github.com/solana-labs/solana/blob/47ddbbe53b4db53183e8f40b2f610b2fb5267f08/core/src/storage_stage.rs#L336

but it needs to submit the proof validation transaction still after doing this. There is a todo there.

**Comment by sakridge** [comment]
1. Signing the storage blockhash is done by the validator, that will then be the encryption key which is the `SubmitMiningProof::signature` field in that transaction.
2. A hash value which is `SubmitMiningProof::sha_state` is the result of the replicator doing the storage mining, the validator should verify that hash value is correct. If so, then it will indicate as such in the `ProofValidation` transaction.
3. Yea, it would need to save all the signatures for all the storage proofs it wants to validate and then at the storage epoch change start doing the validation and then submitting the `ProofValidation` transactions.
4. Yes.

**Comment by sagar-solana** [comment]
Thanks for the explanation!

**Comment by ryoqun** [comment]
close for now because archiver's direction is unclear?
