### ISSUE TITLE
Native loader tx instruction handling is incompatible between master and v1.8

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#21346]
@jackcmay @Lichtso it looks like this new err has made master and v1.8 incompatible. On v1.8 it's possible to invoke the native loader directly from a tx in which case `program_indices` is empty and the tx can still be processed successfully.

Here is an example tx that showcases the different behavior. The tx invokes the native loader in a way that runs the code path for a 0 lamport system ix transfer with the program_id set to the native loader id: https://explorer.solana.com/tx/inspector?message=AQABAxqaPUT28ZZYeGqKkcOfzL7aLBsifPzASKGnxP4QwCbm%252Bk%252BRkBm4gzLzoCATvtlllmIDwh%252B8XErqP9gYsdFvpjUFh4S%252FFIukKC%252BwEldIiKnxU6B9rfdlwEVcmpcDgAAAAL1QHO0HDnEf1DbxkmiM2jg37QuLnqbQDF9g5Y7HZgN3AQICAAEMAgAAAAAAAAAAAAAA

It was constructed with the following JS:
```js
    // create this to copy out the ix data    
    const ix = SystemProgram.transfer({
        fromPubkey: MY_KEY.publicKey,
        toPubkey: NEW_KEY.publicKey,
        lamports: 0,
    });
    
    const tx = new Transaction().add(new TransactionInstruction({
        programId: new PublicKey("NativeLoader1111111111111111111111111111111"),
        data: ix.data,
        keys: [{
            pubkey: MY_KEY.publicKey,
            isSigner: false,
            isWritable: false,
        }, {
            pubkey: NEW_KEY.publicKey,
            isSigner: false,
            isWritable: true,
        }],
    }));
```

_Originally posted by @jstarry in https://github.com/solana-labs/solana/pull/21238#r752263887_

**Comment by jstarry** [comment]
Related: https://github.com/solana-labs/solana/issues/21347

**Comment by Lichtso** [comment]
To fix the incompatibility:
- remove the line `debug_assert_eq!(first_instruction_account, 1);` in `process_instruction_with_program_logging()`
- add `.map_err(|_| InstructionError::UnsupportedProgramId)` behind `keyed_account_at_index(keyed_accounts, 0)?` in `instruction_processor::process_instruction()`.
- pull `InstructionError::ReentrancyNotAllowed` check out of `let program_id = if let Some(index_of_program_id) = program_indices.last() {` in `ThisInvokeContext::push()`
- and then put the `let program_id = if let Some(index_of_program_id) = program_indices.last() {` in `if self.invoke_stack.is_empty() {` without an else return error branch.
- Finally, add the empty transaction test case in `program-runtime/src/invoke_context.rs`.

**Comment by jackcmay** [comment]
In #3 above, where would the runtime check and fail a re-entrancy attempt and return `ReentrancyNotAllowed`?

If #4 isn't sufficient to address this issue then it looks like the issue was present before #21238, is that correct?

**Comment by Lichtso** [comment]
> In 3. above, where would the runtime check and fail a re-entrancy attempt and return ReentrancyNotAllowed?

Hmm, you are right. `program_id` needs to be an optional because it is needed in both cases of `if self.invoke_stack.is_empty()` and its `else` (because `contains` can only be `true` in the `else` branch).
So how about this:

- `let program_id = program_indices.last().map(|index_of_program_id| &self.accounts[*index_of_program_id].0);`
- Remove `return Err(InstructionError::UnsupportedProgramId);`
- Move `if contains && !is_last { return Err(InstructionError::ReentrancyNotAllowed); }` into the `else` block of `if self.invoke_stack.is_empty()`.
- Augment `program_id == crate::neon_evm_program::id()` to become `program_id == Some(crate::neon_evm_program::id())`

> If 4. isn't sufficient to address this issue then it looks like the issue was present before #21238, is that correct?

Yes, I think this phenomenon existed before but never caught our attention until now,
that we explicated our assumptions about the presence of executable accounts in these recent refactorings.

Yet, we have not seen any problem arising from this phenomenon directly, apart from unnecessary complexity caused by additional edge cases.

**Comment by jstarry** [comment]
> If #4 isn't sufficient to address this issue then it looks like the issue was present before #21238, is that correct?

What issue are you referring to?
