### ISSUE TITLE
Native loader tx instructions should be fully disabled

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#21347]
#### Problem
It's possible to invoke the native loader from a transaction and have it process instructions as if it were another native program (such as system program). This is harmless in practice but this edge causes lots of headaches when refactoring ix processing

#### Proposed change
1. Add test case for this type of ix to ensure we don't lose compatibility with the cluster
2. Add a feature switch to remove this functionality

**Comment by jstarry** [comment]
cc @jackcmay @Lichtso

**Comment by jackcmay** [comment]
Forbidding these should be feature gated and PR'd independently of #21348

**Comment by jackcmay** [comment]
@jstarry The feature `remove_native_loader` isn't sufficient to disable the native loader?  If not can you give a more specific example of the scenario you have in mind?

**Comment by Lichtso** [comment]
I believe this issue is independent of the `native_loader` instruction processing [here](https://github.com/solana-labs/solana/blob/ebea3297f969879b938add38bb34ed94a012e12d/program-runtime/src/instruction_processor.rs#L397),
but is related to the `native_loader::id()` being used as a terminal symbol in the chain of executable accounts [here](https://github.com/solana-labs/solana/blob/ebea3297f969879b938add38bb34ed94a012e12d/runtime/src/accounts.rs#L401).

The difference would be the one between the `program_id` and its `owner`:
https://github.com/solana-labs/solana/blob/ebea3297f969879b938add38bb34ed94a012e12d/program-runtime/src/instruction_processor.rs#L380

But I haven't tried deactivating the feature `remove_native_loader` and running this new test here:
https://github.com/Lichtso/solana/blob/a7abec638c28ee1f4b7aa3f92012efad129eadb5/runtime/src/bank.rs#L15396

**Comment by jstarry** [comment]
> @jstarry The feature `remove_native_loader` isn't sufficient to disable the native loader? If not can you give a more specific example of the scenario you have in mind?

Nope, not sufficient. As @Lichtso mentioned there is still a path. I already provided an example in the issue description here: https://github.com/solana-labs/solana/issues/21346
