### ISSUE TITLE
[Question] large account data copy performance

### ISSUE THREAD

**Issue by lyqingye** [solana-labs/solana#21429]
#### Problem
Before the transaction is executed, Solana will copy the account data associated with the transaction, and write the new account state after the transaction is executed successfully. In short, copy on write!

Therefore, my question is whether the performance will be seriously affected when an account is too large, such as the global Orderbook of Serum DEX. assuming that an Orderbook is 1MB in size and has the same Orderbook accessed by multiple transactions, it should be executed serially. each transaction needs to copy 1MB * 2 data, so the theoretical TPS (excluding the time of executing the program instruction) = Memory copy speed / 2MB

The reason why the Solana-Bench-TPS test results are very high is that Alice transfers token to Bob. Alice and Bob have different accounts, so they have no conflict and can be used in parallel

This is my understanding. I hope someone can give me an answer！ thanks

**Comment by sakridge** [comment]
Yes, write-access to a single account will be serialized. I believe each order-book is relative to a trading pair, so you can have multiple trading pairs in-flight at the same time. Of course you could have multiple DEXes order-books in-flight at the same time.

I believe only a small part of the order-book account state is changed by most transactions, so that could be optimized in a way to not require a copy of the full state for each transaction assuming the state was cached in memory already. The runtime could store a diff of the state instead. Of course this has different trade-offs.
