### ISSUE TITLE
Some vote account pubkeys and/or validator account pubkeys appear to have intrinsically worse performance than others

### ISSUE THREAD

**Issue by Marakaya** [solana-labs/solana#21450]
#### Problem

Initially, my key GtgtQLfqKjn3gaHuH7Fw64n49vr2DrYHiJAsSTNNscAE has been on the 9900K server since May of this year, later, when I discovered that my node votes worse than others, I moved to 5950s in the same data center (Hetzner), after looking at that the number of credits for my node did not increase, I canceled this server and moved to 3900 in the same data center, the number of credits for my node did not increase either. The last experiment was a key exchange with a friend who, every epoch, gains on average 7000-8000 credits more than me, he is located in another data center in Poland. This key is 4GuRZCrg6oChXATfMWTDJ9GNjjc4qKyxzow3UYjvhuqq. The exchange was in the 248 epoch. At least 5 people in our community faced a similar problem in the Solana RU-tech telegram. I will also ask them to describe their problem in this issue with they keys.

Key - GtgtQLfqKjn3gaHuH7Fw64n49vr2DrYHiJAsSTNNscAE with vote account 81iuTYDaeJ71XFGkPXNUuQ8gNvHQfBxpU7Vj2hzJ9Q4e
- epoch: 252 - **5950х**
  credits range: (13525377..13815912]
  credits/slots: 290535/432000
- epoch: 251 - **5950х**
  credits range: (13234764..13525377]
  credits/slots: 290613/432000
- epoch: 250 - **3900**
  credits range: (12946961..13234764]
  credits/slots: 287803/432000
- epoch: 249 - **3900**
  credits range: (12671194..12946961]
  credits/slots: 275767/432000
- epoch: 248 (------------------ the keys is changed -------------- ) - **3700х**
  credits range: (12395287..12671194]
  credits/slots: 275907/432000
- epoch: 247 - **3900**
  credits range: (12123462..12395287]
  credits/slots: 271825/432000
- epoch: 246 - **3900**
  credits range: (11833659..12123462]
  credits/slots: 289803/432000

Key 4GuRZCrg6oChXATfMWTDJ9GNjjc4qKyxzow3UYjvhuqq with vote account AQCqPa2bquEEGW1Z57XmgbfyCAqUgv9yHxSRnCDaU8oQ
- epoch: 252 - **3700х**
  credits range: (6864589..7161179]
  credits/slots: 296590/432000
- epoch: 251 - **3700х**
  credits range: (6566379..6864589]
  credits/slots: 298210/432000
- epoch: 250 - **3700х**
  credits range: (6271590..6566379]
  credits/slots: 294789/432000
- epoch: 249 - **3700х**
  credits range: (5988419..6271590]
  credits/slots: 283171/432000
- epoch: 248 (------------------ the keys is changed -------------- ) - **3900**
  credits range: (5703663..5988419]
  credits/slots: 284756/432000
- epoch: 247 - **3700х**
  credits range: (5423221..5703663]
  credits/slots: 280442/432000
- epoch: 246 - **3700х**
  credits range: (5128563..5423221]
  credits/slots: 294658/432000

Difference between keys in credits:
246 epoch 294658 - 289803 = 4855
247 epoch 280442 - 271825 = 8617
248 epoch 284756 - 275907 = 8849
249 epoch 283171 - 275767 = 7404
250 epoch 294789 - 287803 = 6986
251 epoch 298210 - 290613 = 7587
252 epoch 296590 - 290535 = 6055

#### Proposed Solution

I do not have the necessary competencies to solve this problem, but I know that in version 1.9 of solana the team found a solution to this problem (if I understood it correctly). If there is a solution, is it possible to speed up its implementation on the testnet?

**Comment by cattivik66** [comment]
I can confirm the problem reported.
I was running on testnet 3 different servers:
- Server A: 5950x overclocked with 128 GB RAM 3600MHz, 1 gbit connection in a datacenter in Italy, DDOS firewalls disabled, network card Intel x550-T2
- Server B: 5950x overclocked with 128 GB RAM 2333 Mhz, 10 gbit connection in a datacenter in Miami, DDOS firewalls disabled, network card Intel x550-T2
- Server C: 5900x with 128 GB RAM 2333 MHz, 10gbit connection in a datacenter in New York, DDOS firewalls disabled, network card Intel x550-T2

I made some investigations with two keys: AtkFWxD8dEkjSoNHBwMFMMv84WY2ore5XDWWjvLfBZ3q and 8mHseFfqx64WTUFEF2rqAFxwTxsM6bJsPJuHoMFguy2o.

Initially I thought for long time that the issues were something regardin firewalls, hardware or wrong configuration.
So I tried many times swapping the keys between all the servers and applying some changes.
The key 8mHseFfqx64WTUFEF2rqAFxwTxsM6bJsPJuHoMFguy2o was always overperforming the key AtkFWxD8dEkjSoNHBwMFMMv84WY2ore5XDWWjvLfBZ3q.

I was working on a server to try to get better results, and when I saw an improvement, I replaced the key I was using for troubleshooting (8mHseFfqx64WTUFEF2rqAFxwTxsM6bJsPJuHoMFguy2o) with the final key I wanted to use (AtkFWxD8dEkjSoNHBwM2o) with the final key I wanted to use (AtkFWxD8dEkjSoNHBwM2. Once the key was exchanged, I found that the votes dropped immediately and that the key used for troubleshooting (8mHseFfqx64WTUFEF2rqAFxwTxsM6bJsPJuHoMFguy2o) placed on the server where the other key was previously suddenly generated more credits.

Something strange can be seen also when comparing performance across different validators.
If we compare AtkFWxD8dEkjSoNHBwMFMMv84WY2ore5XDWWjvLfBZ3q on
https://metrics.stakeconomy.com/d/f2b2HcaGz/solana-community-validator-dashboard?orgId=1&var-pubkey=AtkFWxD8dEkjSoNHBwMFMMv84WY2ore5XDWWjvLfBZ3q&var-server=ts03-testnet&var-inter=1m&var-netif=All&from=now-24h&to=now&refresh=1m
with
2P3YH9psWAAM6QQgA8NaQnKHQ973cKNqTSFFCNYE4gjk
on
https://metrics.stakeconomy.com/d/f2b2HcaGz/solana-community-validator-dashboard?orgId=1&var-pubkey=2P3YH9psWAAM6QQgA8NaQnKHQ973cKNqTSFFCNYE4gjk&var-server=kobzoha-testnet&var-inter=1m&var-netif=All&from=now-6h&to=now&refresh=1m

you can see that, even if the second has a much worse server it generates 2% more credits.

In this epoch the key AtkFWxD8dEkjSoNHBwMFMMv84WY2ore5XDWWjvLfBZ3q  is at position around 2700.
You can compare it with 8JEabVuVHztGdX55zFYUssDCYH3gpdktWCHJsK7NReqb (https://metrics.stakeconomy.com/d/f2b2HcaGz/solana-community-validator-dashboard?orgId=1&var-pubkey=8JEabVuVHztGdX55zFYUssDCYH3gpdktWCHJsK7NReqb&var-server=triangle13&var-inter=1m&var-netif=All&from=now-24h&to=now&refresh=1m), that currently is at position 1:
it has very similar hardware, and very similar stats, but the key AtkFWxD8dEkjSoNHBwMFMMv84WY2ore5XDWWjvLfBZ3q  is generating 2.1% less credits than the second one.

You can see the difference in credits generation on this graph:
![solana_key_credits](https://user-images.githubusercontent.com/22317433/143720543-52b95148-8845-4103-a4a3-e175a5831635.jpg)
**Both server has CPU usage at around 42%, 128GB ram, IOWAIT around 0, both never rebooted during the current epoch, but if you sort all server by credits the difference between the two keys are around 2700 positions, a difference of ~4.2% votes.**

**Comment by mrduckss** [comment]
I also confirm this problem.
My key is 52gX6aMESU8visvPwFVZBCxrPSkA86fvV43KkLUK56xR.
For several eras I was on Hetzenre (nvme ssd / 128 / 3900X) By skip at 2300-2400 positions. Moved to Ikola in order to avoid concentration (nvme ssd / 64! / 3900X) no effect. 2300-2400 position. Now I moved to IONOS (nvme ssd / 128 / Epic 7302) - no effect. Credits in the same place. 
Everywhere the same configuration files, accounts in ramdisk, snapshots in ramdisk, operating system Ubuntu 20 and kernels are the same, the system is optimized according to the recommendations of doc.solana.com.
On the other hand, my wife has the key wegaXwEgNQ2CQVvZtLEPLVvGtV5gotwCxMGpGm4xshu. She also moved to all these servers (by transferring the keys) and her cretits, as they were originally in the range of 300-500, have remained. At the same time, for short periods of time, it falls into the top 100 in terms of credits.
This cannot be explained by chance factors. Geography of data centers Germany, France and the USA (two locations).

**Comment by bkapolicefund** [comment]
This is an incredible discovery that if it is true, which apparently it is hereby proven based on these posts, that some sort of voodoo curse is being put on these low performance keys by the great Solana tiki gods in the sky hovering over Solana Beach? come on folks, this is a seriously funny post. I been programming and playing star trek on mainframes since 1975 and i thought i heard all the IT jokers, but this one is hilarious. thanks for laughs. maybe the computer you was testing it with was getting vibrated wierdly by a pack of elephants stampeding in india that set of a tsunami that vibrated the undersea fiber cables worldwide cause it was in perfect resonance and that delayed the packet transmissions.

**Comment by cattivik66** [comment]
> This is an incredible discovery that if it is true, which apparently it is hereby proven based on these posts, that some sort of voodoo curse is being put on these low performance keys by the great Solana tiki gods in the sky hovering over Solana Beach? come on folks, this is a seriously funny post. I been programming and playing star trek on mainframes since 1975 and i thought i heard all the IT jokers, but this one is hilarious. thanks for laughs. maybe the computer you was testing it with was getting vibrated wierdly by a pack of elephants stampeding in india that set of a tsunami that vibrated the undersea fiber cables worldwide cause it was in perfect resonance and that delayed the packet transmissions.


This is a very "useful" post, thanks for your contribution. For the future please try to be more constructive.

**Comment by bkapolicefund** [comment]
sorry but i pretty much gave up on doing any constructive work for Solana a long time ago becuase of just this type of jabberwocky like this forum here and the posts in it as there is no "laboratory grade test bed" available to determine things like this are scientifically provable. In science, in order to perform a test, you need to have total control of the environment for a test to be conducted and prove ANYTHING. elsewise its all jabberwocky. So you need a lab with 100 PC's all running the exact same version and having the exact same log entries and having the exact same hardware and they must be started and run on same exact network. Then load a pc with the test key number 1 that is showing normal skip rate and run test for one day exactly. Then reset all 101 pc's same was as day before starting test and load test key number 2 that is showing high skip rate and run test one day exactly. Now if you cannot do the test like this then even wasting time jaberwokyin about it is just that - hot air to fill your balloon to fly in...
