### ISSUE TITLE
Error when running "solana-install update" on version 1.8.6

### ISSUE THREAD

**Issue by samih-harfouche** [solana-labs/solana#21697]
#### Problem
I installed Solana 1.8.6 and when I run solana --version I get Error: "Unknown release: 1.8.6" response

sam@Samihs-MacBook-Pro ~ % solana-install update
Error: "Unknown release: 1.8.6"
sam@Samihs-MacBook-Pro ~ % solana --version
solana-cli 1.8.6 (src:e5aa5efb; feat:591501692)

I installed the Solana Tool Suite as documented on Solana docs
[https://docs.solana.com/cli/install-solana-cli-tools](url)

I am using MacBook Pro Intel Core

**Comment by CriesofCarrots** [comment]
I am not sure why you are running `solana-install update`, but I believe what you are seeing is just because v1.8.6 is still tagged as a pre-release. `solana-install init v1.8.X` should work for those pre-releases, like v1.8.7 right now also.

That said, we don't use github for technical support. Please join us on Discord: https://solana.com/discord
