### ISSUE TITLE
Frozen-abi issue on first build

### ISSUE THREAD

**Issue by eoriont** [solana-labs/solana#22399]
#### Problem

I'm running windows 10.

I cloned the master branch of this repo, updated cargo and rustc with `rustup update`

I already had to install LLVM with `choco install LLVM`, besides the point.

When I run `cargo build`, it downloads a bunch of packages and compiles them, then gives this error:

```
error: expected item, found `..`
 --> frozen-abi\macro\build.rs:1:1
  |
1 | ../build.rs
  | ^^ expected item
```

It appears that `programs/stake/build.rs` only contains a file path, which I believe isn't valid rust code.
Is there a reason why this exists?

Cargo and rustc versions, in case they are relevant:
```
C:\Users\oriont\dev\solana>cargo --version
cargo 1.60.0-nightly (358e79fe5 2022-01-04)

C:\Users\oriont\dev\solana>rustc --version
rustc 1.60.0-nightly (a7e2e3396 2022-01-08)
```

**Comment by joncinque** [comment]
Hi there, we don't use GitHub for support, so please feel free to join #developer-suport at https://discord.gg/JJkWhPjb

To quickly answer, this is a bit tricky, but since Windows doesn't handle symlinks in the same way, you have to essentially recreate symlinks.  Check out how CI does it: https://github.com/solana-labs/solana/blob/master/ci/publish-tarball.sh#L55-L61
