### ISSUE TITLE
How official Solana binaries are built?

### ISSUE THREAD

**Issue by kucharskim** [solana-labs/solana#22749]
Can someone point me to the build scripts?

I'm asking about binary artifacts from asset section of https://github.com/solana-labs/solana/releases

I'm asking in context of `target-cpu` and `target-feature` or anything else, which could lead to SIGILL. Similarly to https://github.com/solana-labs/solana/issues/19669

**Comment by ruuda** [comment]
> I'm asking in context of `target-cpu` and `target-feature` or anything else, which could lead to SIGILL.

The reason we ask, is because we build `solana-validator` from source, and we observed it `SIGILL`.

I have one hypothesis for what causes this, but I haven’t verified it yet. Solana depends on [`reed-solomon-erasure`](https://github.com/rust-rse/reed-solomon-erasure) with `simd-accel` feature enabled. Due to a bug/feature in this crate, when `simd-accel` is enabled and when `RUSTFLAGS` is not set or does not contain a `-C target-cpu` flag, `reed-solomon-erasure` will compile a piece of C code with `-march=native`: https://github.com/rust-rse/reed-solomon-erasure/blob/v4.0.2/build.rs#L161-L181 This could cause the compiler to select instructions specific to the host that the binary is built on, outside of the intended simd instructions. This also relates to https://github.com/rust-rse/reed-solomon-erasure/pull/75.

**Comment by deni64k** [comment]
@ruuda Your guess is correct. I work around it this way.

Here is a stub executable for clang/gcc compilers:

```sh
#!/usr/bin/env bash
declare -a args=()
for arg in "$@"; do
  narg=$(echo -n "$arg" | sed -E "s,-m(arch|cpu|tune)=.+,-m\\1={WHATEVER_ARCH_YOU_WANT},")
  if test -z "$narg"; then
    narg="$arg"
  fi
  args+=("$narg")
done
exec "__EXE__.orig" "${args[@]}"
```

I install it in a Docker builder image this way:

```dockerfile
RUN for exe in /usr/bin/clang* /usr/bin/gcc* /usr/bin/g++*; do  \
      mv "$exe" "$exe.orig";                                    \
      cp /usr/local/bin/clang-stub "$exe";                      \
      sed -i -e "s,__EXE__,$exe,g" "$exe";                      \
      chmod +x "$exe";                                          \
    done

```

**Comment by kucharskim** [comment]
Do you have your build pipeline for binaries public somewhere? Where I can find above piece of code and Dockerfile? What is your default `{WHATEVER_ARCH_YOU_WANT}` for official Solana binaries?

**Comment by t-nelson** [comment]
It's [here](https://github.com/solana-labs/solana/blob/master/ci/publish-tarball.sh).  Specifically https://github.com/solana-labs/solana/blob/1b7bc8b284ba18a6c6603efcb9e905914f8a38dc/ci/publish-tarball.sh#L86-L90

**Comment by steveluscher** [comment]
We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Solana itself – so I'm going to close this.

If you learned something that's worth sharing with the broader community, please do post both your original question _and_ the answer you discovered to our new purpose-built Q&A forum: https://solana.stackexchange.com/questions/ask
