### ISSUE TITLE
Some testnet validators are increasing their credits by duplicating UDP packets

### ISSUE THREAD

**Issue by unordered-set** [solana-labs/solana#22809]
#### Problem
Not everyone is playing fair in the testnet. I've identified some validators who are sending more voting UDP packets than others. https://teletype.in/@xni/h1Z5JBrVuEb

I don't think it is anyhow an improvement of a system, network oк software. It is done with the only purpose to move faster towards mainnet.

#### Proposed Solution
1) Implement anti-spam filter in solana. At the level of deduplication for voting create a black list. If some packet is seeing twice - block all of the senders who sent it.
2) Implement some other type of queue for mainnet. "Just be not in the lowest 20% by credits", for example. Because the race to get more credits created this unhealthy competition.
3) i think there is no need in doing retries actually, so including similar behavior to the source code of original solana does not make sense

**Comment by im-0** [comment]
> BTW, 3413 (9v7E6oEm1V86hjTubtBon7cRYPvQriWZKHZEX6j92Po4) and 3414 looks like belonging to the same person.

Originally, I noticed that some Mainnet validators are unreachable from Russia. This happens either because of Roskomnadzor's blocklists, or because of weird firewall configuration on those validator's side ("block all packets from Russia for whatever reason"). I configured my Mainnet server to send packets to such validators via VPN on another server. I partially replicated the same mechanism on my Testnet validator just to ensure that it actually works and does not cause any trouble.

Sending packets from another server probably makes no sense if you are running outside of Russia already.

> Implement anti-spam filter in solana. At the level of deduplication for voting create a black list. If some packet is seeing twice - block all of the senders who sent it.

All packets are public, vote transactions are additionally duplicated via Gossip. Anyone can resend anyone else's packets, so this will lead to a serious vulnerability.

> Implement some other type of queue for mainnet. "Just be not in the lowest 20% by credits", for example. Because the race to get more credits created this unhealthy competition.

Competition for vote credits also happens on Mainnet, by the way.

> i think there is no need in doing retries actually, so including similar behavior to the source code of original solana does not make sense

Transaction retries are a part of Solana's design considerations. There is no mempool, and UDP is unreliable. The only way to reliably transact is to retry.

**Comment by unordered-set** [comment]
Thanks for your comments @im-0 ! 
That's interesting what you said. On the other hand, having 3000 votes sent from a single IP comparing to 6000 sent by others is something we should deal with, I think. Generally, the redistributed UDP traffic will increase overall bandwidth consumption, but what we get as a rewards? Higher credits for people, but nothing for the network

**Comment by im-0** [comment]
> On the other hand, having 3000 votes sent from a single IP comparing to 6000 sent by others is something we should deal with, I think.

What exactly you mean here? You see 3000 voting packets from one source IP while 6000 combined from all other source IPs within the same period of time? Are you sure that you are not confusing voting transactions with other traffic from the same IP (gossip, turbine).

**Comment by im-0** [comment]
> Higher credits for people, but nothing for the network

Voting is incentivized exactly because it helps the network: it is how the network confirms valid blocks. There is a corner case when validators vote for already confirmed blocks. Such "delayed" votes are not good for the network, but packet duplication has nothing to do with it.

**Comment by unordered-set** [comment]
> > On the other hand, having 3000 votes sent from a single IP comparing to 6000 sent by others is something we should deal with, I think.
> 
> What exactly you mean here? You see 3000 voting packets from one source IP while 6000 combined from all other source IPs within the same period of time? Are you sure that you are not confusing voting transactions with other traffic from the same IP (gossip, turbine)?

Yes, exactly. In a timeframe of 30 seconds I saw about 6000 packets from others (3500 validators * 2 packets per second) and 3000 from a single IP alone.

I had 'dst port 8005' filter, which, I may be wrong, uniquely identifies the intention to send a vote processing instruction. I can double check the contents of the packets as well.

I do understand the purpose of voting. I just wanted to say that the protocol needs 80% confirmations. UDP losses are (i dunno to be honest, but looks like <10%). So the protocol is not loosing anything from loosing your particular vote. But if everyone will start tee-ing packets, individual loss will become, say, 1%, but amount of traffic and also amount of CPU resources to handle it, will double.

So, thinking about the above, i found it reasonable to have a "dynamic firewall" to allow votes for account only from the associated ip in gossip (to prevent fan-out -> fan-in scenario) and a filter with a reasonable threshold, consistent with the constants of built-in resend parameters

**Comment by im-0** [comment]
> I had 'dst port 8005' filter, which, I may be wrong, uniquely identifies the intention to send a vote processing instruction. I can double check the contents of the packets as well.

Do you have the pcap file? Could you share it here please?

> I do understand the purpose of voting. I just wanted to say that the protocol needs 80% confirmations. UDP losses are (i dunno to be honest, but looks like <10%). So the protocol is not loosing anything from loosing your particular vote. But if everyone will start tee-ing packets, individual loss will become, say, 1%, but amount of traffic and also amount of CPU resources to handle it, will double.

Have you seen my rough calculations in discord?

```
there are ~3500 validators in Testnet right now
each sends ~3 vote transactions/packets per second: 10.5k packets per second
if each sends 10x more duplicates, it would be 105k packets per second
currently, i see ~300 kpackets/s incoming and ~600 kpackets/s outgoing on my testnet validator
will definitely be visible, but not that huge difference
```

It won't double even if everyone will send ten times more vote packets.

> So, thinking about the above, i found it reasonable to have a "dynamic firewall" to allow votes for account only from the associated ip in gossip (to prevent fan-out -> fan-in scenario) and a filter with a reasonable threshold, consistent with the constants of built-in resend parameters

Do you have any specific ideas of how to implement this safely?

**Comment by michaelh-laine** [comment]
Excellent research but the conclusion to block such IPs is jumping the gun I think. As im-0 mentions there are various ways in which this could be misused or just lead to bad results, it also goes against the idea of censorship resistance. Resending votes and retransmission happen automatically already, though not on the TPU Vote port, rather via Gossip. It's a tricky situation, sending one vote 50 times seems abusive, sending it 3 times might be fine.

Sending multiple votes in a single transaction is actually something the Solana code does automatically quite regularly so that isn't a red flag in itself.

Still, quite enjoyed reading your breakdown of how you researched it
