### ISSUE TITLE
Optimistic voting optimization to even out block execution

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#22922]
#### Problem

The chain can experience short periods of high transaction volume where some validators may not be able to keep up with the transaction execution and thus their votes are stalled behind the replay operations. This stalls the consensus and could prevent the chain from chain making roots and from letting users know transactions are accepted.

#### Proposed Solution

Nodes could do some simpler checks on a block and vote before having fully integrated the state of the block.

Some potential pitfalls:
* Sustained periods of high throughput might puts nodes so far behind they may never catch up or catch up after an unreasonable amount of time. This could be mitigated by feedback mechanism on compute cost per block limits once this situation is detected.
* Possible to vote on block which maybe wasn't the optimal choice?
* Where to get the hash? Other votes for the block? Remove it entirely from the vote except every <N> blocks?
* Can tell if block broke compute limits? Will assume worst-case scenario? What if worst-case is close to the limit and run-time doesn't actually break the limit, how to tell?

Checks do to on the block before voting?:
* Everything deserializes and transaction sizes are ok
* PoH
* Sigverify
* Transactions can pay fees? what if a transaction uses a fee-payer which is written previously in the block?

**Comment by sakridge** [comment]
cc @pgarg66 @carllin @aeyakovenko

**Comment by carllin** [comment]
An accurate measure of the compute without execution seems to be one of the biggest risks. One miscalculation and we could be spinning forever on some of these blocks. Would try to nail down our cost model/feeds/gas estimation before even attempting this

**Comment by bji** [comment]
All we need is my proposed "vote timeliness" change, then validators who run hardware insufficient to keep up with the fastest validators will tend to lag in vote submission and will receive fewer credits as a result.  This provides incentive where incentive should be: on validators using hardware and network sufficient to keep up with the cluster.

Validators which run "too fast" and submit too many transactions in their block will likely be skipped by subsequent leaders.  This is their incentive to reduce speed to come closer to what the network supports.

I think that adding more ways for the cluster to try to race ahead of its actual capacity will just make it more brittle.

Validators should probably have mechanisms for making a "best guess" about the best size of the blocks they create during their leader slots:
- Compute a trailing avg of compute units in prior slots along with their success rate.  Target inclusion of compute units in block sufficient to expect high success rate (i.e. do not put more compute units into a block than has previously achieved confirmation within N slots)
- If cluster is in a really bad state -- i.e. no confirmations on prior N slots, then start reducing target compute units.  Could ramp down quickly and eventually get to a "votes only" mode once the number of target compute units falls below some threshold.
-

**Comment by bji** [comment]
Additionally, transactions should declare their total compute unit budget and should pay transaction fees commensurate with that.  If they use fewer than the total budgeted compute units they paid for, they still pay full fees.  If they would go over their compute budget, their transaction fails and they still pay the fees.

This would:

a) cause transactions to pay for actual compute units used, which gives incentive to transaction efficiency, and also pays the network according to actual resources used, and
b) give incentive to transaction submitters to provide accurate assessments of the compute units their transactions will use, in order to pay the lowest transaction fee possible without failing due to being over paid-for compute budget

If transactions were costed this way, then transaction submitters would be incentivized to give accurate information about the compute unit cost of their transactions, which would allow validators using the "trailing avg of compute units" method to ensure that their block achieves timely consensus to do so more reliably.

(note that compute units should probably be costed in a non-linear fashion; as a simple example, each subsequent instruction turns into an "instruction compute unit cost" that is then multiplied by a cost factor; that cost factor rises with each subsequent instruction, say by .01%.  This would mean that larger compute unit transactions pay more than a sequence of smaller transactions, when then gives incentive to splitting large transactions up into multiple smaller transactions, thus reducing the overall latency of small simple transactions and increasing the overall latency of large transactions.  Essentially transactions pay for how many other transactions they delay.)

**Comment by j-h-a** [comment]
It's in a leaders interest to ensure their block is voted, so fast leaders who are capable of producing blocks that are too big for slower validators to keep up with should self-moderate on what they put into a block. They could do this to the point where they are confident that consensus can still be reached on their block (within whatever margin of error they decide they are comfortable with). Yes this means the bar is raised for validators, but doesn't this mean they are simply incentivised to improve their hardware and connectivity, and isn't that good for the network?

**Comment by sakridge** [comment]
Isolated vote state idea from @aeyakovenko:

* Isolate votes such that vote instructions that read other programs are invalid
* System instruction to move state in/out of Vote isolation
* Evaluate votes and vote on an isolated vote “bankhash”
* Asynchronous evaluate all other program state and include it in vote isolation state asynchronously
