### ISSUE TITLE
Separate vectors for account_keys and program_ids wastes space in transactions

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#2294]
#### Problem

Both `Transaction` members `account_keys` and `program_ids` are referenced by index but stored in two separate vectors.  Combining the two into one vector would save 8 bytes (one byte after #1801 is resolved).

#### Proposed Solution

Combine the two vectors into one.  Program accounts would be added to `account_keys` after the signed accounts.

**Comment by garious** [comment]
Now that #1801 is resolved, this only saves a byte. I took a stab at it here. It's probably close to done, but it broke a bunch of tests in core. It might just be because the System program is `Pubkey::default()` and that we should change those to `Pubkey::new_rand()`.

https://github.com/garious/solana/commit/3da2b93add6fa21e0bcccef5af9df15e7edc27f4

**Comment by mvines** [comment]
It would be nice to do this after #3693 to avoid having to duplicate the Transaction format changes in the JS SDK

**Comment by mvines** [comment]
This is already fixed, we now have only signed and unsigned keys
