### ISSUE TITLE
QoS Service Over Estimates Compute Units

### ISSUE THREAD

**Issue by buffalu** [solana-labs/solana#23030]
#### Problem
The QoS Service selects + updates the cost model before building a batch, resulting in an overestimate of compute units: https://github.com/solana-labs/solana/blob/f67a27eee/core/src/banking_stage.rs#L1119

discord:
https://discord.com/channels/428295358100013066/754723351389536348/940847277134729266

#### Proposed Solution
- make cost model + compute units accurate.
- can take into account the batch that's actually built + executed.
- probably want to take an iterative approach to cost model while building the batch? maybe you want to run qos while executing the tx?

cc @jstarry

**Comment by taozhu-chicago** [comment]
Thanks for opening the issue. 

Since qos estimates transaction's CUs when packing them into block, it happens before transaction execution, so it;s likely not exact. With that said, we want to make the estimation as close as possible as so not to waste block space. There are metrics put in to [measure estimated CUs](https://github.com/solana-labs/solana/blob/f67a27eee/core/src/banking_stage.rs#L1123-L1128) and [Actual executed CUs](https://github.com/solana-labs/solana/blob/f67a27eee/core/src/banking_stage.rs#L1167). They indeed indicate that cost model is over estimation instruction cost. #22286 is to improve estimation calculation.

**Comment by ckamm** [comment]
This looks like a significant issue to me. Nearly all recent blocks hit the cost_tracker.block_cost limit and have accounts that hit the per-account cost limits. At the same time cost_tracker.transaction_count is usually 1.5x-3x bigger than the actual tx count in the block.

This suggests that blocks would be packed with more transactions if this problem was resolved. I'll start looking at it.

**Comment by ckamm** [comment]
To prove my point, I hacked benches/banking_stage.rs to just do one full pass through the test transactions and then write out the cost tracker stats.

For the default TransactionType::Accounts case I get
```
datapoint: 
cost_tracker_stats bank_slot=0i 
block_cost=1236910080i 
vote_cost=0i 
transaction_count=6144i 
number_of_accounts=12288i 
costliest_account="5G1okYjewBBRE4xveYzRCfihkBAFr98hQka1GxsDEGgg" 
costliest_account_cost=201320i 
account_data_size=0i
```
but if I change `make_account_txs()` to make them all transfer to the same target account (and remove the can-execute-in-parallel sanity check):
```
datapoint: 
cost_tracker_stats bank_slot=0i 
block_cost=292514134920i 
vote_cost=0i 
transaction_count=1452981i 
number_of_accounts=6145i 
costliest_account="DM2Rc1fCguHAK2jZ8ykE5vByK4CZQR32UWwdFydy4tYr" 
costliest_account_cost=292514134920i 
account_data_size=0i
```
In this fully single threaded case, the cost_tracker numbers just explode.

**Comment by ckamm** [comment]
For the real implications, look at block 128593968. The cost_tracker_stats say:
```
"cost_tracker_stats.bank_slot","cost_tracker_stats.block_cost","cost_tracker_stats.transaction_count"
"128593968","47999360","666"
```
but the true block has 235 transactions only. 197 are votes and 38 are others. Summing up the compute reported by log messages for the 38 tx gives me 5098643 CU. The 200 votes should be less than a million CU. 

I think that block was small because of this bug.

**Comment by taozhu-chicago** [comment]
Ah, good finding! This is a bug that contributes to low block density. Thanks for looking into it. Will comment solutions on PR
