### ISSUE TITLE
f64::powi() doesn't work properly on-chain with negative exponent

### ISSUE THREAD

**Issue by askibin** [solana-labs/solana#23588]
#### Problem
This works as intended:
```
msg!("{}", f64::powi(10f64, -1)); // prints 0.1
```

This also works:
```
let n = 1;
msg!("{}", f64::powi(10f64, -n)); // prints 0.1
```

But when exponent is not a literal but a dynamic value known at run-time, then it breaks:
```
for i in 1..20 {
  msg!("{}", f64::powi(10f64, -i)); // prints inf
}
```

or:
```
let n = instruction_data[0] as i32; // assuming instruction_data[0] > 0
msg!("{}", f64::powi(10f64, -n)); // prints inf
```

All examples work properly on the client at the same time.

#### Proposed Solution
Fix or document as unsupported

**Comment by brson** [comment]
The problem appears to be in the compiler's lowering of intrinsics, and cases that appear to work do so because constant folding removes the pow operation.

When the compiler lowers `intrinsics::powif64` intrinsic to a call to the C-ABI  `__powidf2` function it clears the top half of the 32-bit exponent argument by doing a logical left shift by 32 bits then a logical right shift by 32-bits; when the compiler normally calls a C-ABI function with the same signature it instead does the same logical left shift, but follows it with an _arithmetic_ right shift, leaving the high word all 1s. `__powidf2` assumes it can count on the sign extension, uses 64-bit math, and produces an incorrect result.

This also happens for the 32-bit pow intrinsic.

The bug is probably in the llvm bpf backend - its intrinsic translation needs to change such that when it clears the high word of a signed type prior to calling a builtin it uses arithmetic right shift instead of logical right shift.

**Comment by brson** [comment]
Changing the BPF target to override TargetLowering::shouldSignExtendTypeInLibCall might fix it.

**Comment by dovahcrow** [comment]
Stepped into this bug today and spent several hours to debug. Maybe just add a deprecate warning to the `powi` function if fixing it can take longer.

**Comment by dmakarov** [comment]
This is issue will be resolved with the next release of sbf-tools.  https://github.com/solana-labs/llvm-project/pull/52
