### ISSUE TITLE
test_replay is ignored and bitrotting

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#2358]
#### Problem
test_replay() is ignored, but appears to be the only "unit" test for the data plane

#### Proposed Solution
ensure there are actual unit tests for each of the sub-units of test_replay, retire test_replay, and restructure to test the glue in this file

**Comment by sagar-solana** [comment]
This test is hardly "testing" anything. 
It's got two parts. 

- One that simulates bank ticks and entries and makes sure the bank is processing a single transfer of balance (pointless since bank has unit tests) 

- Second that tries to send entries to "validator" for replay. It doesn't perform any assertions on whether or not anything was actually received or if replay worked correctly. 

Finally, after fixing the bank transactions (process_tick instead of process_entry being called) the test freezes because storage_stage is stuck trying to get last_id from a bogus leader node.

**Comment by garious** [comment]
Find out who wrote and consider deleting it?

**Comment by sagar-solana** [comment]
@garious will do.
