### ISSUE TITLE
Measure performance of dropping packets from banking_stage packet_batch buffer by fee priority

### ISSUE THREAD

**Issue by taozhu-chicago** [solana-labs/solana#24006]
#### Problem

#23841 implements a logic to drop low priority packets first when banking_stage `PacketBatch` buffer is full. It calls to scan the entire buffer to index individual packets by priority, then low priority packets until an empty batch is found. This op happens everytime adding new `PacketBatch` to buffer when it has reached capacity.

Compare to previous indiscriminately FIFO operation, this implementation adds overhead cost. It would be good to know how much it adds.

#### Proposed Solution
Add a benching test, or enhance existing one, to test above scenario. 

`banking_stage` buffer capacity is determined [here](https://github.com/solana-labs/solana/blob/master/core/src/banking_stage.rs#L421-L422). With default setting, it is `~2000` batches per buffer, where each batch has 128 packets. 

So the test should: 
1. prepare batches of 128 `transfer` transactions, with different fee/CU
2. send `2000 * 2` such batches to banking_stage to saturate 2 non-vote buffers.
3. start timer
4. send another 500 batches to trigger 500 times testing operations
5. stop time. 

Compare the time spent before and after PR #23841 should give us a sense of the overhead, from there we can optimize it.

**Comment by taozhu-chicago** [comment]
also be interesting to see the result with different fee/cu distribution amount packets.

**Comment by nikhayes** [comment]
Do y'all also have a performance test more similar to mainnetbeta activity spikes (IDOs or NFT drops)? Something where you spam a certain amount of non-contentious transfers along with increasing amounts of higher compute contentious transactions? I feel like that might result in much different behavior that could be worth observing.

**Comment by taozhu-chicago** [comment]
@carllin suggested another approach of indexing packets by priority at https://github.com/solana-labs/solana/pull/23841#discussion_r839116939, worth evaluate together.

**Comment by carllin** [comment]
I've added a bench here: https://github.com/carllin/solana/blob/0e49bccd91f3b8ea5eb8ff9256a7863a02c3c612/core/benches/banking_stage.rs#L406-L486 for the current packet dropping behavior in https://github.com/solana-labs/solana/pull/23841

`bench_unprocessed_packet_batches_insert_beyond_limit` inserts `10,000` `PacketBatch`'s with a max buffer of `5000`, and takes `10000` ms to run

 `bench_unprocessed_packet_batches_under_limit` inserts inserts `10,000` `PacketBatch`'s with a max buffer of `10,000`, and takes `20` ms to run

This seems to imply the current behavior for dropping packets by priority will be too slow to handle sudden high traffic loads

**Comment by nikhayes** [comment]
Not sure how difficult it is to add, but with the new transaction processing changes (by stake weight and fee), if after the priority-weighting you sort transactions into different groups based on instruction number (or perhaps compute), and threads deal with transactions of certain instruction ranges, I think you can bypass a lot of the major issues caused by a contentious group of transactions saturating all batches and threads (and leading to mostly serial processing on one thread). It's obviously a bit of a janky short term upgrade, but you'd basically have a thread that gets all transactions with 1 to 2 instructions (transfers, pyth, etc), another with 3 to 5 or so, etc etc. and at the end you would have the last thread that receives batches containing the bulk of Raydium IDO transactions, which have a high number of instructions. I'm not sure if any of the current bench tests would be suitable to see if this would help though.

Anyway, apologies for the armchair commentary, I would definitely help test/write stuff if I could -- I'm a bio grad student and only have some python background atm though.
