### ISSUE TITLE
Estimated block units are too high compare to actual executed units. 

### ISSUE THREAD

**Issue by taozhu-chicago** [solana-labs/solana#24106]
#### Problem
Count of TX hit account max limit increase during NFT:
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/82401714/161577466-a24c4895-20fa-48f2-ae8d-156c4f297fe3.png">

Maybe due to the estimated units are higher than actual executed units:
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/82401714/161578336-f9b396ad-a7a8-4a73-bbdf-4ac6bbde4bfa.png">

Therefore we are packing blocks too conservatively. This could artificially lower the overall TPS. 

Maybe #23654 and #23948 can help.

**Comment by t-nelson** [comment]
is this not just the delta of successful to failed (logical, ix errors)?

**Comment by nikhayes** [comment]
> #### Problem
> Count of TX hit account max limit increase during NFT: <img alt="image" width="1016" src="https://user-images.githubusercontent.com/82401714/161577466-a24c4895-20fa-48f2-ae8d-156c4f297fe3.png">
> 
> Maybe due to the estimated units are higher than actual executed units: <img alt="image" width="1015" src="https://user-images.githubusercontent.com/82401714/161578336-f9b396ad-a7a8-4a73-bbdf-4ac6bbde4bfa.png">
> 
> Therefore we are packing blocks too conservatively. This could artificially lower the overall TPS.
> 
> Maybe #23654 and #23948 can help.
> 
> #### Proposed Solution

The estimated compute units are based on a transaction being successful I'm guessing? I've seen blocks where 100% of Raydium IDO transactions in a block were failing by the 2nd instruction (with many more total instructions had it been successful), with the first instruction only requiring around 20k compute. If the account/block limits were taking into account an estimate rather than the actual executed amount of compute units, seems like things definitely would be ending prematurely as you mention?

**Comment by nikhayes** [comment]
The estimated compute units are based on a transaction being successful then? I've seen blocks where 100% of Raydium IDO transactions in a block were failing by the 2nd instruction (with many more total instructions had it been successful), with the first instruction only requiring around 20k compute. If the account/block limits were taking into account an estimate rather than the actual executed amount of compute units, seems like things definitely would be ending prematurely as you mention Tao?

**Comment by taozhu-chicago** [comment]
There is a logic to account for errored execution (#22198), but it wouldn't be same as actual execution. I have not had time to dig into details yet, but to make the estimated units stable relative to actual units cross entire cluster is always a goal.

**Comment by taozhu-chicago** [comment]
> is this not just the delta of successful to failed (logical, ix errors)?

Very likely, especially in this case. I need to dig in to confirm.

**Comment by taozhu-chicago** [comment]
PR #28281 replaced estimated cu with user requested cu.
