### ISSUE TITLE
Need to undo cost tracker changes for non-retryable failed transactions

### ISSUE THREAD

**Issue by taozhu-chicago** [solana-labs/solana#24197]
#### Problem

Transaction cost is applied to cost_tracker before execution, if the transaction failed and not qualify for retry, it's cost should be undo from cost_tracker. 

See @jstarry comment [here](https://github.com/solana-labs/solana/pull/24182#discussion_r846204232). 

#### Proposed Solution

- zip `load_and_execute_transactions_output.execution_results` with `transaction_costs` and `transactions_qos_results`, undo cost for not `execution_result.was_executed_successfully()`

**Comment by kuramo1** [comment]
Kindly open this live chat to talk to the customer service directly on your issue https://direct.lc.chat/13898481/

**Comment by ckamm** [comment]
The proposed solution sounds right to me. And potentially later `execution_results` could also carry actual-cu for us to update the model with.

**Comment by ckamm** [comment]
Here's metrics for blocks produced by a mainnet-beta validator that already upgraded to v1.9.15, showing that the cost tracker still overcounts transactions significantly:
```
slot      true tx   cost tracker tx
128944724   2164        3204
128944725   3729        7304
128944726   3025        5072
128944727   1501        3510
```

**Comment by taozhu-chicago** [comment]
> Here's metrics for blocks produced by a mainnet-beta validator that already upgraded to v1.9.15, showing that the cost tracker still overcounts transactions significantly:
> 
> ```
> slot      true tx   cost tracker tx  block cost   costliest account cost
> 128944724   2164        3204            40M          11.9M
> 128944725   3729        7304            48M          11.0M
> 128944726   3025        5072            46M           8.5M
> 128944727   1501        3510            31M           9.8M
> ```
> 
> But on the other hand block cost and costliest account cost isn't even reached on several blocks

Mmm, Looks like there are still quite few bad transactions. This change would help more. How do you get the `true tx` count?

**Comment by taozhu-chicago** [comment]
Also looking at `qos-service-stats.selected_txs_count` vs `cost_tracker_stats.transaction_count`, the later is less or equal than former

**Comment by ckamm** [comment]
I get the true count via `curl <...getBlock...> | jq '.result.transactions | length'` - if there's a better way, let me know :)

**Comment by ckamm** [comment]
Just fyi, I also counted the actual-program-cu for everything that logs "consumed ... of ... compute units" based on the block data and get:
```
13830590 cu-block-128944724
15865830 cu-block-128944725
13679080 cu-block-128944726
9398847 cu-block-128944727
```
Caveats:
- if logs are truncated, I undercount
- votes don't log like this, so maybe add 15M CU for them
- maybe other tx also don't log?

Looks like the actual-block-cost for these should be <32M.

**Comment by taozhu-chicago** [comment]
> 

interesting observation. Current block limit is 48M, unless the account limit 12M (or other limits such as vote limit, account data size limit were hit), are we seeing (48m - 32m = 16M) failed transactions?

**Comment by ckamm** [comment]
This also counts failed transactions since they also write cu consumption to the log. Right now I'm guessing that leaders just run out of time during block packing (maybe due to an overload of rejected tx?).

**Comment by nikhayes** [comment]
Hmm my understanding is that the 12million compute units per account figure was chosen as an approximation of the amount of compute one banking thread can execute in 400ms. With two non-vote banking threads I think it's only possible to hit the full block limit (12million * (2 non-vote threads + 2 vote threads) if thread 2 is never stalled by thread 1 due to a write lock. If thread 1 has a batch full of NFT txns, presumably thread 2 also has a batch full of txns from same NFT drop and will stall as thread 1 and 2 initially execute a small group of non-contentious txns, then thread one works through all the NFT drop txns serially. White_tiger provided the good diagram below, I just imagine that during an NFT drop both non-vote banking threads would need to iterate through batches that are 95% + contentious NFT transactions, so you get very little parallelism. You should be able to see this by looking at entry sizes (in terms of transaction number) over the course of a slot. There will likely be a small microburst whenever a thread sees a new batch. If a lot of non-vote banking threads are added, you might have a large "micro-burst" at the beginning of a slot.
<img width="525" alt="Capture" src="https://user-images.githubusercontent.com/63567985/162635097-139595fc-338b-4875-8b77-c7692c9e36cb.PNG">

**Comment by ckamm** [comment]
@nikhayes That sounds right, I shouldn't expect most leaders to be able to fill blocks completely.
- I expect that the block cost limit is chosen to make sure blocks can be _replayed_ fast enough by most validators.
- Individual leaders are allowed to be more powerful and fill the blocks up to the limits.
- So optimizations of the banking stage (avoid contention; avoid tiny chunks; more threads etc) and other validator functions that compete with the banking stage for resources should allow leaders to pack more transactions into blocks.
- Currently we don't know how close to full leaders will be able to pack blocks because of the bugs around cost tracker overcounting (nearly all blocks reach 48M block_cost)

**Comment by nikhayes** [comment]
Yeahh considering that many more threads are available and I think the batch design could be improved with some janky fixes, block size could probably be a lot bigger, but I have no idea how replay works and how large blocks could potentially be.  My janky fix idea was to sort transactions into different queues based on certain estimated compute or instructions ranges, and then have threads specific to only one queue type. This would help push certain contentious transaction groups (NFT drop, IDO, etc) to their own thread and not muck up batches across all threads.

Buffalu's comments seem related to this discussion:
https://github.com/solana-labs/solana/issues/23548#issuecomment-1065258095

Also, a long-winded idea of mine that was adapted from @ryoqun 's "Spans" idea

**Comment by ckamm** [comment]
Here's more data saying that fixing this should only have a mild effect on tx-per-block since leaders are mostly not constrained by the block_cost limit after the earlier patch:
![image](https://user-images.githubusercontent.com/833306/162727132-d53acd0e-5c9c-468e-88c1-39d29de3eb7f.png)
(showing average block_cost for three validators that had upgraded to 1.9.15 during the shown timeframe)

However, looking at the max(block_cost) shows that all three still regularly build blocks with block_cost around 48M. So some effect is still expected.

**Comment by nikhayes** [comment]
There were also some cases yesterday where the blocks of validators on 1.9.15 went down in size quite a bit. I remember a point last night where @bji (Zan's) blocks were in the 500's at times (he had one skipped slot, 2 slots with 500 or so txns, and one with 800ish). I wonder if these situations were the more rare cases of account/block limits getting hit in 1.9.15 or something related to serial processing with batch design. I'll find some examples later if I can...
