### ISSUE TITLE
Need help with .config file 

### ISSUE THREAD

**Issue by andb222** [solana-labs/solana#24220]
Hi, i want to reinstall solana, because of this error

"Unable to load C:\\Users\\username\\.config\\solana\\install\\config.yml" 

i deleted the .config file on the documents, and i can't update or do anything with solana, 

 
anyway to get the file back, or how can i delete solana ?

thanks

**Comment by kuramo01** [comment]
Kindly open this live chat to talk to the customer service directly on your issue https://direct.lc.chat/13898481/

**Comment by willhickey** [comment]
Here's the config.yml file from a fresh install of 1.9.15. Updating version number and USER might produce a valid config on your system. If that doesn't work try deleting the active_release directory and reinstalling.

The 1.10 installer for Windows is currently missing but v1.19.15 works. v1.10 should be fixed in the next release.

```
---
json_rpc_url: "http://api.devnet.solana.com"
update_manifest_pubkey:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
current_update_manifest: ~
update_poll_secs: 3600
explicit_release:
  Semver: 1.9.15
releases_dir: "C:\\Users\\USER\\.local\\share\\solana\\install\\releases"
active_release_dir: "C:\\Users\\USER\\.local\\share\\solana\\install\\active_release"

```
