### ISSUE TITLE
`solana-ledger-tool bounds` Doesn't Respect `--output` flag.

### ISSUE THREAD

**Issue by ProfMoo** [solana-labs/solana#24756]
#### Problem

When using the `solana-ledger-tool`, the only possible output is plaintext. Example:

```bash
> solana-ledger-tool --ledger <my_ledger_dir> bounds
Ledger has data for 2157 slots 131574183 to 131576507
with 1767 rooted slots from 131574183 to 131576250
and 211 slots past the last root
```

This is fine for human readers, but difficult for machine users.

#### Proposed Solution

It'd be great for machine users if the command would respect the `--output json` flag that is already used for the `solana-ledger-tool bigtable` sub-command.

```bash
> solana-ledger-tool --ledger <my_ledger_dir> bounds --output json
{
  "totalSlots": {
    "start": "131574183"
    "end": "131576507"
  },
  "rootedSlots": {
    "start": "131574183"
    "end": "131576250"
  } 
}
```

**Comment by lhendre** [comment]
Is this task still open/out for grabs? Looking at picking it up

**Comment by CriesofCarrots** [comment]
@lhendre , yep, as far as I know, no one is working on this yet. Please feel free to go for it :)

**Comment by lhendre** [comment]
@CriesofCarrots  working on this now, quick question/ suggestion.  Im working for this on the bounds but there are a lot of different arguments and possible outputs. It maybe good to break this up into seperate smaller prs/tasks since each one will be different and it will avoid a large PR, would also open this to others if they want to join easierly.

Having some build issues but thats seperate, once that is done have some code to trial out and test

**Comment by gnapoli23** [comment]
@CriesofCarrots Hi, don't know if you saw the pull request for this issue, but i proposed a solution as you can see in #28410. Any kind of update? Thanks :)
