### ISSUE TITLE
Write highest optimistic slot to durable storage

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#24872]
#### Problem

When restarting a cluster it's important to have the correct optimistic confirmed slot, we have a metric but not all nodes report metrics and the log but not all nodes record logs or have the log level set to capture the optimistic slot message.

#### Proposed Solution

Write the highest confirmed slot to rocksdb. And maybe it should be the highest non-vote-only slot which is optimistically confirmed.

**Comment by sakridge** [comment]
@jdavis103 can you take a look?

**Comment by jdavis103** [comment]
Hi Stephen, it looks like this may already have been addressed by https://github.com/solana-labs/solana/pull/25362

**Comment by jbiseda** [comment]
stores optimistic slot in blockstore and adds ledger tool option to display data:
preserve optimistic_slot in blockstore #25311

**Comment by steviez** [comment]
I see this issue was about to get claimed by stale bot. Just confirming that jbiseda is correct about optimistic slots getting stored in in blockstore. Additionally, we added support to `ledger-tool` to find the highest non-vote-only slot in https://github.com/solana-labs/solana/pull/30580 so explicitly closing to confirm that these things are done
