### ISSUE TITLE
Investigate turbine votes vs. gossip votes landing

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#24887]
#### Problem

There seem to be more gossip votes landing than turbine, although from the current metrics it's hard to tell. We would like to find how many of each is successful and from what nodes. Hopefully we can compare the latency and success of each and try to increase the success of turbine votes.

#### Proposed Solution

Investigate with metrics which may lead to solutions on how to improve the vote success rate via turbine.

**Comment by nikhayes** [comment]
There should be a much lower compute limit for vote accounts I think. No reason for it to be 12mil.

**Comment by t-nelson** [comment]
> I believe this is telling us that turbine votes are getting partially starved out when bank transactions are high. However, at the cluster level, it doesn't appear TPS fluctuated much through this same period.. WIP to understand why bank transactions are showing this "bathtub" behavior

what TZ are the stamps in these graphs?

**Comment by brennanwatt** [comment]
@t-nelson PST

**Comment by t-nelson** [comment]
ah! this is a dev testnet, not _the_ testnet.  that explains why I can't find these numbers :sweat_smile:

**Comment by brennanwatt** [comment]
These numbers are from my validator (logging to personal Influx database - testnet-dev-bwatt) while connected to _the_ testnet cluster (confirmed it was being seen in testnet using `solana gossip` )

FYI - The results continued to look like the righthand side of the pictures above for several hours. I'm thinking the "bathtub" part of the graph is just some artifact from the validator getting started

**Comment by carllin** [comment]
> However, at the cluster level, it doesn't appear TPS fluctuated much through this same period

There's a more useful metric for figuring out where the leader is getting the votes it's putting into the blocks, that are then propagated over tubine.

The one you were looking at `bank-process_transactions` metric isn't the most useful for figuring out what how the leader is packing the block, because this metric is reported by validators replaying blocks and the leader packing the blocks.

I would also take a look at `banking_stage-leader_slot_packet_counts`, `committed_transactions_count` which is only reported *only* by the leader, per banking thread. 

You can break down if the leader is getting votes over gossip vs it's TPU port by: 

1. If you filter down by `id = 0` you get the metrics for the banking thread processing vote transactions from gossip
2. If you filter down by `id = 1` you get the metrics for the banking thread processing vote transactions sent to the leader's TPU port

**Comment by brennanwatt** [comment]
After some local testing, I believe turbine votes are landing before gossip votes most of the time due to the long sleep period (`pub const GOSSIP_SLEEP_MILLIS: u64 = 100;`) before trying to receive gossip vote updates. In the ideal case, turbine votes take single digit milliseconds to land while gossip often take 10s of milliseconds due to this sleep period.

Is this something we want to play with so that gossip votes get picked up sooner?

**Comment by brennanwatt** [comment]
> After some local testing, I believe turbine votes are landing before gossip votes most of the time due to the long sleep period (`pub const GOSSIP_SLEEP_MILLIS: u64 = 100;`) before trying to receive gossip vote updates. In the ideal case, turbine votes take single digit milliseconds to land while gossip often take 10s of milliseconds due to this sleep period.
> 
> Is this something we want to play with so that gossip votes get picked up sooner?

Chatting w/ Behzad, this vote receive sleep interval is tied to the gossip round interval. Thus, waking up to receive votes more frequently won't help much w/ anything besides the validator's own votes because they're not being pulled from the network more than once per 100ms. Increasing the gossip round rate would obviously have an impact on network congestion, so probably best to leave this sleep interval alone.

**Comment by brennanwatt** [comment]
Here's some interesting data showing turbine vote landing latency during idle vs. when bench-tps is running (data from single validator).
![image](https://user-images.githubusercontent.com/44715351/169913518-4e776712-e806-4375-b6dd-2106e25069a1.png)
As one might guess, latency is considerably longer when we are handling 10s of thousands of client transactions. During these long latencies, we are spending ~1/2 the time between vote creation and leader committing the transaction, and ~1/2 the time between leader confirmation and validator replay. I'm assuming this can be attributed to needing to burn down the transaction queue

Gossip latencies also increase when running traffic, but they are more consistent and shorter overall latency (presumably because they are not competing as directly w/ client transactions):
![image](https://user-images.githubusercontent.com/44715351/169914252-d4855e55-5ed4-4f16-a8b0-fe8a407cdace.png)

Notes on setup:
* 1x bootstrap validator
* 2x additional validators
* 1x client submitting transactions for 3 minutes (achieving ~15-25k AVG TPS)
* All running on GCE instances w/ QUIC TPU

**Comment by brennanwatt** [comment]
Some more data from the last 7 days on MNB showing successful TPU vote transactions getting committed at a rate of ~6:1 compares to Gossip
![image](https://user-images.githubusercontent.com/44715351/172226924-cebd03dc-3d73-42ee-9243-5cbde030bac4.png)

**Comment by brennanwatt** [comment]
Collected some more interesting data to better understand the interaction between turbine and gossip votes. Data was collected for reporting nodes between slots 142426995 and 142428995 (~830 reported slots):

- Successfully committed turbine votes = 1172497 (89.4% of total successful votes)
- Successfully committed gossip votes = 138804 (10.65 of total successful votes)
- Non-retryable failures for turbine votes = 305401
- Non-retryable failures for gossip votes = 252654

Turbine vote failures can be further broken down as follows:
- account_not_found = 618
- blockhash_not_found = 23544
- blockhash_too_old = 285
- instruction_error = 240631
- already_processed = 40323

Gossip vote failures can be further broken down as follows:
- account_not_found = 53934
- blockhash_not_found = 25473
- blockhash_too_old = 11214
- instruction_error = 72183
- already_processed = 89850

A few observations from this:
1. We see ~139k successful Gossip votes but only ~40k cases of turbine votes failing because they've already been processed. This means these Gossip votes are definitely resulting in more (10%) successful votes landing that wouldn't have landed from just waiting
2. Number of failures for instruction error seems really high... 240k represents ~20% or more of the total terminal transaction executions
3. Failure signatures are often (but not always) clustered for a given slot (e.g. 800 instruction errors seen during one slot, but 0 for the next slot)

Need to better understand what is happening and what is driving turbine error rate, but I think the conclusion for now is that Gossip is helping us land more successful votes and we would lose ~10% of votes by turning it off.

**Comment by nikhayes** [comment]
Sorry, I meant to reply to this thread with some observations about periodic vote hash mismatch time periods that correspond to higher periods of bank errors, but accidentally responded here instead... https://github.com/solana-labs/solana/issues/26681#issuecomment-1191750703

**Comment by brennanwatt** [comment]
Created #26718 to distinguish between instruction errors and invalid account index errors.

Also, started running experimental branch on `tv` on testnet and am observing several instruction errors that are all of type `Custom`
![image](https://user-images.githubusercontent.com/44715351/180587851-70dbdedb-5cd0-4a68-a1d9-7c37fca7a423.png)

Need to dig deeper to understand why this error is being thrown so frequently

**Comment by t-nelson** [comment]
> Need to dig deeper to understand why this error is being thrown so frequently

Almost certainly these are `VoteTooOld` which occur when vote transactions land out of order

**Comment by brennanwatt** [comment]
> > Need to dig deeper to understand why this error is being thrown so frequently
> 
> Almost certainly these are `VoteTooOld` which occur when vote transactions land out of order

Right you are. Confirmed that 100% of the instruction errors observed during 1 hour period are `Custom(0)` --> `VoteTooOld`

**Comment by sakridge** [comment]
@brennanwatt Do we have any indication of whether TVU votes or gossip votes are reaching the node first?

**Comment by brennanwatt** [comment]
> @brennanwatt Do we have any indication of whether TVU votes or gossip votes are reaching the node first?

TVU votes are reaching first the vast majority of the time. In only ~5% of cases are TVU votes being flagged as already received (through Gossip)
