### ISSUE TITLE
AgentManager holds process up until connection timeout; devs have no option to explicitly close `Connection`

### ISSUE THREAD

**Issue by NarkomDe** [solana-labs/solana#24970]
#### Problem
It looks like if any JSON RPC request is made through a connection instance from `@solana/web3.js` library, the process of a script idles for approximately 5 seconds after the finish before the exit. This time can really add up when launching multiple scripts consecutively. Is this a known issue? The minimal example can be seen below:
```
const { PublicKey, Connection } = require("@solana/web3.js");

const connection = new Connection("https://api.devnet.solana.com");

async function main() {
  const balance = await connection.getBalance(
    new PublicKey("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA")
  );
  console.log(balance.toString());
}

main()
  .then(() => {})
  .catch((err) => console.log(err));
```

**Comment by steveluscher** [comment]
This is almost certainly because you're running this from Node and our `AgentManager` holds the connection open for…

https://github.com/steveluscher/solana/blob/f912c63b22a9420febc1c4468f45d8b8c2e08da1/web3.js/src/agent-manager.ts#L4

We need to provide you a way to explicitly destroy a connection. Thanks for the report!

**Comment by steveluscher** [comment]
Merging this into #25069.
