### ISSUE TITLE
Listen transaction transfer token on wallet

### ISSUE THREAD

**Issue by docongminh** [solana-labs/solana#25167]
#### Problem
Hi @jstarry 
I am developing feature listen a wallet account for receive a specify token. 
I used `onAccountChange` method. But result AccountInfo have no field to detect in/out amout of token for specify transaction
Could you help me ? How to get data transfer by listen an account ? 
thank so much !

**Comment by jstarry** [comment]
@docongminh In order to get transfer information, you'll need to get transaction history for the account. Can't use the `onAccountChange` method because that will only tell you what changed in the account info. I recommend polling this API to get the recent transactions for an account and looking in the metadata for pre/post token balance https://docs.solana.com/developing/clients/jsonrpc-api#getsignaturesforaddress

**Comment by docongminh** [comment]
i know one for `Extra contextual information for RPC responses` and other `the slot this transaction was processed in` But could you explain for me different between it or share me docment to research.
