### ISSUE TITLE
stake: Delegating an amount below the minimum returns a misleading error message

### ISSUE THREAD

**Issue by brooksprumo** [solana-labs/solana#25337]
### Problem

When the following features are enabled, delegating a stake amount below the minimum will return with an error saying "Error: split amount is more than is staked", which is misleading since the error was caused during `delegate` and not `split`.

Features: 
* https://github.com/solana-labs/solana/issues/24357
* https://github.com/solana-labs/solana/issues/24669

Code in question:
https://github.com/solana-labs/solana/blob/c49efae445042f761b57c8401f82ca1216cba516/sdk/program/src/stake/instruction.rs#L35-L36

Originally encountered in #25336 

### Proposed Solution

~~Reword the error message.~~
Add a new error behind a feature-gate.

**Comment by brooksprumo** [comment]
cc: @joncinque

**Comment by joncinque** [comment]
Bah, sorry about that, we need to actually add a new error and return that finally, based on another feature flag probably

**Comment by brooksprumo** [comment]
Bummer. It is insufficient to just reword the error message?

**Comment by joncinque** [comment]
I think it could cause issues, since during rollout some nodes would produce the old error message, and others produce the new one.  It depends on how those error messages are used by the runtime, but I'm cautious due to this note: https://github.com/solana-labs/solana/blob/84f1e5c0daa0212f2927abd07d9e86314c448e3e/sdk/program/src/instruction.rs#L220-L230

Maybe @jackcmay can tell us for sure what we should do since he put in https://github.com/solana-labs/solana/pull/17864

**Comment by jackcmay** [comment]
Yeah, changing the `String` value without a feature flag is a bad idea because the return value is part of the bank hash
