### ISSUE TITLE
JIT could be done async

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#25409]
#### Problem

We are seeing high JIT latencies sometimes impact the replay time of slots.

#### Proposed Solution

* On a JIT cache miss, the interpreter could be used at first and then the JIT compile kicked off to a background process which could fill the cache.

**Comment by jackcmay** [comment]
I think this is a great idea and one that we want to pursue.  One of the complexities is the differences between the jit and the interpreter.  Alex has done a good job of writing tests to compare the two against each other to ensure parity, but the surface is very large, and it is very likely there may be differences we are not aware of.  These differences could result in a loss of consensus.  Also, there are some other inherent differences related to things being jitted vs interpreted, one big one is that if we jit, the jit compilation itself might fail before even trying to execute anything, in the interpreter, that step is gone, so we will start running the program which may or may not fail at some point during execution

+ @Lichtso for awareness

**Comment by Lichtso** [comment]
I think we should spin up some MNB validators running the Interpreter instead of the JIT to check for consensus loss. They don't need to keep up with the network or vote, just replay real transactions.

In parallel we could think of a strategy to do hybrid Interpreter + JIT execution working together. We probably want the cache to hold a lot more metainfo for improved decision quality and also a lot more entries. Most of these entries would not retain a compiled JIT Executor, just execution statistics.

Another interesting thing @jackcmay and I noticed is that programs can have very different distributions of hot and cold code paths. Some are versatile, they have a lot of code (and also code paths) but most stays cold in every individual run, others are specialized and have only very little code but it is always the hot path. The worst thing is when a versatile program is used sporadically and triggers a lot of JIT compilation of which most is wasted because the compiled code will stay cold.

**Comment by jackcmay** [comment]
@jeffwashington do you have canary bandwidth to set up at least one machine on mainnet that is running bpf programs as interpreted to check for consensus vs mnb which is running all jit?

**Comment by jackcmay** [comment]
Yeah, @jeffwashington, everything else should the same, just add the `--no-bpf-jit` option
