### ISSUE TITLE
test_check_account_subscribe is flaky

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#25423]
#### Problem

test_check_account_subscribe is flaky: https://buildkite.com/solana-labs/solana/builds/74072#_

#### Proposed Solution

Debug and fix it

**Comment by xiangzhu70** [comment]
I have the following questions (copied from the debug notes doc):

When the sol-sub-notif thread calls subscribe, it initializes SubscriptionInfo last_notified_slot from the account state last_modified value.  Why?  Shouldn’t notification state depend on only notification history, not the account history?  The first failure case is due to the main thread gets down process_transaction fast enough (rarely, but is one cause of the flakyness) so the account last_modified state is changed.

What is the relationship between slot and notification?  Is there 1 notification per slot?  Why is the decision to send notification based on last_modified slot ==? last_notified_slot?  Why not let the decision directly base on the received notification sequence number?  if the notification to be transmitted is based on only the notification received, then no notification sending would be skipped.

In the 2nd failure case why should lamports==0 cause the notification to be skipped?  Isn’t that also an account state change which should be notified?   NOT_FOUND causes None return, and that is interpreted as slot 0.  This does not look solid.  The None case should be differentiated from slot 0?

cc'ing related code commiters ri@idzaaus.org, @justin@solana.com

**Comment by xiangzhu70** [comment]
@sakridge 

let expected2 = make_account_result(1, 2, "error: data too large for bs58 encoding");

tx2 sets up a transaction which stores lamport 1 into the account, with the data size too large.  Should the lamport change still go through despite the data size too large error?
