### ISSUE TITLE
CI publish-crate can fail invisibly

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/solana#25485]
#### Problem
If `cargo publish` fails on a crate (eg due to [pulling a breaking dependency version](https://github.com/solana-labs/solana/issues/25476#issuecomment-1134922460), the CI job still looks "green" (reports success), even though the failed crate *and* any that depend on it were not published.

#### Proposed Solution
@t-nelson : Consider adding two steps to the crates publish job, first pass a dryrun and only if it succeeds run again to actually publish.
Alternately, at least actually raise errors and fail the CI job.

**Comment by willhickey** [comment]
I don't think the 2-pass dryrun solution will work because `cargo publish --dry-run` will fail unless the dependencies have already been published. AFAICT the only way to do a full dry-run of our crates would be to maintain our own private registry to publish to.

I also looked into Michael's proposal of not publishing everything in the monorepo. I haven't collected stats yet but at a glance it looks like most of our crates have at least some dependents. AFAICT those dependents would have to fork and publish their own versions to keep their projects alive.

Assuming I'm right about ^ (if I'm wrong I'd love to learn how!) the most viable option is better error reporting so we don't fail silently.
