### ISSUE TITLE
Combat spam by deprioritizing recently active wallets or IPs

### ISSUE THREAD

**Issue by VinceJTorrel** [solana-labs/solana#25628]
#### Problem

I'd like to suggest a broadly effective way of combatting the spam that has so severely taxed the ecosystem of late. I'm aware that there are numerous other proposals described in issues against this repo. This one addresses spam at its earliest point of ingestion from the network. I assume that the team will split this into multiple issues or just refuse parts of it. That's fine, but I think the spam problem needs all the help it can get, at this point. I would have posted this to the Discord, but I lack the required privileges.

I'm aware of the prosed addition of QUIC. My comments here assume that that's already a done deal.

#### Proposed Solution

First of all, I'm aware of Anatoly's proposed ban on repeated writes to the same target wallet within the same block. This is a good policy, but it won't help much unless subsequent attempted writes are somehow greeted with some sort of feedback mechanism that informs the sender that further write attempts will be ignored until the next block. (Rate limiting is nice, but it would be better if the sender would just shut up.) I don't know if this is even possible to convey in some form of reply, which means that dumb bots may just keep spamming anyway. So the first suggested change would be to facilitate such a reply and at least make app developers aware of it. "You lose, for now. Stop asking to write to wallet X until a block time has elapsed."

Secondly, I'm aware of the recently merged change to drop packets at random under heavy congestion. This is indeed what would occur naturally anyway. But I think the randomness should be biased against wallet addresses which have more recently been involved in finalized transactions. Unfortunately, we can't do this on the IP address level directly: It's hard to attach counters to all 32-bit IPv4 addresses (as though they're static anyway, which they're not) and effectively impossible with 128-bit IPv6 addresses (which can, by the way, be mutated in a zillion ways but still pass QUIC authentication). Therefore I would suggest an approach that works backward from the fee payer's wallet to all of its associated IP addresses. Consider this: if the payer's wallet was last active in a finalized transaction 5 blocks ago, then _all_ IP addresses associated with that wallet should have a weight of one fifth for the sake of deciding which packets to ignore. After applying this weighting, we might decide in a (biased) random manner that we need to ignore all transactions involving fee payer X. Now, without even autheneticating incoming packets, we can just delete all of them which have X as the fee payer. This means that we tend to ignore recent transactors (transactors, not transactions) in order to make room for those who have not touched the chain in a long time. This would go a long way toward disempowering bots that just smash the validators all day long in the hopes of scoring a transaction. The more you transact, the more we'll deprioritize you until we have time to listen to your jabber.

One corollary of this policy is that we'd need to treat source and target wallets the same for the sake of computing the weighting. Otherwise a bot could just move from wallet X to wallet Y so as to evade deprioritization on the next block. I think the weight should purely depend on the number of blocks since the last transaction involving the wallet in question, as the compute load is essentially independent of transaction size (but this is debatable if for example we want to discourage trivial transfers).

Too much to implement? Then a quick and dirty approximation of all this would be to attach counters to all IPv4 addresses (and perhaps all contiguous 32-bit subparts of IPv6 addresses) and ignore incoming packets in a random manner which is weighted by how many packets ago we received another packet from the same address. It would go a long way by at least forcing the bots to hop IPs from time to time, which would cost them probably hundreds of milliseconds of latency, leading them to lost transactions and eventual extinction. A further enhancement would be to implement address spacing maximization, so for example if we've been talking to 17.241.3.96 and 99.52.104.193, then we would prioritize packets from 49.86.71.5 above those from 17.240.6.88 (because it's father away in IPv4 space and therefore less likely to be part of the same botnet).

**Comment by VinceTorrel** [comment]
By the way, while I'm not against deduping, I think it goes without saying that it's only too easy to create polymorphic spam that evades such measures. We need a broader net.

**Comment by michaelh-laine** [comment]
> First of all, I'm aware of Anatoly's proposed ban on repeated writes to the same target wallet within the same block. This is a good policy, but it won't help much unless subsequent attempted writes are somehow greeted with some sort of feedback mechanism that informs the sender that further write attempts will be ignored until the next block. (Rate limiting is nice, but it would be better if the sender would just shut up.) I don't know if this is even possible to convey in some form of reply, which means that dumb bots may just keep spamming anyway. So the first suggested change would be to facilitate such a reply and at least make app developers aware of it. "You lose, for now. Stop asking to write to wallet X until a block time has elapsed."

My understanding is that QUIC does in fact implement this "back off" feedback mechanism within its protocol

**Comment by VinceTorrel** [comment]
@michaelh-laine I see, and thank you for pointing that out. But then how does QUIC say "come back in another block time" or "we just started the next block so you can try again now". We want to kill spam but at the same time allow as much rapid-fire transaction activity as we can actually handle. I would imagine that the QUIC context doesn't carry over from one block to another, but hopefully I'm wrong. I just have a hard time imagining that the validator software would take the bandwidth to say "OK, you're clear to try again now" in followup to a traffic suppression request from a previous block. (And it can't happen within the same block, assuming that Anatoly's one-write-per-wallet-per-block fix is eventually implemented. So if your write attempt get suppressed, that means we need to remember to unsuppress you while the _next_ block is under construction. Seems unlikely we'd carry the conversation that far, but it's possible.)

What I'm mainly advocating here is to make the probability of transaction success inversely related to the frequency of transaction attempts. The more you're involved in _any_ successful transaction as a sender or a receiver, the lower your priority in the queue. If your wallet was most recently a party to a transaction 5 blocks ago, then it has greater odds of having _all_ its pending traffic dropped from the queue than a wallet that was last involved in a transaction 8 blocks ago. (Ideally, we wouldn't ignore any attempted transaction, but that's no longer possible to guarantee in the world of NFT bot wars.)

The mistake that I see being made is an attempt to estimate prices for compute units and wallet transfers. That's actually irrelevant to the spam problem because if the total cost is still worth paying, then the spam will still happen. What we need is an active punishment system that deprioritizes parties to successful transactions. (Unfortuantely, we can't base spam suppression on failed attempt count because by definition that metric is not recorded on chain, so we can't all agree on it.) I would further argue that the only point of Solana's trivial transaction fees is to thwart spam (but this is not true of Ethereum); inflation alone actually pays for securing the network and validating transactions. It's not like anyone earns significant revenue from fees.

It's like this: I don't get charged a fee to walk into my bank branch. But I'm forced to stay in line until it's my turn. After I do my transaction at the teller window and walk away, I can't just cut right back to the front of the line if I forgot something. I need to get back in line and wait again.

What Solana is currently doing is trying to increase the cost of speaking with the bank teller, from say 5 cents to 50 cents when I have a more complicated issue to discuss. But if I can do a highly profitable business deal by paying the teller 50 cents, then I'll do it. And not only that, I'll push everyone else away from the teller window so I get service first.

I think that's a flawed approach. I need to be taught that if I'm obnoxious, then I'll keep getting pushed to the back of the line.

I don't know enough about the Solana architecture to know exactly which components to modify and how, but I hope that someone who does  ( @jstarry  ) will understand the abstract argument I'm making here. We need to exhaust the spammers before the kill the ecosystem.

**Comment by VinceTorrel** [comment]
For the record, I think the best solution is to have the fee payer declare what they're willing to pay for any given transaction, then let the network decide what to execute. This would be the exact opposite solution, wherein the fees pay to run the network and there's no need for inflation. However, I realize that this is just too invasive of a change at this point. So realistically, the best we can do is the opposite: have low (or even zero) fees, positive inflation, and deprioritize by recency of transaction involvement.

However, if this is _still_ too big of a change, then an emergency fix would be to scale the fees in proportion to the reciprocal of [(blocks since last transaction involvement) raised to some positive power]. That way Solana remains cheap and highly available for manual use but rapidly becomes exorbitant for bot use. But OK, if the bots are going to pay 1000 SOL for 10 successful transactions over 10 successive blocks, so be it.

Consider that the cost of pulling N spam messages/packets out of the input pipeline is at least (N log N) because it requires a lookup for each packet in a memory structure (such as a B tree or the like). But at some large N, you bump to the next more distant cache, incurring an _exponential_ penalty in data access time. And so on as N continues to grow. The fees need to reflect this, at least roughly. Granted, the cost curve against N isn't actually exponential because each successive cache level is also exponentially larger (by a factor that depends on the hardware). The bottom line is that (N log N) costing is too cheap, and even (N^2) might be too cheap when you consider that thousands of spammers sending millions of messages might only result in a handful of successful transcations. Worse still, you can't actually set the fees according to N because N is not the object of any consensus. It's as if the winner just sent one message and got lucky. So the best you can do, realistically, is to amp the fees based on the recency of (finalized) transaction involvement according to some obnoxiously inverse polynomial pricing curve.
