### ISSUE TITLE
solan-test-validator can't be launched

### ISSUE THREAD

**Issue by glcanvas** [solana-labs/solana#25896]
Hi! 
trying to launch solana-test-validator but getting this error:
```
(base) nduginets@admins-MacBook-Pro ~ % solana-test-validator  
dyld: Symbol not found: __ZNSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE7seekoffExNS_8ios_base7seekdirEj
  Referenced from: /Users/nduginets/.local/share/solana/install/active_release/bin/solana-test-validator (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libc++.1.dylib
 in /Users/nduginets/.local/share/solana/install/active_release/bin/solana-test-validator
zsh: abort      solana-test-validator
(base) nduginets@admins-MacBook-Pro ~ % 
```

My macOs version is 11.6, yes I read logs and see that this solana-test-validator was built for Mac OS 12.0 but is here version for Mac os 11? 

I downloaded solana with this command:
```bash
sh -c "$(curl -sSfL https://release.solana.com/v1.9.26/install)"
```

**Comment by steviez** [comment]
Hi @glcanvas - we only build against the one (current) macOS version, and the error isn't terribly surprising between major versions of macOS. If you're not keen to upgrade macOS, you could also build and run the test-validator from source:
https://github.com/solana-labs/solana#readme

**Comment by vvsuperman** [comment]
Hi, I follow the instruction and build from source, then how to install solana on my mac? do I need to uninstall my former first?

**Comment by steviez** [comment]
> then how to install the builded solana target on my mac? do I need to uninstall my former first?

What do you mean by install in this context? You're free to move the built binaries to any directory you'd like, and likewise, modify your `$PATH` to include that directory so that you can run `solana-validator` from any directory. However, I would make sure that your `$PATH` variable only includes one set of binaries; otherwise, the chosen version will depend on ordering in `$PATH` which could be unexpected / easy to overlook.

We have a script that will automate building, and also includes a note about updating path
https://docs.solana.com/cli/install-solana-cli-tools#build-from-source
