### ISSUE TITLE
Installing v1.10.26 Installs The Incorrect Version (Or Includes An Incorrect Version Number)

### ISSUE THREAD

**Issue by bonedaddy** [solana-labs/solana#26064]
#### Problem

Installing v1.10.26 installs either the incorrect version (1.11.0) or has an incorrectly labelled version number (1.11.0):

```
buntu@reallybig-2:~$ sh -c "$(curl -sSfL https://release.solana.com/v1.10.26/install)"
downloading edge installer
  ✨ edge commit a5f290a initialized
ubuntu@reallybig-2:~$ solana-validator --version
solana-validator 1.11.0 (src:a5f290a6; feat:528226107) <---- bad version number
```

**Comment by mvines** [comment]
I manually re-triggered the secondary 1.10.26 build and that fixed it. But some release process somewhere looks to be going wrong.  Also added more [logging](https://github.com/solana-labs/solana/commit/2353c2c701ece0ede5726a0b043362a87f8da10a) so that hopefully we'll be able to better debug if this happens again with 1.10.27

**Comment by mvines** [comment]
1.9.29 also seems to be affected

**Comment by yihau** [comment]
I will keep my eyes on next few releases after the PR is merged

**Comment by yihau** [comment]
v1.10.27, v1.10.28, v1.10.29 are all good. 🎉
