### ISSUE TITLE
QUIC client opens unnecessary connections

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#26097]
#### Problem
QUIC connections support concurrent streams so there's no need to open concurrent connections to the same server. A single connection should be sufficient. Opening 4 connections will cause quic server connection limits to be met sooner than necessary. Additionally, connection pooling is not taken into account when enforcing the number of max connections:
https://github.com/solana-labs/solana/blob/e344c8476f5aa63860602923c5db68f5fc33b7f8/client/src/connection_cache.rs#L319

#### Proposed Solution
Remove connection pooling in QUIC connection cache or reduce connection pool size to no more than 2.

**Comment by KirillLykov** [comment]
To clarify, if it is related thing: when profiling bench-tps I see 4 threads called "tokio-runtime-w" (https://share.firefox.dev/3P9KQp3). Looks like half of the time they do something useful and half not while it is definitely enough to have 1 thread and 1 connection to send 25pps.

**Comment by stakeconomy** [comment]
![image (2)](https://user-images.githubusercontent.com/25040379/194549349-aa7924cc-4acf-4468-8815-6aacf106d8dc.png)

Triton does see the same behaviour on many sendTransactions. We found there is def. a relation of burst of sendTransaction and tokio-runtime-working blowing up and using all free CPU threads

![image (3)](https://user-images.githubusercontent.com/25040379/194549556-003bfdb9-b052-4d33-9b00-bc781a73a985.png)

**Comment by ryleung-solana** [comment]
The main issue here IMHO isn't really the number of connections but the number of concrueent send calls (e.g. send_batch, send_transaction, etc), which is currently not rate-limited. So while each send_batch calls limits the number of steams it opens concurrently, there's no limit on number of concurrent send_batch call for example. So the issue is really to figure out a performant way to rate-limit the number of send calls somehow.

**Comment by KirillLykov** [comment]
I wonder if this issue is still relevant or these concerns have been addressed
