### ISSUE TITLE
Transaction wastes bits with transaction fee

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#2635]
#### Problem

The transaction fee is 8 bytes and its value is not intended to be a "bid". The price is set by the cluster, not the client.

#### Proposed Solution

Store the price in the Last IDs queue. Extend the `getLastId` API with that price. When the transaction arrives, the leader should charge the price that matches the transaction's `last_id`.

If the client wants to set an upper bound, that can be done with userdata and handled by the on-chain program.

**Comment by garious** [comment]
@aeyakovenko, @mvines, what do you think?

**Comment by aeyakovenko** [comment]
@garious Not sure if it will work.

* The economic model allows the leader to collect excess fees. 
* leaders do a check for capacity to pay the fee before the accounts are locked
* The fee is going to be variable based on the number of bytes and instructions in the programs.

Somewhere in the root checkpoint the minimum per byte fee and per instruction fee will be computed. We might need to expand the tx format to include the expected total instruction count, so the leader can compute how much "bonus" they get for that tx.  Or we do away with the bonus entirely because the network will never be at capacity (tag @ericlwilliams on the last point)

**Comment by garious** [comment]
We can work with all those constraints. But first, let's make simple things simple.

**Comment by aeyakovenko** [comment]
@garious, also cross chain atomic swaps wont work with transactions that can expire, so the LastId can't really be overloaded as a fee as well.

**Comment by ericlwilliams** [comment]
Only the minimum fee to be confiscated by protocol is to be determined by the cluster, client should still be able to 'bid' above this. The leader is to keep the net sum of the fees _less_ the minimum fee confiscated.

**Comment by garious** [comment]
Problem description is under the premise that the fee is not a bid. @ericlwilliams says it is. Closing.

**Comment by aeyakovenko** [comment]
@garious, you will still need to have that field.  The transaction needs to specify the max it expects to pay for execution. Instructions, bytes fetched, bytes written, all those add up to a max value

**Comment by garious** [comment]
That can all be captured by `last_id`. The signature on a transaction with a last_id can mean the signer expects to be charged the fees defined in a config account and to use the values at the time last_id was recorded.

**Comment by aeyakovenko** [comment]
@garious, but it’s trusting the network to be charged the max amount.  It’s hard to prove the number of instructions executed.

**Comment by aeyakovenko** [comment]
how long do you expect an epoch to be?  6 hours?

**Comment by garious** [comment]
But somehow every validator will arrive at the same number?

**Comment by aeyakovenko** [comment]
@garious, yea I get it.  I think if the epoch is long enough, like over 10 min we should be good.  Make the last id optional for atomic swaps and save a few more bytes :)
