### ISSUE TITLE
transactions do not work in solana-test-validator in 1.11.5

### ISSUE THREAD

**Issue by samurajj** [solana-labs/solana#27126]
#### Problem
When starting solana-test-validator, no transaction can be made. Not even an airdrop. 

It works in [1.11.4](https://github.com/solana-labs/solana/releases/download/v1.11.4/solana-release-x86_64-unknown-linux-gnu.tar.bz2)
It does NOT work in [1.11.5](https://github.com/solana-labs/solana/releases/download/v1.11.5/solana-release-x86_64-unknown-linux-gnu.tar.bz2).

My steps:
```
./solana-test-validator --reset
```
and in another window:
```
./solana-keygen grind --starts-with XX:1
./solana config set --keypair XXF16TEoBi8skqbEg5N3jNgBuw6GEyfy6QAmZeWk2m4.json 
./solana config set -ul
./solana airdrop 1
```

=> Problem is that the airdrop hangs until timeout with message "Error: unable to confirm transaction. This can happen in situations such as transaction expiration and insufficient fee-payer funds"
But that error seems unrelated.

I tried different approach: I had started it with mint address and transferred from it with the same result. My steps for that:
```
./solana-test-validator -ul --reset --faucet-sol 1000000 --mint XXXNB6suND4rk2Q5arGAZnZDDShuagvKGuMC1VPy4KN
# in another window:
./solana transfer  --from XX* ZHPCz6vE4Fhg99pPTHFWHCtRfScQUEZjhCzCUR4eRyJ 1000 --allow-unfunded-recipient
```
I tried ```/solana logs``` in another window and it doesn't log anything for those transactions...

My system: Ubuntu 20 LTS

#### Proposed Solution
No idea, check changes on git?

**Comment by CriesofCarrots** [comment]
Hello, there. This is a known issue with solana-test-validator in v1.11.5, which sets client actions to use quic by default. The bug was fixed [in master](https://github.com/solana-labs/solana/pull/27046) and [in v1.11](https://github.com/solana-labs/solana/pull/27053). We don't have a new v1.11 release yet, but if you upgrade to the tip of the beta branch (`solana-install init beta` or build from source), you can run the patched version.
