### ISSUE TITLE
RPC: No way to get latest valid blockheight given a blockhash

### ISSUE THREAD

**Issue by jacobcreech** [solana-labs/solana#27189]
#### Problem

Given a specific blockhash, there's no way to know what the latest blockheight that the blockhash is valid.

There exists [isBlockhashValid](https://docs.solana.com/developing/clients/jsonrpc-api#isblockhashvalid), but relying on this when retrying transactions is unreliable due to the potential issue of hitting a RPC that does not have the blockhash yet.

#### Proposed Solution

Let's add either a new RPC call or add the ability to get context slot back from isBlockhashValid.

**Comment by mvines** [comment]
[getLatestBlockhash](https://docs.solana.com/developing/clients/jsonrpc-api#getlatestblockhash) returns a `lastValidBlockHeight` field along with the blockhash, so ideally the client simply retains that field and uses it to determine expiry by comparing against [getBlockHeight](https://docs.solana.com/developing/clients/jsonrpc-api#getblockheight) periodically while waiting for their transaction to confirm.

A new RPC method or adding field to `isBlockhashValid` is a little tough because nodes don't retain all previous observed blockhashes. This means that eventually it'll be impossible to distinguisha blockhash from the distant past from and one that has never been valid to begin with.

**Comment by jacobcreech** [comment]
The usecase here is that a transaction may have a recent blockhash provided by a wallet. Apps and other helper libraries will only have the signature + blockhash and not know when to reliably stop retrying the transaction.

Seems like there is no good solution given that you could either have 

1. RPC that doesn't know of the blockhash yet and therefore `isBlockhashValid` returns false/not found (false negative)
2. Blockhash is way too old and not stored on the RPC, so return false/not found
3. Blockhash is stored on the RPC and you get the `lastValidBlockHeight`

There's no reliable way to figure out is response 1 should have been response 3. You *may* get response 3 first and be able to compare against `getBlockHeight` normally, but no guarantee.

Closing for now. Thanks for the response.

cc: @jordansexton

**Comment by jordansexton** [comment]
Hmm, that definitely answers my question of "is it possible now". I might not be following why this would be hard to add though.

Either a blockhash is recent enough that you know it's valid, and you could tell when it won't be.

Or it's not recent enough, and you don't have it anymore, or you never saw it, so it's not valid. Right?

**Comment by jordansexton** [comment]
Basically, in the scenario described, I think the app can ask the RPC "is the blockhash valid", and the RPC can say "I dunno, guess not" or "yes (and it's good until this height)". Currently the RPC doesn't return that, but it could be knowable, right?

**Comment by jacobcreech** [comment]
> Either a blockhash is recent enough that you know it's valid, and you could tell when it won't be.
> Or it's not recent enough, and you don't have it anymore, or you never saw it, so it's not valid. Right?

There's also the case of response 1:

> RPC that doesn't know of the blockhash yet and therefore isBlockhashValid returns false/not found (false negative)

More thoroughly:
1. Wallet RPC that retrieves blockhash is update to date
2. Client RPC is behind 30 slots
3. Client then calls RPC method to get blockhash context
4. Client RPC returns invalid/not found because the RPC doesn't have knowledge of the blockhash yet

This makes getting the context of a blockhash pretty unreliable.

**Comment by jordansexton** [comment]
I think it's fair to say best practice is probably for the app to get the latest blockhash, last valid block height, and min context slot. Then pass those as options to the wallet.

But assuming the blockhash that was selected was at least `confirmed` or `finalized` and the transaction it's on is presumed to have been recent, it should be found fairly reliably I think?

**Comment by mvines** [comment]
> I think it's fair to say best practice is probably for the app to get the latest blockhash, last valid block height, and min context slot. Then pass those as options to the wallet.

Yes, 100%.

**Comment by jordansexton** [comment]
I think we could expose this in the `isBlockhashValid` RPC call. It's more useful to know when it will be valid until than only if it's valid right now.

This is because you might ask if it's valid, and it is, and then becomes invalid before you can do anything with it, because it's already near EOL.

**Comment by t-nelson** [comment]
an alternative could be to query the recent blockhash through the wallet (adapter?). wallet can then cache the result until it expires, putting an upper bound on cache size.
