### ISSUE TITLE
Benchmark performance of loading many accounts from transactions using address lookup tables

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#27211]
#### Problem
Lack of benchmarks that measure performance across transactions that load different number of accounts

#### Proposed Solution
Configure bench-tps to use transactions with multiples of 32 accounts (up to the max of 256) and then run bench tests to see performance metrics

**Comment by jstarry** [comment]
See https://github.com/solana-labs/solana/pull/26948 for how to bump the account lock limit for a test validator

**Comment by jstarry** [comment]
FYI I'm working on feature gate which will bump the account limit per transaction to 256. But doing the bench testing described in this issue is a prerequisite to activating the feature

**Comment by jstarry** [comment]
@CriesofCarrots do you have a timeline in mind for setting up the benchmarks? I can help add lookup table support to bench-tps if needed

**Comment by CriesofCarrots** [comment]
> @CriesofCarrots do you have a timeline in mind for setting up the benchmarks? I can help add lookup table support to bench-tps if needed

I was hoping to dig into this properly yesterday, but several other things are lingering on the list before this. If you have the bandwidth to start on it, I'm happy to defer. I can check in later and pick up wherever you are, or just serve as reviewer, whatever seems most helpful.

**Comment by jstarry** [comment]
I'm merging https://github.com/solana-labs/solana/pull/27242 to unblock Neon on devnet which needs about 100 accounts for many of the smart contract functions they intend to support. However, I won't be activating it without first doing the perf testing laid out by this issue FYI

**Comment by taozhu-chicago** [comment]
Does the accounts' size matter? I mean does loading a 10B account same as 10MB account?

**Comment by dlin128** [comment]
Hey @taozhu-chicago! David from Eclipse here. We are heavily using neon-evm on our forked instance of solana and we've hit the 128 account limit quite a few times now. I'm wondering if you guys got around to designing or implementing the benchmarks. If not, perhaps this is something we can contribute to and we would love to sync with you guys on a spec first.

**Comment by taozhu-chicago** [comment]
Hey @dlin128, thanks for reaching out. We have various tests regarding read/write different number/size of accounts, but, as far as I know, have not implement bench-tps as described in this issue. It'd be good to have it, and to understand your concerns/needs. Are you interested in finding out the performance impact of more than 128 accounts?

**Comment by dlin128** [comment]
Yes. I think we may need to increase to 256 for some of the contracts to work, so we'd like to understand the performance impact first.

**Comment by taozhu-chicago** [comment]
gotcha. I'll update bench-tps tomorrow, hope that'd provide some data points on increasing accounts to 256. Let me know if that works for you.

**Comment by dlin128** [comment]
That sounds good to us. Keep us updated!

**Comment by dlin128** [comment]
@taozhu-chicago any update on this?

**Comment by taozhu-chicago** [comment]
thanks for reminder, am working on it (alone with few other things), will update here with PR to change

**Comment by taozhu-chicago** [comment]
@dlin128 It looks like I overlooked the fact that ALT is not yet hooked up to bench-tps. A quick dirty hardwiring didn't pan out as I thought 😞 
To do it properly, we probably need to:
1. add command line param, use it to bump account lock limit
2. add command line param, use it to specify number of accounts to be loaded by Transfer transaction via ALT;
3. add ALT support to bench-tps
  3.1 create address-lookup-table with specified number of entries;
  3.2 create accounts for each entry in address-lookup-table, perhaps with various size;
  3.3 update Transfer Transaction to include ALT account.

There are few test scenarios we could/should cover, for example:
- number of read/writes in ALT;
- size of accounts in ALT;

If it helps, I am happy to sync over zoom or dm, otherwise I'm working through above list.

**Comment by taozhu-chicago** [comment]
test setups:

**Comment by taozhu-chicago** [comment]
Test setup using codebase #32281 
1. run test-validator as single-node cluster:
    - transaction account lock limit increased to 256, 
    - deploy `noop` sbf program with any valid Pubkey,
`./cargo nightly run --release --bin solana-test-validator -- --reset --transaction-account-lock-limit 256  --bpf-program FbXmsPdGqmSPrtbPCuvX16SEWqA3w6Ee16wu6jucFZuG ./programs/bpf-loader-tests/noop.so`
2. run bench-tps against test-validator:
    - configured with test-validator's entrypoint
    - use `--load-accounts-from-address-lookup-table` to use `noop` to load desired amount of accounts from address-lookup-table.
`./cargo nightly run --release --bin solana-bench-tps -- -u localhost --use-randomized-compute-unit-price  --faucet "127.0.0.1:9900" --entrypoint "127.0.0.1:1024" --load-accounts-from-address-lookup-table FbXmsPdGqmSPrtbPCuvX16SEWqA3w6Ee16wu6jucFZuG 64`

**Comment by dlin128** [comment]
This is awesome. We will take a look as well! Anything in particular we should help test?

**Comment by taozhu-chicago** [comment]
I used `noop.so` program in test, which does nothing to accounts. If you have program that mimic closer to what you are doing, you might want to use that in test to see how it turns out. (you probably need to [update these lines](https://github.com/solana-labs/solana/pull/32281/files#diff-f466d902c328d03c5941b2ea2831da4b011d934f65b51eb1e3e6d639e6926316R678-R682) if you use your program)

Another test I would like to see is the size of accounts loaded from ATL. (They are empty in my test)

**Comment by apfitzge** [comment]
I modified your branch - https://github.com/apfitzge/solana/pull/new/apfitzge/bench-tps-tx-account-limits

I think the original bench you ran suffered from a few issues:
1. w/ a single ALT with the txs write-locking all accounts, this mean ALL transactions conflicts - only one transaction can be processed per batch by a single thread.
2. w/ a single ALT it's sort of the "best-case" since that ALT will always be in the cache for accounts db to load quickly

## Read-Only Single Table Results
This series of tests uses a single ALT but the accounts are read-locked.

| \# Accounts      | Max TPS | Avg TPS| 
| -----------: | -----------: |  --: |
| 1 | 50497 | 32056 |
| 4 | 50752 | 32599 |
| 16 | 46252 | 30760 |
| 32 | 28981 | 24103 |
| 64 | 16636 | 12211 |
| 96 | 11902 | 8958 |
| 128 | 8959 | 6304 |
| 160 | 7231 | 5182 |
| 192 | 7744 | 5205 |
| 224 | 6847 | 4002 |
| 250 | 6124 | 3819 |

## Read-Only 10k Table Results

This series of tests uses a 10k ALTs, each tx randomly selecting one, and the accounts are read-locked.

|# Accounts|Max TPS|Avg TPS|
|--:|--:|--:|
| 1 | 49985 | 33685 |
| 32 | 25694 | 20163|
| 64 | 13757 | 10622 |
| 128 | 7296 | 5591 |
| 250 | 3457 | 2422 |


## Write 10k Table Results

This series of tests uses a 10k ALTs, each tx randomly selecting one, and the accounts are write-locked.

|# Accounts|Max TPS|Avg TPS|
|--:|--:|--:|
| 1 | 49981 | 32408 |
| 32 | 11700 | 9929 |
| 64 | 6534 | 5326 |
| 128 | 3482 | 2844 |
| 250 | 1841 | 1256 |

Interestingly, one of the main bottlenecks for these write-transactions was actually the 48M block limit. 250 lock test is roughly 75 kCUs per tx, so that only allows for roughly 600 txs per block.
