### ISSUE TITLE
web3.js on React Native bug - No identifiers allowed directly after numeric literal

### ISSUE THREAD

**Issue by ajrod124** [solana-labs/solana#27347]
#### Problem

I recently build a mobile dapp using the React Native scaffolding dapp recommended here: https://solanacookbook.com/integrations/react-native.html#solana-dapp-scaffold-for-react-native

The @solana/web3.js package by default is at version 1.41.3. Upon attempting to upgrade this to the latest, I received the following error on my device:

![Screenshot_20220823-120550](https://user-images.githubusercontent.com/9423063/186247663-63c14408-35a6-4704-a742-1f23a3180066.png)

I figured out that the breaking change took place on this commit for release version 1.41.7: https://github.com/solana-labs/solana-web3.js/commit/980f460e0e22dd8f82d25e067da9d636c2841d08

Note that the only change from the cloned React Native scaffolding dapp is the @solana/web3.js version from 1.41.3 to 1.41.7

#### Proposed Solution

A workaround that can be implemented from the dapp's configuration files.

**Comment by steveluscher** [comment]
Message received! I'm seeing this too.

**Comment by steveluscher** [comment]
So, fun fact: the material change was actually [this one](https://github.com/solana-labs/solana/commit/dcef8ec1006596ed1f46594b16b147e5e809395e#diff-00f853ca82f33fd6c5afe5ea06f22de7dfa6844067ca2d51a40928faf148697eR35).

* JavaScript Core (JSC) doesn't support the exponentiation operator (`**`) so there's a transform that converts `2n ** 64n` to `Math.pow(2n, 64n)` and _then_ you're in trouble because `Math.pow()` doesn't work with `bigint` (runtime fatal)
* Hermes supports the exponentiation operator but doesn't support `bigint` yet.

I'm right now in the middle of figuring out what to do, but I think the answer is going to be: if you want to use newer versions of web3.js with React Native, you will have to upgrade to React Native 0.7 and Hermes.

Stay tuned.

**Comment by steveluscher** [comment]
https://twitter.com/steveluscher/status/1563940218444840960

**Comment by steveluscher** [comment]
We've advanced the requirements for using `@solana/web3.js` with React Native to a version that supports BigInt literals. https://github.com/solana-labs/solana/tree/master/web3.js#compatibility
