### ISSUE TITLE
Solana CLI not working with the new ledger nano s plus

### ISSUE THREAD

**Issue by codemonkey6969** [solana-labs/solana#27441]
The Solana CLI is not working with the new ledger nano s plus. It works with the normal nano s and the nano x.

**Comment by steviez** [comment]
Hi @codemonkey6969 - I'm unsure what specific issue you encountered, but the following post might be helpful:
https://solana.stackexchange.com/questions/207/error-no-device-found-when-using-ledger-nano-s-plus-with-solana-cli

The Solana Stack Exchange is still relatively new, but we're trying to funnel technical support questions over there instead of here on GitHub. In lieu of that, if the answer in link above doesn't work for you, please post a followup question there
