### ISSUE TITLE
Vote refresh will fail if slot is outside SlotHashes

### ISSUE THREAD

**Issue by carllin** [solana-labs/solana#27566]
#### Problem

Vote refresh will fail if the refreshed vote is too old to be in  SlotHashes

#### Proposed Solution
Refresh vote at tip of heaviest fork descended from last vote

**Comment by AshwinSekar** [comment]
Some more context:

When votes aren't landing, validators can't make progress, fail Threshold etc., we can use refresh to speed up recovery and maintain commitment level when votes do start landing.

However these refreshed votes don't succeed when network regains health anyway because they are outside slot hashes. 
Instead we wait for enough lockout to expire so we pass the threshold check and vote closer to the tip.

**Comment by wen-coding** [comment]
I'm confused, is the proposed solution:
1. don't send out refresh votes which will be outside slot hashes, because these will fail, wait for lockout to naturally expire and we will then send correct votes
or
2. let's just skip over to somewhere inside s lot hashes and vote right now (this is not refresh vote, since we haven't voted for this new descendant yet)

**Comment by wen-coding** [comment]
Summarizing the current plan:
1. maintain the fact that vote refresh is a fast path, make the change in the main select_vote_and_reset_fork() path, so that vote refresh will always have the same decision
2. on the main path, if heaviest_bank is on the same fork as last_vote's fork, then there is nothing to do, heaviest_bank should be picking a leaf which is within SlotHash. If that leaf is outside SlotHash already, there is nothing we can do
3. if the failure reason is FailedSwitchDuplicateRollback, then the last_vote is for a duplicate slot and should be rolled back, we should not continue on this fork anyway
4. so, only if the failure reason is FailedSwitchThreshold, and our last vote is outside SlotHash, we are considering a new option here. The situation is:
- we see another fork with more votes
- we can't switch because we are somehow in lockout etc
- our last vote also couldn't land because it was outside SlotHash
The options are:
a. do nothing and wait for more people to confirm the other fork
b. pay the cost of longer lockout, vote on the current fork, because other people might be waiting for our vote
We used to do a, now we want to do b, pay the cost of longer lockout so we cast our vote
When we do this, there is another choice, which bank on the current fork do we vote on, the choices are:
A. vote on the oldest one on the current fork in SlotHash
B. vote on the newest leaf on the current fork in SlotHash
C. vote somewhere in between

The original proposal is A, but after discussion, we fear that if we vote on the edge of SlotHash, we might need to do the same thing again soon when this slot we just voted on got out of SlotHash, so now we prefer B, which is closer to the normal path, it just means we have longer lockout.

**Comment by AshwinSekar** [comment]
don't think you need FailedSwitchThreshold. Conditions should be:
1) Last vote hasn't landed
2) last vote has expired (needs refresh to land)
3) last vote is outside slot hashes (won't land even if we refresh)

If 1, 2, and 3 are met we should stop sending refresh votes and instead send a vote for the `best_slot` on the fork we last voted on `HeaviestSubtreeForkChoice::heaviest_slot_on_same_voted_fork`

**Comment by wen-coding** [comment]
See my comments above. In case 2, you are sending the same vote as the main path, so this is a waste. In case 3, the last vote is a duplicate (not duplicate confirmed), so voting on the best_slot in this fork is actually a wrong choice. We only need to send out vote in case 4.

In any case, I think we are talking about the same action, I'm just removing a few conditions where we don't need to send this vote at all.

**Comment by AshwinSekar** [comment]
Just seems too specific, why not just do it only when we need to refresh and we know refresh will fail? Could be reasons other than `FailedSwitchThreshold` for why we can't vote.

**Comment by wen-coding** [comment]
I think we are talking about the same thing, just written in different ways. You are proposing:
if (we need to refresh vote) {
   if (all new conditions meet) {
       vote at the leaf of current fork
   }
}
main path

I'm talking about:
if (we need to refresh vote) {
   ... original refresh code
}
// main path
..old code
case (failure reason is FailedSwitchThreshold) {
  if (all new conditions meet) {
     vote at the leaf of current fork
  }
}
So you can see the results are similar, it's just where you put the code. This is mostly an aesthetic choice. Because we think vote refresh is a fast path which reiterates the choice we made, it felt neater to use the latter, so vote refresh remains a fast path, it will never make a different choice than the main path, all the decision making logic is on the main path.

**Comment by AshwinSekar** [comment]
yeah i don't mind where in the code it occurs i'm just arguing for the removal of this line
> case (failure reason is FailedSwitchThreshold) {

**Comment by wen-coding** [comment]
In the case of FailedSwitchDuplicateRollback, isn't it wrong to cast more votes on the current fork? I don't mind the extra vote generated in case 1.

**Comment by AshwinSekar** [comment]
this case is agnostic of switch failures, refresh vote is a backup for when we're stuck - this is a backup for when refresh fails. 
If you're sending the same vote as the "main path" then condition 1, (Last vote hasn't landed) will be false. If we have some sort of `FailedSwitch*` failure then condition 3 (last vote is outside slot hashes) will only be triggered if we are stuck.

Another possibility is if we are in a partition and simply don't receive any blocks and our vote didn't land - we have nothing to vote on. We still want to refresh once the partition is resolved however condition 3 might be in effect causing the regular refresh path to fail. The switch proof situation that we almost observed in the testnet failure was simply an example, it is possible to reach conditions 1,2 and 3 through different means so I think including `FailedSwitch*` as a condition is too restrictive.

**Comment by AshwinSekar** [comment]
idrc where the change ends up happening but fwiw `select_vote_and_reset_fork()` picks the ideal vote and reset bank we would vote on if we could, however vote refresh votes resigns a vote on the previous vote which might not be similar. given the spirit of this change seems like it would do best in either  the refresh pathway or in some if statement in the main loop

**Comment by wen-coding** [comment]
After chatting with Ashwin, figured out the worst case isn't too bad. If for whatever reason we chose the wrong slot, it will only push one slot to the tower, so the total lockout is 2. Next time when we are in this loop, condition 2 won't be true for 30 seconds, so we do have a chance in next round to go to the main path and switch to the correct fork if possible.

I'll put the code in the vote refresh part with less restrictive condition to make the code simple.
