### ISSUE TITLE
[Bug] withdraw_nonce_account is advancing nonce 

### ISSUE THREAD

**Issue by kingsframe** [solana-labs/solana#27832]
#### Problem
When I create a durable transaction with advance nonce, transfer, and withdraw nonce, it fails with error. 

```
 let tx = new Transaction().add(
            // nonce advance must be the first insturction
            SystemProgram.nonceAdvance({
              noncePubkey: nonceAccountKeypair.publicKey,
              authorizedPubkey: wallet.publicKey,
            }),
            // after that, you do what you really want to do, here we append a transfer instruction as an example.
            SystemProgram.transfer({
                fromPubkey: wallet.publicKey,
                toPubkey: destAddress,
                lamports: amount,
            }),
            SystemProgram.nonceWithdraw({
                authorizedPubkey: wallet.publicKey,
                lamports: accountInfo!.lamports,
                noncePubkey: nonceAccountKeypair.publicKey,
                toPubkey: wallet.publicKey,
            }),
        );
```

I get this error 
```
> Withdraw nonce account: nonce can only advance once per slot
> Program returned error: "custom program error: 0x7"
```

#### Proposed Solution
I would prefer to be able to withdraw nonce in a single transaction after it has been executed. My current use case is that after a durable tx has been executed, I don't need the nonce account anymore. So I would like to recover the rent from the nonce account. Ideally this would be done in a single tx.

**Comment by jstarry** [comment]
Your use-case makes sense to me. I can't think of a good reason why a nonce shouldn't be allowed to be advanced and withdrawn in the same block. The important thing is that nonces can't be _created_ and advanced in the same block, because otherwise you could create > advance (tx 0) > withdraw > create > advance (tx 0) and process the same tx twice in the same block.

**Comment by steveluscher** [comment]
I guess there's two ways we could go with this.

1. Nonces can be consumed by prepending _either_ an `AdvanceNonce` _or_ a `WithdrawNonce` instruction
    * Would have to add the invariant that a nonce can neither be withdrawn nor advanced in the same block in which it's created
2. Allow nonce accounts to be withdrawn from in the same block in which they're advanced

**Comment by phoenixeliot** [comment]
Just chiming in to say I would like this too. I create one nonce per [thing] and then close out the nonce account once the transaction goes through; this setup is to make the transactions preparable ahead of time and still idempotent. But I don't want to be slowly bleeding sol to rent fees on nonce accounts. I can just close the nonce account after this transaction but it's not ideal because that's more state to track to make sure it happens, if solana is being flaky.

**Comment by rockooor** [comment]
+1 this for the reasons explained above

**Comment by jimmdd** [comment]
+1
