### ISSUE TITLE
Add a way to estimated cost for programs (ExecuteCostTable) from and RPC node

### ISSUE THREAD

**Issue by godmodegalactus** [solana-labs/solana#28269]
As a ongoing development to analyze performance issues and see check easily the cost in the execute cost table for a program. 
I would like to add a method in the class `JsonRpcRequestProcessor` which returns a json having all the entries of the table `ExecuteCostTable` for `CostModel`.

May be we can two methods one which entry in cost table for a specific program and another for all the entries.

This methods then can be integrated with existing solana cli.

**Comment by godmodegalactus** [comment]
I will look into this issue, please comment your thoughts.

**Comment by mschneider** [comment]
fyi @taozhu-chicago

**Comment by taozhu-chicago** [comment]
if issue #27608 is going to happen, is adding a rpc endpoint still necessary?

For short term analyze, if possible to run non-staked validator in mainnet-beta, perhaps can print results of `ExecuteCostTable` lookup to log file, since `replay_stage` calls cost_model.calculate_cost() [here](https://github.com/solana-labs/solana/blob/master/ledger/src/blockstore_processor.rs#L418).

**Comment by godmodegalactus** [comment]
I think it could still be interesting to have this feature. We can easily request any RPC server or a validator what is the instruction cost at a given instance.
Log files are easy to debug or understand problems like exceptions or errors etc. But for me they are not suited to get performance metrics. Each rpc / validator has its own view for estimated cost, network does not have same values for these costs.
