### ISSUE TITLE
Validate transaction account locks earlier

### ISSUE THREAD

**Issue by taozhu-chicago** [solana-labs/solana#28293]
#### Problem

banking_stage validates transaction's account locks (by `get_account_locks()`) at late stage during bank loading accounts. It can be moved up earlier, so banking stage doesn't need to process transactions would failed on loading accounts.

#### Proposed Solution
- make `get_account_locks` part of transaction's sanitization

**Comment by apfitzge** [comment]
Should these PRs be backported to 1.13 & 1.14?
I'd definitely lean towards yes, but open for discussion here

**Comment by taozhu-chicago** [comment]
> Should these PRs be backported to 1.13 & 1.14?

@t-nelson @sakridge wdyt ^^^

**Comment by apfitzge** [comment]
Created an alternate PR to #28297 since it felt like a fairly intrusive change, in that it prevents us from created SanitizedTransaction that we could have previously created. https://github.com/solana-labs/solana/pull/28303 moves the initial lock check just to where we use it for banking when we insert into the unprocessed storage. That approach makes me less worried that I broke something in the sdk.

Any thoughts on these different approaches @taozhu-chicago / @jstarry ?

**Comment by taozhu-chicago** [comment]
Agree the alternative PR is safer, but feels bit too patchy. Still prefer checking account locks when creating `SanitizedTransaction`, if can't make it part of `sanitize` trait yet. It's going to need a feature gate anyway, is it?

**Comment by apfitzge** [comment]
> Agree the alternative PR is safer, but feels bit too patchy. Still prefer checking account locks when creating `SanitizedTransaction`, if can't make it part of `sanitize` trait yet. It's going to need a feature gate anyway, is it?

thoughts on how we can make it less patchy?

Agree that I prefer it either in `sanitize` or in the constructors of `SanitizedTransaction`. I think that will have to be feature-gated though:
* unpatched leader could include SanitizedTransaction that now fail to pass checks in patched creation
* patched node gets tx from leader, fails replay because it cannot create SanitizedTransaction

Alternate PR doesn't need to feature-gated I think:
* unpatched leader could include SanitizedTransaction that now fail to pass checks in patched creation
* patched node gets tx from leader, can still create SanitizedTransaction because we've not changed the construction for replay
* patched leader just won't include those Tx

I'm not entirely sure how we'd ever get that initial point though "unpatched leader could include SanitizedTransaction that now fail to pass checks in patched creation"? These tx fail checks, so wouldn't make it into a block regardless of the patch right?

**Comment by t-nelson** [comment]
I'm reworking `Sanitize` to better support gating ATM, 'cause I need it for something else.  Will toss y'all on review once it's ready
