### ISSUE TITLE
"spl-token accounts" command does not work

### ISSUE THREAD

**Issue by injaan** [solana-labs/solana#28320]
Command returned "HTTP status client error (429 Too Many Requests) for url (https://api.mainnet-beta.solana.com/)" message after few seconds later

**Comment by hspy** [comment]
I have same issue with  url (https://api.mainnet-beta.solana.com/), my toolkit release version is mainnet v1.10.41

**Comment by joncinque** [comment]
Hi there, thanks for reaching out -- this issue belongs in the solana-program-library repo: https://github.com/solana-labs/solana-program-library, so could you add it there?

Very quickly, I'm surprised that this is giving a 429 since it's just doing one call to `getTokenAccountsByOwner`.  You might simply need to use a different endpoint unfortunately.

**Comment by injaan** [comment]
@joncinque Ok thank you
