### ISSUE TITLE
cargo run poh-bench fails to detect AVX2/AVX512F

### ISSUE THREAD

**Issue by ripatel-jump** [solana-labs/solana#28551]
#### Problem

When building and running `solana-poh-bench` locally on a machine with AVX512F support, the binary fails to test the `cpu_simd_avx2` and `cpu_simd_avx512f` code paths.

```
$ cargo version
cargo 1.64.0 (387270bc7 2022-09-16)
$ cargo build --release --package solana-poh-bench
    Finished release [optimized] target(s) in 0.33s
$ ./target/release/solana-poh-bench --num-threads 1
64,cpu_generic,27772

$ grep avx512f /proc/cpuinfo | wc -l
16
$ ./target/release/solana-poh-bench --num-threads 1
64,cpu_generic,27837

$ 
```

#### Proposed Solution

Fix x86 SIMD detection and run `cpu_simd_avx2` and `cpu_simd_avx512` bench too.

**Comment by ripatel-jump** [comment]
Nevermind, my perf-libs were missing.

**Comment by KirillLykov** [comment]
I confirm that it works for me -- I've tried on amd and intel cpus.

**Comment by ripatel-jump** [comment]
Odd -- I still cannot get AVX2/AVX512F to run even with locally-built perf-libs. But if it works for others, must be on my end.

**Comment by KirillLykov** [comment]
> Odd -- I still cannot get AVX2/AVX512F to run even with locally-built perf-libs. But if it works for others, must be on my end.

I should say that I've tried with solana built from master as of today. ubuntu 20.04

**Comment by billythedummy** [comment]
Am running on v1.13.5. Think theres a bug / documentation inconsistency in `perf/src/perf_libs::locate_perf_libs()`. Running `solana-poh-bench` with `RUST_LOG=info TEST_PERF_LIBS=1` shows the following warning

```
WARN  solana_perf::perf_libs] "/path/to/solana/target/debug/perf-libs" does not exist
```

Probably because `exe.parent()` in `let perf_libs = exe.parent().unwrap().join("perf-libs");` on line 102 returns `target/debug/` instead of `target/`, which is what the README on `solana-perf-libs` documents

Solution for me was to create a new folder `target/debug/perf-libs` and move `libpoh-simd.so` into there instead
