### ISSUE TITLE
Revisit block CU limits

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#28604]
#### Problem

Banking stage has added 2 new threads. Should the block size increase to account for that change.

#### Proposed Solution

Take a look at replay stage timing with larger block sizes to see if there is enough margin to increase it. How often we are hitting the block size limits today?

**Comment by nikhayes** [comment]
Would be great to see these metrics on the public validator grafana. It is currently shown in a private grafana instance (might belong to Labs).

The graph looks like the one shown below 
![unknown-39](https://user-images.githubusercontent.com/63567985/198158843-2efe813a-37c5-4efe-9346-cc5ca2613863.png)

SolanaCompass also posted some data in mb validators that indicates skip rate decreases as of late that appear to correlate with compute per block decreasing (mainly due to lower mango activity recently).

**Comment by taozhu-chicago** [comment]
Making a public dashboard for cost/fee stats is in the pipeline: https://github.com/solana-labs/solana/issues/26818
