### ISSUE TITLE
start signature and poh verify as soon Entry is deserializeable

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#28633]
#### Problem

Shreds are received out-of-order and so are FEC sets. There could be some time between when a consecutive set of Entry is received and any give Entry.

#### Proposed Solution

As soon as the FEC set is deserializeable into an Entry, then a thread could start PoH and signature verify of that before consecutive entries are received. This could lower verify latency and also potentially a new signal about the highest PoH chain which is seen before the bank transactions have been verified.

**Comment by behzadnouri** [comment]
Just as a note, it will be great if we can do some a/b testing with validators running on mainnet and measure the improvements. 
As an example, on a similar issue https://github.com/solana-labs/solana/issues/28634 we saw that overheads from async processing didn't actually allowed a net improvement.

Also on a 48 core machine that I have checked, we are spawning 638 threads from the validator, so we are already at 13x threads to cores ratio.

**Comment by ilya-bobyr** [comment]
I will definitely need to measure performance, in order to see if the change is an improvement.
@steviez was suggesting that this change may affect distribution of the slot processing time more, than the actual performance.

> Also on a 48 core machine that I have checked, we are spawning 638 threads from the validator, so we are already at 13x threads to cores ratio.

Not sure if I would need to add a lot more threads.
There is already a thread that is running GPU verification.
And a thread pool used by a number of operations in the verification code.

A number of thread pools, that I've seen, allocate as many threads as there are cores.
Which may contribute to the total number of threads.

**Comment by steviez** [comment]
Should we keep this one open @ilya-bobyr ? The last message in the linked commit would indicate there was some testing to be done that you never got around to
