### ISSUE TITLE
passing minContextSlot value in getTokenAccountsByOwner, but it’s always return same result

### ISSUE THREAD

**Issue by UMANGAWASTHY** [solana-labs/solana#28718]
Hello Solana Team, 

I am passing minContextSlot value in getTokenAccountsByOwner, but it’s always return same result.
 Here is my curl query
curl --location --request POST 'https://solana-api.projectserum.com' \  --header 'Content-Type: application/json' \ --data-raw '
  {  "jsonrpc": "2.0",  "id": 1, "method": "getTokenAccountsByOwner",  "params": [ "5Xm6nU1Bi6UewCrhJQFk1CAV97ZJaRiFw4tFNhUbXy3u", { "mint": "ETAtLmCmsoiEEKfNrHKJ2kYy3MoABhU6NQvpSfij5tDs" }, { "encoding": "jsonParsed" }, { "minContextSlot":"1587" } ] }'

API document url - https://docs.solana.com/developing/clients/jsonrpc-api

**Comment by CriesofCarrots** [comment]
Hi @UMANGAWASTHY . That parameter guarantees that the result is from a slot greater than or equal to the value passed. Otherwise, you will receive an error. With a slot value so far in the past, any current block will meet the criteria.
I'm closing this, since there's no bug here. But if you need more support in using this parameter, please ask on Solana Stack Exchange https://solana.stackexchange.com/

**Comment by UMANGAWASTHY** [comment]
Hi @CriesofCarrots. do we have chanse to pass blockno in query, so i can get token account balance up to that particular block height.
