### ISSUE TITLE
Intermittent CI failure with snapshot storage rebuilder

### ISSUE THREAD

**Issue by brooksprumo** [solana-labs/solana#29053]
#### Problem

Some snapshot test in `core/tests/snapshots.rs` is failing intermittently on the snapshot storage rebuilder:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', runtime/src/snapshot_utils/snapshot_storage_rebuilder.rs:234:57
```
Full log:
https://buildkite.com/solana-labs/solana/builds/85862#0184d482-5bf9-4e3c-8df3-e0ae55cb7fbc

#### Proposed Solution

Debug and fix.

**Comment by apfitzge** [comment]
Hard to tell from the logs provided, but I have an idea what may be happening.

Rebuilder threads are spawned and just open and process paths that are sent to them. In this case, the path sent did not exist and we fail on an unwrap.
If we have a temporary append-vec file that's sent to the rebuilder threads, and that temporary file goes out of scope, then that file no longer exists.

Tests may still fail, but I'm going to fix the unwrap so that we don't fail this way and get more information on what's failing.

**Comment by apfitzge** [comment]
@brooksprumo FYI
Happen to see this failure: https://buildkite.com/solana-labs/solana/builds/86460#0185073f-1d22-42c1-9124-023ff5dbf452

Fails with asserts on "sender should be connected". Which means our main (recving) thread is exitting in the test before our workers finish.

**Comment by apfitzge** [comment]
#29219 has a description of what was causing these tests to fail.
