### ISSUE TITLE
Add new counters to fee-market dashboard

### ISSUE THREAD

**Issue by taozhu-chicago** [solana-labs/solana#29331]
#### Problem

Would like to add following panels to [fee-market](https://metrics.solana.com:3000/d/0n54roOVz/fee-market?orgId=1) dashboard, source `block_prioritization_fee`
1. Panel displays both `min_prioritization_fee` and `max_prioritization_fee`, to provide a visual of min/max fee spread of prioritized transactions. And, if possible, overlay `ratio = max_prioritization_fee /min_prioritization_fee`
3. Panel displays staked bars for `prioritized_transactions_count` and `non_ prioritized_transactions_count`

#### Proposed Solution
Once #29330 landed to Mainnet-beta, add these counters to dashboard

**Comment by overclock-validator** [comment]
I kinda wonder what the best measure would be for the local feemarket-ness level would be. I guess what would be indicative is if one of the more contended accounts has a high min priority relative to fees outside of that contended account. Maybe you could do some ratio of min priority of most highly accessed account vs base fee (or min priority fee outside of contended account). I think it's good to figure out some measurements to detect the level of local vs global fee market changes. You should be able to see a change in such a metric for example when decreasing account compute limits because it would increase local contention/congestion which should lead to a stronger local fee market.
