### ISSUE TITLE
test_run_test_load_program_accounts_partition_root is flaky

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/solana#29602]
#### Problem
`test_run_test_load_program_accounts_partition_root` fails intermittently in CI, eg:
https://buildkite.com/solana-labs/solana/builds/87841#01859845-13c5-400a-9d0c-a1599f932a64

@carllin , looks like this is your test, though flakiness may be new.

#### Proposed Solution
Figure out why and fix

**Comment by brennanwatt** [comment]
Looks like we encountered the following error performing an async transfer of lamports:
`Custom("\"WriteError(ConnectionLost(ApplicationClosed(ApplicationClose { error_code: 4, reason: b\\\"too_many\\\" })))\"")'`

This error (`CONNECTION_CLOSE_REASON_TOO_MANY`) gets returned when we're trying to add a connection that would cause us to exceed the max connections per peer.

On my bench, I see that I am sometimes exceeding the connection limit (9 connections when max is 8), but the test is still passing the majority of the time in these cases. Only occasionally does the closed connection actually lead to the async transfer failing

**Comment by brennanwatt** [comment]
The main issue here is related to the fact that almost all the connections look like they're coming from the same entity (localhost) and thus count against the same `MAX_QUIC_CONNECTIONS_PER_PEER` threshold. This includes all of the clients, but it actually also includes the validator connecting to itself as part of warming up the quic connection cache for anticipated sends to leader

Looking to explore 2 things that would help resolve this issue:

1. Constrain the TPU connection pool size so we don't open up so many parallel connections.
2. Investigate if we should be including our own validator's stake when determining priority of staked connections. This is somewhat orthogonal to this issue, but it would actually help because the connection would be seen as coming from the validator's Pubkey instead of localhost IP (which means a separate table row and different threshold it counts against)

**Comment by bw-solana** [comment]
Closing as fixed by #29831
