### ISSUE TITLE
QUIC cache warm up service should not contact the validator itself

### ISSUE THREAD

**Issue by dovahcrow** [solana-labs/solana#29767]
#### Problem

We had a QUIC warm-up service https://github.com/solana-labs/solana/blob/master/core/src/warm_quic_cache_service.rs#L34 that contacts each leader before their schedule. However, this service also tries to contact the node itself.

#### Proposed Solution
add a check 
```rust
if cluster_info.id() == leader_pubkey {
    continue;
}
```
in the while loop.

**Comment by t-nelson** [comment]
cc/ @lijunwangs @ryleung-solana

**Comment by lijunwangs** [comment]
Will look into it. The funny thing is we are also sending Tx (forwarding) to the node itself so this warming probably is also "useful"

**Comment by dovahcrow** [comment]
> Will look into it. The funny thing is we are also sending Tx (forwarding) to the node itself so this warming probably is also "useful"

Yeah this is also something I'm thinking. First, shall we forward to itself? Second, the QUIC handshake time to the node itself will be super fast (packets sent through loopback), and warming up seems unnecessary.

**Comment by brennanwatt** [comment]
#29838 is somewhat related to this. We try and warm up the connection to ourself, but our own node doesn't exist in the stake table, so the connection gets treated/prioritized as unstaked.

I don't suspect either of these (the issue I linked, and warming/not warming up connection to our own TPU port) are a big deal in reality because of how quickly we should be able to send packets to ourselves through loopback, but probably better to keep the paths the same for connecting to our own node vs. other nodes to reduce chances of obscure bugs/performance issues.

I vote for keeping this code as is (warm up QUIC connection to our own TPU port)

**Comment by lijunwangs** [comment]
Closing, no incentive to do special handling for the local address
