### ISSUE TITLE
Speed up test_duplicate_shreds_broadcast_leader

### ISSUE THREAD

**Issue by AshwinSekar** [solana-labs/solana#29917]
#### Problem

Voting thread is slow and sometimes causes it to take longer than 180s to observe the required 16 roots [e.g](https://buildkite.com/solana-labs/solana/builds/88880#0185ea17-6827-4d97-bd78-e26b1e017d69)
#### Proposed Solution
Investigate slowness and improve

**Comment by bw-solana** [comment]
There seems to be variability in number of slots it takes to get 16 new roots. In one case, I'm seeing it only takes 162 slots and thus the test takes 79.5 seconds. In another case, it takes 422 slots and thus 189.25 seconds. TBD what exactly is driving this difference

**Comment by bw-solana** [comment]
I think I understand what's driving the variability...

The goal here is to root 16 slots. We need to fill the tower in order to root slots. Thus, we need to add confirmed slots faster than we're popping them off the tower.

They can get popped off if the new slot we're attempting to add is `> existing slots + 2^confirmations`.

This happens frequently because we are skipping a lot of leader slots. The leader schedule includes many slots for the "gossip voting node" which all get skipped. Because of this, there are big gaps in slots, then we try and add new nodes and pop a bunch of nodes off.

Fortunately, there are basically just these 2 nodes jockeying for leader slots, so we usually get lucky and get a bunch of leader slots consecutively and get enough confirmations that it's tough to pop off votes from the tower.

The cases where we don't get lucky, we pop votes off like crazy and it takes a lot of slots to eventually root 16 slots.

**Comment by AshwinSekar** [comment]
Nice find! Looks like we can use `validator_config.fixed_leader_schedule` to remove the spy from the leader schedule to mitigate it
