### ISSUE TITLE
Writing Custom Transactions 

### ISSUE THREAD

**Issue by rigelrozanski** [solana-labs/solana#306]
Is there a way to write custom application transactions on top of the solana? Couldn't figure this out from the README.md docs - from a longterm perspective is solana planning on supporting custom blockchain development or more smart contract languages?

**Comment by garious** [comment]
Here's your entry point:
https://github.com/solana-labs/solana/blob/v0.6.0/src/transaction.rs#L15

To do custom transactions, you add a custom EDSL, such as this one:
https://github.com/solana-labs/solana/blob/master/src/budget.rs

That implements this interface:
https://github.com/solana-labs/solana/blob/v0.6.0/src/payment_plan.rs

Here's a ticket to track implementing that interface with general purpose programming language Lua:
https://github.com/solana-labs/solana/issues/157

That interface is very much pre-1.0. Expect it to be generalized quite a bit and include additional methods for the network to ask the contract about data dependencies so that they can be executed concurrently.

Give it a go. I'd gladly support your efforts.
