### ISSUE TITLE
Replace deprecated crate jsonrpc with newer jsonrpsee 

### ISSUE THREAD

**Issue by godmodegalactus** [solana-labs/solana#30911]
#### Problem

JSON RPC crate in rust by parity tech is a deprecated crate and is replaced by a new jsonrpsee crate by them.
We want to replace this deprecated crate used in Solana mono repo with the newer crate. We want to replace both rpc calls and pubsub calls.

Deprecated crate:  [https://github.com/paritytech/jsonrpc](https://github.com/paritytech/jsonrpc)
Replacement crate: [https://github.com/paritytech/jsonrpsee](https://github.com/paritytech/jsonrpsee)

Moving to a newer crate, we will quickly help Solana get all the latest developments, bug fixes, and performance improvements for the json rpc module. Json rpc is an essential module all clients use to interact with the Solana cluster. Any improvement in this crate will make interaction with the cluster more fluid. Jsonrpsee has more advanced async implementation and easier macros.

#### Proposed Solution

Start replacing jsonrpc crate with jsonrpsee crate in the rust library and solve all its dependencies. Usually, these libraries are structured similarly around macros, so we expect some changes. Still, we can reuse most existing code with method signature and traits changes. More changes might be involved around replacing the pub-sub part of the code. Currently, Pubsub is implemented by the mixture of sockettio/tokio socket and jsonrpc. Jsonrpsee has its implementation for pub-sub module. We would also like to replace the current implementation of pub-sub module with jsonrpsee pub-sub.

Once we have replaced the jsonrpc with jsonrpsee, we can run the Solana unit test to check if they are working as expected. Then we can run mango simulation tests to test if the getSlot, getBlocks, getBlock, and subscriptions to the account changes are working as expected. As jsonrpc is a core feature which every Solana client uses, performance deterioration or bugs will be detected relatively quickly in devnet and testnet.

**Comment by godmodegalactus** [comment]
I have identified that we will have to use jsonrpsee version 0.11.0 instead of 0.16.2 because of tokio. We can wait for solana to move to newer tokio version minimum 1.16.

I guess we can wait till the upgrade of tokio is done.

**Comment by aniketfuryrocks** [comment]
I am working on this

**Comment by steveluscher** [comment]
Dead serious suggestion: **what if we wrote our own**?

The JSON-RPC [specification](https://www.jsonrpc.org/specification) is dead simple. I was able to write a zero-dependency [JSON-RPC client](https://github.com/solana-labs/solana-web3.js/tree/master/packages/rpc-transport/src/transports/http) in the new web3.js in less than a day. I bet that we could write a zero-dependency JSON-RPC _server_ in under a week!

### Why?

* We _already_ know how to handle HTTP requests
* We _already_ know how to parallelize method calls internally
* We _already_ know how to serialize values as JSON strings

Those are _all_ the tools we need to build our own JSON-RPC server.

### Pros

* No barriers to making changes because of dependency lock-in (eg. we wouldn't _have_ to upgrade `tokio` to upgrade the RPC – #24644)
* We can use the _best in class_ HTTP server (ie. one that supports HTTP/2) without worrying about what the JSON-RPC crate-du-jour supports
* We can make fine-grained optimizations that make sense for us (ie. we could disable batching in the future)
* Fewer crate dependencies!

cc/ @tyera for thoughts.
cc/ @linuskendall because I mentioned batching and HTTP/2.

**Comment by mschneider** [comment]
love the idea, we could also drop tokio 😁

**Comment by mschneider** [comment]
make or break would be to know how much tooling has been built around tokio already, especially related to tracking task queue and scheduler issues. if we need to retrofit an existing monitoring pipeline, that could easily make this a very expensive decision.
