### ISSUE TITLE
JSON RPC returns corrupt `id` value in JSON RPC response

### ISSUE THREAD

**Issue by petrucioinica99** [solana-labs/solana#31158]
## Overview
Calling the Connection.getAccountInfo function throws an error because the RPC returns a badly formatted JSON.
I have encountered this bug while trying to load a serum market. It used to work properly but all of a sudden it was throwing an error while trying to get the market account info. 

## Steps to reproduce
1. create a connection to the solana mainnet
```
const connection = await new Connection("https://solana-mainnet.rpc.extrnode.com/");
```
2.  try to use the getAccountInfo with the following address:
````
 const accInfo = await connection.getAccountInfo(
    new PublicKey("ArqoQnUYNWuc6XQwdyZy1TTrrAzGhKvhfB3tGAtL3kSh")
  );
````
3. The function should throw an error: 
````
Error: failed to get info about account ArqoQnUYNWuc6XQwdyZy1TTrrAzGhKvhfB3tGAtL3kSh: SyntaxError: Expected ',' or '}' after property value in JSON at position 603
````

If you open the network tab and look at the endpoints made to the solana RPC, you will see that one of them returns the following JSON:
`````
{
    "jsonrpc": "2.0",
    "result": {
        "context": {
            "apiVersion": "1.15.0",
            "slot": 187789813
        },
        "value": {
            "data": [
                "AQAAAAAAAABYFJAGT8g8lsVLaNKeVw7mPlE8Dyue9Jn114BZxXv5tMb6evO+2606PWXzaqvJdDGxu+TC0vbg5HymAgNFL11hr/lvt9zLKR2tb9UnqCQq+P/hYDwB3UAnHivCEBj1UTOR0hguoQYM7ktKQuDh1ZWdGuKN7VUkAUWrkepVTHOZR3ArUfHOA1tRfwMNpDAEfYTOmtG07zSFm1Gxoaok4rU1Dmy/vPwpFD064syo/70mkLoYE33hlYE30ocIlmFyYgrkvgBkAAAAAHUAAAAAAAAAIN5BBgAAAACKogAAAAAAAAEAAAAAAAAA6AMAAAAAAABA0J4AAAAAAAEAAAAAAAAAECcAAAAAAAD+AAAAAAAAAA==",
                "base64"
            ],
            "executable": false,
            "lamports": 2839680,
            "owner": "94nRXYTWa5fwAF8pZze6p6qczqZ9sqaTcu72EeSty3xy",
            "rentEpoch": 0
        }
    },
    "id": 836 b393f-b18a-4 fad-aeb4-16 bbabb1c492
}
`````
Notice how the id (last field in the json) does not have the value as a string, the quotation marks are missing.

## Description of bug
The Connection.getAccountInfo function does not work, instead throwing the following error:
````
Error: failed to get info about account ArqoQnUYNWuc6XQwdyZy1TTrrAzGhKvhfB3tGAtL3kSh: SyntaxError: Expected ',' or '}' after property value in JSON at position 603
````
This might occur while being used by other packages, for example my case was the @bonfida/dex-v4 package.

**Comment by steveluscher** [comment]
Here are the things I know:

* RPC `v1.15.0` responded to this request
* The `@solana/web3.js` library uses uuidv4 ids as the `id` in JSON RPC messages.
* This server (`https://solana-mainnet.rpc.extrnode.com`) appears to have responded by spitting a uuidv4 `id` string out, without wrapping it in double quotes. This fails to parse as JSON and crashes the client.

**Comment by steveluscher** [comment]
@CriesofCarrots, do you have any ideas here? Is this just a bug that snuck into 1.15 that's irrelevant now that 1.15 has been abandoned?

**Comment by CriesofCarrots** [comment]
I can't reproduce this error on a local validator, foundation RPC pool, or actually solana-mainnet.rpc.extrnode.com
Submitting a request with a uuidv4 string returns with a correct id string. Submitting a request with a uuidv4 without quotes correctly returns a parsing error.

The [jsonrpc library](https://github.com/paritytech/jsonrpc) we use accepts string or uint ids, and just copies them back in the response. I am pretty certain that we (and Parity) would have seen issues before now if there was some sort of intermittent incorrect typecasting going on in that library. Meanwhile, our `solana-rpc` service code doesn't interact with the id field directly at all.

My best guess is an issue on Everstake's side, perhaps a misconfigured proxy. It's a bummer that it didn't reproduce for me when I queried their endpoint. But perhaps they have fixed it since the issue appeared.

If this exhibits again, I think we need to see the actual Request data to investigate much further.

**Comment by petrucioinica99** [comment]
For me it keeps happening, here is the request payload, I hope it helps
````
{
  "method": "getAccountInfo",
  "jsonrpc": "2.0",
  "params": [
    "ArqoQnUYNWuc6XQwdyZy1TTrrAzGhKvhfB3tGAtL3kSh",
    { "encoding": "base64" }
  ],
  "id": "57a6598a-2943-4125-83ce-ee2a153c0fc8"
}
````
But it does indeed only happen on extrnode

**Comment by CriesofCarrots** [comment]
Everstake told me via slack that this was an issue in their backend, and that it has been fixed.
Therefore, I'm closing this issue. If it reproduces again, please contact Everstake directly.
