### ISSUE TITLE
Unexplained segfault during upgrade to 1.13.7

### ISSUE THREAD

**Issue by michaelh-laine** [solana-labs/solana#31164]
#### Problem
Was running jito-solana 1.13.5 uninterrupted since last restart. Hardware is an Equinix server in Frankfurt with an Epyc 7502p with 8 cores disabled and 256G RAM. Swap is enabled with 225G.

While attempting to upgrade to jito-solana 1.13.7 (compiled on another machine with a similar processor (Epyc 7443) after completing the loading of the ledger the validator restarted. The logs exhibited no related panic or assert (an unrelated panic was discovered which was triggered by the admin_rpc exit command and is a bug in the jito code triggered during shutdown, this was shared with the jito team and was mistakenly first assumed to be related).

The restart happens with an existing rocksdb and shortly after the "Validator initialized" log entry. A second restart attempt resulted in the same behaviour. Thereafter I rolled back to 1.13.5 after deleting the rocksdb folder and getting new snapshots, therefore it is unclear if the same behaviour may have persisted on 1.13.5 with rocksdb intact (one suggestion from the jito team is a blockstore related issue).

RocksDB shred compaction mode is set to FIFO. Issue was discussed with @steviez in DM, recording here for his further review.

Start args:
```
--identity [path/to/identity/keypair] \
        --vote-account GE6atKoWiQ2pt3zL7N13pjNHjdLVys8LinG8qeJLcAiL \
        --authorized-voter [path/to/identity/keypair] \
        --rpc-port 8099 \
        --entrypoint 184.105.146.35:8000 \
        --entrypoint se1.laine.co.za:8001 \
        --entrypoint entrypoint2.mainnet-beta.solana.com:8001 \
        --entrypoint entrypoint3.mainnet-beta.solana.com:8001 \
        --entrypoint entrypoint4.mainnet-beta.solana.com:8001 \
        --log /home/solana/solana-validator.log \
        --ledger /mnt/ledger \
        --accounts /mnt/validator/accounts \
        --dynamic-port-range 8001-8050 \
        --no-port-check \
        --private-rpc \
        --rpc-bind-address 0.0.0.0 \
        --tower  /mnt/validator/tower \
        --snapshots /mnt/validator/snapshots \
        --no-check-vote-account \
        --expected-shred-version 56177 \
        --known-validator PUmpKiNnSVAZ3w4KaFX6jKSjXUNHFShGkXbERo54xjb \
        --known-validator SerGoB2ZUyi9A1uBFTRpGxxaaMtrFwbwBpRytHefSWZ \
        --known-validator FLVgaCPvSGFguumN9ao188izB4K4rxSWzkHneQMtkwQJ \
        --known-validator qZMH9GWnnBkx7aM1h98iKSv2Lz5N78nwNSocAxDQrbP \
        --known-validator GiYSnFRrXrmkJMC54A1j3K4xT6ZMfx1NSThEe5X2WpDe \
        --only-known-rpc \
        --limit-ledger-size \
        --wal-recovery-mode skip_any_corrupted_record \
        --incremental-snapshots \
        --no-snapshot-fetch \
        --no-genesis-fetch \
        --contact-debug-interval 1000000 \
        --minimal-snapshot-download-speed 30000000 \
        --rocksdb-shred-compaction fifo \
        --tip-payment-program-pubkey T1pyyaTNZsKv2WcRAB8oVnk93mLJw2XzjtVYqCsaHqt \
        --tip-distribution-program-pubkey 4R3gSG8BpU4t19KYj8CfnbtRpnT8gtk4dvTHxVRwc2r7 \
        --merkle-root-upload-authority GZctHpWXmsZC1YHACTGGcHhYxjdRqQvTpYkb9LMvxDib \
        --commission-bps 750 \
        --relayer-auth-service-address http://relayer-1.mainnet.frankfurt.jito.wtf:8100 \
        --relayer-address http://relayer-1.mainnet.frankfurt.jito.wtf:8100 \
        --block-engine-address https://block-engine.mainnet.frankfurt.jito.wtf:1003 \
        --block-engine-auth-service-address https://block-engine.mainnet.frankfurt.jito.wtf:1005 \
        --tip-distribution-account-payer [path/to/identity/keypair] \
        --shred-receiver-address 145.40.93.84:1002 \
```

Entries in dmesg:
```
[Tue Apr 11 08:40:12 2023] traps: solana-window-i[738739] trap invalid opcode ip:55bcf9ab26d7 sp:7efbfda3a4b8 error:0 in solana-validator[55bcf8be6000+1f0a000]
[Tue Apr 11 09:01:37 2023] traps: solana-window-i[746620] trap invalid opcode ip:56198e6e66d7 sp:7ed023c514b8 error:0 in solana-validator[56198d81a000+1f0a000]
```
Logs for 08:00 - 08:59 and 09:00 - 09:59 below:
https://laine.one/jito-0800-0859.log
https://laine.one/jito-0900-0959.log

**Comment by michaelh-laine** [comment]
Tried again this morning after deleting rocksdb, the issue persisted. Then tried 1.13.6 and still hit the segfault

**Comment by steviez** [comment]
I noticed the following in your logs:
```
// Restart
[2023-04-11T08:30:07.708197239Z INFO  solana_validator] solana-validator 1.13.7 (src:devbuild; feat:1775889670)
[2023-04-11T08:30:07.708224120Z INFO  solana_validator] Starting validator with: ArgsOs {

// Finish replay of local ledger
[2023-04-11T08:46:21.516886589Z INFO  solana_ledger::blockstore_processor] ledger processed in 9 minutes, ...
...
[2023-04-11T08:46:21.585701326Z INFO  solana_core::validator] Starting validator with working bank slot 187781852
```
The reason this is peculiar is because `WindowService` is created by `RetransmitStage` here:
https://github.com/solana-labs/solana/blob/616d8d67978c325087cc5a9f33307f54eee48b6e/core/src/retransmit_stage.rs#L447
which is created by `Tvu` here:
https://github.com/solana-labs/solana/blob/616d8d67978c325087cc5a9f33307f54eee48b6e/core/src/tvu.rs#L205
which is created by `Validator` here:
https://github.com/solana-labs/solana/blob/616d8d67978c325087cc5a9f33307f54eee48b6e/core/src/validator.rs#L907

So, `WindowService` won't be created until `Tvu` is created by `Validator` on line 907. However, the `Starting validator with working bank slot` log line from above is emitted on line 579 here:
https://github.com/solana-labs/solana/blob/616d8d67978c325087cc5a9f33307f54eee48b6e/core/src/validator.rs#L579

Looking at timestamps, the `Starting validator with working bank slot` was emitted at 08:46 whereas the segfault was reported at 08:40. But, based on the order of operations I illustrated above, `WindowService` wouldn't have been started up again until after 08:46. So, I am pretty puzzled how a `WindowService` thread could have segfaulted before it would have been spawned.

Is there anything "unusual" with how you restart `solana-validator` process on your machine / what is your typical workflow? Do you wait to ensure that the old process has completely stopped before beginning the new one?

Given that the segfault was ~10 minutes after your process restart, it seems unlikely to me that the old process would have lingered that long. But, then again, the lines of code show `WindowService` wouldn't have been running in new process yet so something strange is going on here

**Comment by michaelh-laine** [comment]
The validator start was at around 08:30, so yeah the ledger loading took around 16 minutes, which I guess is spent in purging/cleaning ledger? Nothing unusual about the restart, `solana-validator exit -m`

**Comment by steviez** [comment]
> The validator start was at around 08:30, so yeah the ledger loading took around 16 minutes, which I guess is spent in purging/cleaning ledger?

Yeah, unpacking snapshots / generating index / replaying slots that you already had past the most recent snapshot.

**Comment by steviez** [comment]
I have since found out that system time and dmesg time can deviate, so that could explain the dmesg / system log timestamps not aligning well:
https://serverfault.com/questions/576139/dmesg-time-vs-system-time-time-isnt-correct

**Comment by michaelh-laine** [comment]
The issue was resolved by compiling the validator binaries on the same machine that was running them. This was never previously an issue.

Validator machine: AMD EPYC 7502P 32-Core Processor (24 cores active)
Build machine: AMD EPYC 9224 24-Core Processor

The build machine is running a newer generation Epyc which seems to have created an incompatible binary.
