### ISSUE TITLE
Third party wallet integration

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#313]
What client API do we need to expose for third parties to most easily integrate with Solana?

**Comment by jroelofs** [comment]
I recommend building out a way to spin up a full node, with a service built on top that mimics Etherscan's apis, since your chain is a lot more like ETH than BTC: https://etherscan.io/apis At a bare minimum, you'll need API endponts for:
    * "What's the balance of this address?"
    * "What transactions involving this address have happened in the past?"
    * "Here's a signed transaction, please broadcast it for me"
    * "Has my transaction confirmed yet?"
    * "Are there any unconfirmed transactions in the mempool, if so what are they?" (If that even makes sense for Solana)

Try to minimize the number of libraries it depends on, and get everything statically linked (if possible). That'll make it easier for wallet vendors to spin up this service.  Design it with the idea of running it on cloud service providers like AWS in mind, i.e. make it convenient / easy to manage how the blockchain data is stored on disk, and reliable against the full node being shut down unexpectedly and then re-started. Make it easy to take snapshots of the data, and re-sync from them in new instances. Make the API endpoints thread safe, so it can serve lots of requests from lots and lots of users.

If you don't already have first-class support for multisig transactions, I *highly* recommend adding it. This is something that ETH got wrong, IMO, and makes it difficult for exchanges to integrate support safely and robustly.

You'll also need a defined way to derive private/public key pairs following: BIP32/BIP44, and to register your BIP44 coin type here: https://github.com/satoshilabs/slips/blob/master/slip-0044.md

**Comment by garious** [comment]
We now have wallet support in a few different forms. Closing this ticket, since it's not specific to any particular wallet. @jroelofs, to your comments:
* we recently added BIP32 support to `solana-keygen`
* for BIP44, we're `501` (SOL, but 1337)
* yes, limited multisig support
