### ISSUE TITLE
Consensus (bank hash) mismatch between master and v1.13/v1.14 (mnb)

### ISSUE THREAD

**Issue by steviez** [solana-labs/solana#31365]
#### Problem

On April 23, nodes running against master were observed to have diverged from mainnet. Nodes with various commits off of master forked off at slot `190061698`, and this hit this panic.
```
thread 'solReplayStage' panicked at 'We have tried to repair duplicate slot: 190061698 more than 10 times
and are unable to freeze a block with bankhash J5GobCrZZLvvj8EW72BV1Q7973TefL7f3qtqGinebCWF,
instead we have a block with bankhash Some(FqJHBuSpEXHGM5Rt5pk1hWuKQh2Wg3iyQnyiQ4kwT8NW).
This is most likely a bug in the runtime. At this point manual intervention is needed to make progress. Exiting', 
```

The incorrect bank hash and associated fields that make up the bank hash look like:
```
bank frozen: 190061698
hash: FqJHBuSpEXHGM5Rt5pk1hWuKQh2Wg3iyQnyiQ4kwT8NW
accounts_delta: nSAB5dSBaN94HF7UNT4ZwKna4rYfZKMUPLoA9ZRAHTE
signature_count: 1640 
last_blockhash: 4Nez6awxz3mqyEPPtvmBErhaUVFgCd1Us1GVsr9kFEU4
capitalization: 545940604106710686,
stats: BankHashStats {
	num_updated_accounts: 4976,
	num_removed_accounts: 21,
	num_lamports_stored: 2524779513915279,
	total_data_len: 20916547,
	num_executable_accounts: 0
}
```
whereas the correct hash produced by v1.13/v1.14 looks like:
```
bank frozen: 190061698
hash: J5GobCrZZLvvj8EW72BV1Q7973TefL7f3qtqGinebCWF
accounts_delta: qnhRzBRp4Uapif5QewsCkLaEVL2zgLAiBvMacbchn45
signature_count: 1640
last_blockhash: 4Nez6awxz3mqyEPPtvmBErhaUVFgCd1Us1GVsr9kFEU4
capitalization: 545940604106710686
accounts hash slot: 190061698
stats: BankHashStats {
	num_updated_accounts: 4984,
	num_removed_accounts: 22,
	num_lamports_stored: 2524854860183319,
	total_data_len: 23534954,
	num_executable_accounts: 1
}
```
At first glance, there is an obvious difference in some of these numbers which would point to a transaction had a different execution result between versions.

Adding some extra logging, I determined that the transaction ([explorer link here](https://explorer.solana.com/tx/6ujGsjkwWJtE3VsraD97PBrhWpJaKGVfbxQAyV5thV32NTR9HWa6PjJgqGComn8y9oXBJMc1iT1NwZRLWLm4aM8)) that executed differently between versions is:
```
6ujGsjkwWJtE3VsraD97PBrhWpJaKGVfbxQAyV5thV32NTR9HWa6PjJgqGComn8y9oXBJMc1iT1NwZRLWLm4aM8
``` 

Looking at the basic logs in explorer, the above transaction fully succeeded in v1.13 / v1.14. However, looking at the debug logs from executing with master via `solana-ledger-tool`, I see the following for this tx:
```
[...] Program ComputeBudget111111111111111111111111111111 invoke [1]
[...] Program ComputeBudget111111111111111111111111111111 success
[...] Program SMPLecH534NA9acpos4G6x7uf3LWbCAwZQE9e8ZekMu invoke [1]
[...] Program log: Instruction: ExecuteTransaction
[...] Program hvsrNC3NKbcryqDs2DocYHZ9yPKEVzdSjQG6RVtK1s8 invoke [2]
[...] Program has been closed
[...] Program hvsrNC3NKbcryqDs2DocYHZ9yPKEVzdSjQG6RVtK1s8 failed: invalid account data for instruction
[...] Program SMPLecH534NA9acpos4G6x7uf3LWbCAwZQE9e8ZekMu consumed 17573 of 1400000 compute units
[...] Program SMPLecH534NA9acpos4G6x7uf3LWbCAwZQE9e8ZekMu failed: invalid account data for instruction
...
[...] tx error: InstructionError(1, InvalidAccountData) SanitizedTransaction { ... }
```

**Comment by steviez** [comment]
I have determined that aebc191c38547d0df75319c3232965c93769694f (https://github.com/solana-labs/solana/pull/30703) introduced the breaking change:
- Running `solana-ledger-tool` with aebc191c38547d0df75319c3232965c93769694f produces the incorrect bank hash
- Running `solana-ledger-tool` with the parent commit e7887cfb0633b8188680d1521c960d9aa764208f produces the correct bank hash.

@pgarg66 @Lichtso - Can you two please look into this further given that you were the author + reviewer on this PR.

**Comment by Lichtso** [comment]
I think I got an idea what is going on:

First of all, in the TX in question, the program `hvsrNC3NKbcryqDs2DocYHZ9yPKEVzdSjQG6RVtK1s8` is first executed via CPI (meaning it is passed as an instruction account in a top level instruction) and then upgraded via CPI (meaning it is set to writable in the TX). Either of these conditions triggers the special case we added in the PR in question here: https://github.com/solana-labs/solana/commit/aebc191c38547d0df75319c3232965c93769694f#diff-a6df749724ef3698bf0b90625702f100670b58c585f91da8725f78a94b04196eR388

However, if both occur simultaneously on the same program in the same TX as it is the case here, the function `filter_executable_program_accounts()` incorrectly filters the program out here:
https://github.com/solana-labs/solana/blob/aebc191c38547d0df75319c3232965c93769694f/runtime/src/accounts.rs#L639

And it is thus the matching programdata account is **not** pre-loaded into the executor cache anymore here:
https://github.com/solana-labs/solana/blob/aebc191c38547d0df75319c3232965c93769694f/runtime/src/bank.rs#L4494

Later, in the program runtime when the program is attempting execution it is not found in the executor cache because it was never pre-loaded:
https://github.com/solana-labs/solana/blob/aebc191c38547d0df75319c3232965c93769694f/programs/bpf_loader/src/lib.rs#L184

Which leads to an incorrect fall through into `get_programdata_offset_and_deployment_offset()`, where it is finally reported as being closed:
https://github.com/solana-labs/solana/blob/aebc191c38547d0df75319c3232965c93769694f/programs/bpf_loader/src/lib.rs#L155

**Comment by jeffwashington** [comment]
I also had a machine hit this at what I think is a different slot:
```We have tried to repair duplicate slot: 190064501 more than 10 times```
