### ISSUE TITLE
Feature Gate: round down compute-unit-price to the nearest 1_000 microlamports 

### ISSUE THREAD

**Issue by tao-stones** [solana-labs/solana#31453]
#### Problem

Data from mainnet-beta shows the `compute_unit_price` is too granular, that:
1. value of `compute_unit_price` scatters from range [0, 200_000+] in rather random fashion. Ideally user should set the value based on recent blocks' and/or accounts' min priority fee (available via RPC), only only when needed;
2. priority_fee, calculated by multiplying `compute_unit_price` and `compute_unit_limit`, are too small; the side effect is user request lot more CU than what is actually needed for transaction. 

#### Proposed solution
Regulate `compute_unit_price` by rounding down to its nearest 1_000 micro-lamport. The effect is user should set `compute_unit_price` in increment of 1_000. Transaction has less then 1_000 `compute_unit_price` will have no priority nor be charged a priority fee.

Examples:
For a transaction with default 200_000 CU `compute_unit_limit`:

|set `compute_unit_price` in micro-lamports | tx currently prioritized by value | current priority fee (lamports) | round down to (1_000 microlamports) | tx WOULD BE prioritized by value: | WOULD BE priority fee |
|------------|--------------|---------------|-----------------:|-------------:|------------:|
|1 | 1 | 1 | 0 | 0 (eg: no priority) | 0 |
|999|999|200|0|0 (eg, no priority) | 0|
|1_000|1_000|200|1_000|1_000|200|
|1_999|1_999|400|1_000|1_000|200|

Proposed change needs to be feature gated because it changes actually priority fee changed to payer account. 

### Feature ID

6J6GS57v5q4CnPrLgDMsyZLFfpPEBPZ66h8efDEpesPk

### Activation Method

Single Core Contributor

### Minimum Beta Version

1.16.0

**Comment by mschneider** [comment]
hi @taozhu-chicago, i don't understand why this is a good solution:

1. value of compute_unit_price scatters from range [0, 200_000+] in rather random fashion. Ideally user should set the value based on recent blocks' and/or accounts' min priority fee (available via RPC)

Most people I know use 1-10,000 microlamports. 1,000,000+ sounds like a severe congestion case on-chain, or wallets / UIs just blindly setting a fixed value. Do you have more data? i think it's important to look more differentiated at users in segments:

<10tx/week occasional user
<100tx/week power user
<1000tx/week bot running every hour or absolute power user
<10,000 tx/week bot running every few minutes
>10,000 tx/week HFT


2. priority_fee, calculated by multiplying compute_unit_price and compute_unit_limit, are too small; the side effect is user request lot more CU than what is actually needed for transaction.

Most CLOB workloads are dependent on account state, e.g. if you order $1M of any asset on openbook you are going to match with more than 1 party, hence there's a dynamic component that is very hard to limit by a fixed number. As there's no way for programs to terminate a transaction before it hits the gas limit gracefully, people are just forced to over-estimate for the worst-case. To just increase fees without providing the actual APIs for dapps to implement solutions takes the cart before the horse.

This change as it stands would make most CLOBs unusable.

**Comment by taozhu-chicago** [comment]
Hey @mschneider, good to have your inputs. The easy one first: this doesn't aim to fix but to encourage requesting  accurate, or at least more reasonable, CU limit. I'd guess it'd take multiple approaches and much works, but eventually the requested CU limit need to be at a reasonable level. 

> i think it's important to look more differentiated at users in segments

You mean priority fee be charged at different level?

**Comment by mschneider** [comment]
i think the right scale is somewhere in between!

1 micro lamport in priority fee = e-5 SOL / week
1 lamport in priority fee = 10 SOL / week

probably e-2 is a good reference value

**Comment by taozhu-chicago** [comment]
Yea, a in-between value does sound safe / comfortable, but replacing one fraction unit with another fraction unit doesn't sound like final solution, tbh. 

I'd be arguing that 10Sol/week has more chance than 0.01Sol/week to incentivize dev digging into refine, even redesign, transactions.

**Comment by mschneider** [comment]
If the goal is to allow users to set accurate compute limits I believe the best way would be to expose the CU consumed in a sysvar. This way users can decide to stop consuming CU before reaching the limit

**Comment by mschneider** [comment]
> 
> I'd be arguing that 10Sol/week has more chance than 0.01Sol/week to incentivize dev digging into refine, even redesign, transactions.

By introducing way too large buckets you will prevent real price discovery we see the same with order and price lots on orderbooks the ideal measure of increment is $1

**Comment by mschneider** [comment]
Sample TX CU: 50,000
$E-4 in lamports: ~5000
Min increment: 0.1 lamports / CU

**Comment by mvines** [comment]
> In Pyth's case, we have an expensive aggregation operation that needs to be performed once per slot. Most price update transactions use very few CUs, except for the one that happens to trigger aggregation. However, since we can't tell up front which transactions will trigger aggregation, we have no choice but to set the CU limit conservatively (as if every transaction triggers aggregation).

Longer-term would the functionality being proposed here help with that, https://github.com/solana-foundation/solana-improvement-documents/pull/16, where the Pyth program could potentially rebate fees when the aggregation is not triggered.

**Comment by SpaceMonkeyForever** [comment]
Hey, thanks for replying!

Yes, `compute_unit_price`. I don't want to link my wallets publicly, but if you want to see example TXs, it will be easy to find my accounts if you check openbook makers (openserum.io is good).

Yes, I understand it's only used when needed, 1_000_000 is a large increment IMO still. When doing HFT, this doesn't help much because I cannot wait for my TXs to start timing out first before adding a fee. Market makers have to be quoting all the time every second or else you start losing money and you stop providing liquidity (you can still trade as a taker i.e. toxic flow which will hurt the protocol even more than pulling out liquidity).

IMHO I would rather keep it the same as it is now or increase to 1_000 increments or maybe 10_000 increments at most.

**Comment by taozhu-chicago** [comment]
if `compute_unit_price` is set to 50K - 200K microlamports, then increase its unit to 1 lamport is a x20 - x5 increase on `compute-unit-price` alone; at same time, if `compute_unit_limit` can be reduced by x3 (spot checked few txs, looks like possible), we are looking at x7 - x2 prioritization fee increase, assuming every transaction still pays prioritization fee.

Utilizing RPC (https://docs.solana.com/api/http#getrecentprioritizationfees) to determine when and how much prioritization fee might be needed before sending transactions, there are more room to further reduce overall fees.

Would be great if you can explore possibilities of reducing requested `compute_unit_limit` for transactions, and opportunities to not to _always_ set priority.

**Comment by SpaceMonkeyForever** [comment]
@taozhu-chicago 

Right, I know about the [RPC endpoint](https://twitter.com/RealSpaceMonkey/status/1614275118271991813), it's useful for UI apps for sure.
The compute limit is already set to a minimum to maximise chance of delivery and minimise the fees.

I think you are focused on the general use-case, I'm talking about a market maker use-case. The best I can do is estimate what the priority fee needed might be.

Also, it seems your overall goal is to increase the fees, which would kill all orderbook liquidity on the chain and only AMMs will remain (what Ethereum has). Aside from killing all orderbook protocols like openbook, I can go into detail on why that's a very bad idea in general, but it's better to stay on topic and we can all agree that we need orderbooks and HFT (not CEX-level but still good) on Solana, it's what makes it better than all other chains.

If you want to cut down on compute, IMHO there are 2 ideas I can think of:
- Increasing CU limit without adding a priority fee does not increase the flat fee at the moment, maybe this is something you can get rid of.
- Maybe you can decrease the default compute limit because for most of the protocols I interact with, I need a lot less than that. Some protocols like Zeta and Drift do require a high limit though, but that shouldn't be the default IMHO.

**Comment by crispheaney** [comment]
+1 to exposing CU consumption if we want users to request tighter CU limits

**Comment by taozhu-chicago** [comment]
> +1 to exposing CU consumption if we want users to request tighter CU limits

Agreed. Simulations or careful design help on some use cases, but may not be enough for others. [SIMD #49](https://github.com/solana-foundation/solana-improvement-documents/pull/49) also helps better utilized requested CU limit. Any suggestions are welcomed.

**Comment by taozhu-chicago** [comment]
> Can you elaborate on why higher CU limits is problematic? Will make it easier to brainstorm suggestions!

- requesting more CU than actually needed wastes block space (block has CU limits);
- with CU based fees (SIMD 19, SIMD 16, and SIMD 50), higher CU limits means higher fee.

**Comment by eugene-chen** [comment]
are block CU limits based on CU used or CU requested? i was under the impression it's the former.

**Comment by eugene-chen** [comment]
If we're in a market regime where blockspace demand is so low, such that the price is low enough for people to spam funny logs or drastically over-request CUs, I don't think this is an issue.

The market's response--if there is actually more demand that is being serviced--is to increase the price by the appropriate amount. If folks (users, bots, etc.) sending transactions aren't getting them included at a satisfactory rate, they need to increase the priority fee.

note: the UX with this type of priority fee will always be quite poor, since you will always be guessing how much priority fee you need to add. A 1559-like mechanism should make a lot more sense.

**Comment by taozhu-chicago** [comment]
> I imagine you'd end up getting less fees overall.

In general sense, leaders do extra work for TXs with priority, prioritization fee compensates that extra work. Less prioritization, less fee. 

As for CU limits, I think there are room for improvement. Randomly pick a [tx](https://explorer.solana.com/tx/373NBWtQ5rcfXT2iMm7KM5bvtYLgczY26rDBKv49XWXeuWTjBVqFWjtVPZtF4yftXTm5Vc8tWeMEqErngWBwVjwc), it only used half of request CU. It is understood TX has to cover worse scenario, but we can work out better ideas such as SIMD 49

**Comment by SpaceMonkeyForever** [comment]
> Randomly pick a tx, it only used half of request CU

Exactly what you said. You have to cover worst case scenario. Most of the time, 150k is used, but TX do hit over 250k sometimes and you'll lose money when that happens. SIMD 49, as far as I understand, would make it so that I place orders up to the remaining CU i.e. some orders at the end might not make it to the book. It's more of a trade-off than a solution IMO because it does remove liquidity from the book specially the backstop orders at the end which are important for liquidations to work properly on margin protocols like Mango.

**Comment by taozhu-chicago** [comment]
Without understanding what takes to trade successfully, and with full respect, I'm wondering if possible such transaction be broken up into smaller TXs, coordinated by signals generated off-chain? Akin to traditional trading/MM-ing app builds order books locally via feeds, sending orders via signals generated from local order books.

**Comment by eugene-chen** [comment]
We don't see a *ton* of this today, but having lots of logic on-chain (so state can be read at execution time) creates difference in CU requested (max CU used) vs. actual CU used.

For example, I may have a smart contract where I ping it with what I think the fair price is. The contract's logic decides whether it should cancel orders, place new orders, etc., depending on the input fair price + the current state of the market, sometimes using a lot of CUs and sometimes using not that many.

**Comment by SpaceMonkeyForever** [comment]
> I'm wondering if possible such transaction be broken up into smaller TXs

I'm not sure if I understand correctly. My point above was to comment on the proposal (SIMD 49) that would allow the TX to specify "process instructions up to compute limit N" rather than running out of compute, maybe I misunderstood it though. What I was trying to say is that if the compute requirement suddenly jumps (since it's dynamic, I cannot know for sure that a TX will require only 150k and not 250k), and I use that new feature of "process inx up to" then some orders will not be placed because their inxs will be omitted, specially the ones at the end with bigger sizes which are needed for liquidations to work properly on e.g. Mango (liquidations usually require big orders because it's a big market order that needs to be filled).

About splitting orders over multiple TXs in general though:
One of the best features on Solana relative to everywhere else I trade(d) is the fact I can replace all orders in a single TX atomically, this is extremely useful. Most CEXs don't support this, Binance being one big exception but it's still not as smooth as Solana (it's modify not cancel+place, so need to get order ids right).  It is possible to split up order updates over e.g. 2 TXs but then isn't that creating more congestion for you? Because, again, I don't know when I should or shouldn't split so I'll just always split and now my TX rate is doubled everywhere which will be a significant increase in total TXs sent to the chain every second.

**Comment by taozhu-chicago** [comment]
Right, this is model is common that creates large variance in requesting CU limits. Would be great if the decision could be made off-chain, so you have one small and static tx to frequently pull data from chain to build local cache; then ping it with price locally, based on decision to send new/update/cancel orders, which are pretty much single-function transactions that'd be constant in requested CU.

Not sure if it is feasible to all cases, but maybe there are successful stories out there?

**Comment by eugene-chen** [comment]
yes, the problem is you really care about the state at run time, not at tx send time, especially in a HFT setting. Extra troubling when you don't even know when your tx is going to land

**Comment by taozhu-chicago** [comment]
> My point above was to comment on the proposal (SIMD 49) that would allow the TX to specify "process instructions up to compute limit N" rather than running out of compute,

You are correct that SIMD 49 allows transactions to adjust execution path in runtime based on CUs consumed. leading to better CU utilization. Removes some need of "over requesting".

>  It is possible to split up order updates over e.g. 2 TXs but then isn't that creating more congestion for you? 

Number of transactions per second isn't a reliable indicator for congestion. If one transaction requests 300_000 CU, but can break into 2 transactions, each request 100_000 CUs, then we are better off.

**Comment by taozhu-chicago** [comment]
Convos are zooming into reducing request CU limit, which is good. But just to keep big picture in perspective, this issue (and SIMD 50) is solely for changing prioritization fee units (which combines with request CU limits impacts prioritization fee). For HFT and MM, when PRAW fee (SIMD 16) is implemented, I imagine there would be even less need to prioritize their transactions. (BTW, it might worth pointing out PRAW fee is also requested CU based).

**Comment by ckamm** [comment]
I don't like this proposal in its current form. It seems to have negative side effects and I don't think it will accomplish all of its goals.

If you make the prioritization fee increment 1 lamport/cu, I'd expect:

1. Most people will use zero prioritization fee. Their transactions won't have to care about the amount of compute they request, since there's no cost associated with it. At this level there will be lots of contention for getting into the next block.

2. Market makers who send lots of transactions and care about send-to-confirm time will have no economic way of getting faster confirmations than users who don't care. They'll lean on time-in-force even more (because they can't rely on timely cancels) and quote wider (because by the time their orders land, the price is stale). 

3. The 1 lamport/cu prioritization level will be the only other one that sees much use. People who send rare or urgent transactions will use it.

Looking at the goals from SIMD-50:

> Prioritization_fee is proportionally insignificant to base fee

Well, people could already use 1 lamport/cu prioritization. But no one does because they can outbid enough people with much less. This could be because the demand isn't large enough to drive prices higher. But yeah, increasing the prio market's tick size would likely help - but something like 10k microlamports/cu should be enough without wiping out most current usage.

> Therefore, some payers set priority even there is no contention, potentially leaves other users at a disadvantage

I don't get this at all. If there's no contention, why is someone without priority fee at a disadvantage? Isn't the whole point of the priority fee for users to be able to pay fees to get into blocks more quickly when there's contention for that?

> Little consideration was given to compute_unit_limit when setting priority

I expect this proposal would not change that, because people who use zero priority fee don't have an incentive to care about compute units. (though other proposals are addressing that)

**Comment by taozhu-chicago** [comment]
Thanks for chiming in @ckamm, 

Ideally user should selectively/carefully utilize priority. As example, updating orders might not justify additional prioritization fee under normal condition, but mass cancel would be OK to pay higher fee to increase certainty of its timely execution. 

The main goal of this proposal is to get close to this ideal scenario, that is no tx _need_ to pay priority when no contention (not on block nor on account), but should pay when urgency raises that justifies the additional cost.

My argument is if this "additional cost" is too insignificant, TXs needn't pay will continue set priority, say to lock an account, which practically raise cost unnecessarily for anyone wants to wrote that account.

Some data collected at #31755 shows only 3.6% non-vote transactions set cu-price in MNB today, assuming these are from active users who cares about both send-to-confirm time and overall cost. I figured this is the ideal group to start working out cu cost, and perhaps, as nice side effect, figuring out ways to request more accurate cu limit. 

Hope we can all agree on that, if so we just need to figure out what CU cost works the best towards that goal, being 1 lamport/cu, or 0.1 lamport/cu, or 0.01 lamport/cu.

**Comment by SpaceMonkeyForever** [comment]
> My argument is if this "additional cost" is too insignificant, TXs needn't pay will continue set priority, say to lock an account, which practically raise cost unnecessarily for anyone wants to wrote that account.

I want to understand this. When there is no contention, why does setting priority increase the cost for others? Aren't all TXs processed anyway when there is no contention?

> Hope we can all agree on that, if so we just need to figure out what CU cost works the best towards that goal, being 1 lamport/cu, or 0.1 lamport/cu, or 0.01 lamport/cu.

I'd say decreasing current granularity by 1000x to milli-lamports (0.001) is the right choice in my experience so far.

**Comment by SpaceMonkeyForever** [comment]
> My argument is if this "additional cost" is too insignificant, TXs needn't pay will continue set priority, say to lock an account, which practically raise cost unnecessarily for anyone wants to wrote that account.

I want to understand this. Currently, when there is no contention, all TXs are processed anyway so there shouldn't be an increase in cost for others. Is that correct?

However, your point is if you implement dynamic (CU-based) fees then this will change and it will become more costly for others?

> Hope we can all agree on that, if so we just need to figure out what CU cost works the best towards that goal, being 1 lamport/cu, or 0.1 lamport/cu, or 0.01 lamport/cu.

I'd say decreasing current granularity by 1000x to milli-lamports (0.001) is the right choice in my experience so far.

**Comment by taozhu-chicago** [comment]
> I want to understand this. Currently, when there is no contention, all TXs are processed anyway so there shouldn't be an increase in cost for others.

An example would be, say one _always_ sets `cu_price = 50_000` to lock account `ABC`. Now I am going to send a transaction to write `ABC`, so I diligently check RPC Endpoint for the minimal prioritization fee for `ABC`, found for last 150 slots the min fee paid for that account is `50_000`. I would have to think it is what it takes to lock `ABC` (even I understood the prio fee is insignificant atm), so I ended up paying `50_000 * my_cu_limit` unnecessarily. 

From this example, my point is, to improve local fee market integrity, user should be incentivized _enough_ to use prioritization fee close to its original intention. (sorry for repeating this over)

**Comment by taozhu-chicago** [comment]
> However, your point is if you implement dynamic (CU-based) fees then this will change and it will become more costly for others.

Changes to priority fee impacts that 3.6% priority-setting-txs', implementing cu-based fee will impact all transactions. I'm working this proposal as precursor of dynamic base fee. (Just to clarify, changing base fee will not impact prioritization, nor local fee market).

**Comment by taozhu-chicago** [comment]
> I'd say decreasing current granularity by 1000x to milli-lamports (0.001) is the right choice in my experience so far.

Well, the vote counting so far:

| lamport/cu | votes | whom | 
| ---- | ---- | ---- |
| 1  | 1 | me |
|  0.01  | 1 | @ckamm |
| 0.001 | 1 | @SpaceMonkeyForever |

**Comment by mschneider** [comment]
About no one using `getRecentPrioritizationFees`, isn't this feature only available on mainnet since 1.14. My rpc runs this version since last Thursday. An upgrade that took labs multiple months to release. Did you expect users to upgrade their code and use the RPC call before it was released (looks like it from the issue date).

How about upgrading client libraries (including anchor) updating the solana cookbook and other documentation (just checked, doesn't mention this RPC call yet), announcing the feature regularly on social and just waiting a few more weeks until people adopt and then make a conclusion?

This seems more reasonable to me, then to release a feature gate, that has negative economic impact on nearly every stakeholder in the ecosystem.

**Comment by eugene-chen** [comment]
Current base fee is 5000 lamps/signature (let's say lamps/tx for simplicity)

Current min prio fee is 1 lamp/tx (assuming 1m CU requested)

It seems reasonable to increase the min prio fee to be a higher portion of the base fee--at least 1%. But many multiples of the base fee (the original proposal would bump this to 1m lamps or 200x the base fee) seems way too large and likely to cause unintended effects with priority fees (like people choosing to never use them).

Increasing by a factor of 1000 (min prio fee becomes 20% of base fee) seems reasonable as @SpaceMonkeyForever suggests.

Is there a reason we need to change the units we denominate priority fees in, rather than just the minimum value? Does it make the implementation much more complicated?

**Comment by taozhu-chicago** [comment]
> Increasing by a factor of 1000 (min prio fee becomes 20% of base fee) seems reasonable as @SpaceMonkeyForever suggests.

Did some manually simulation over 500 slots of MNB ledger [here](https://github.com/solana-labs/solana/issues/31755#issuecomment-1574312634), setting incremental unit to 1_000 micro-lamport does look better than proposed 1_000_000 micro-lamport. 

I updated this issue description to adapt using "1_000 micro-lamport" as tick size for compute-unit price. Will update PR #31469 accordingly, will ask for review/approval when ready.

**Comment by taozhu-chicago** [comment]
PR #31469 is ready for review, appreciate any feedbacks. SIMD #50 was updated as well.

**Comment by tao-stones** [comment]
Issue no longer valid, nor has plan for further development, close it
