### ISSUE TITLE
Backporting

### ISSUE THREAD

**Issue by diman-io** [solana-labs/solana#31464]
Hello,

There's no information about non-Git automated backporting in the [CONTRIBUTING.md](https://github.com/solana-labs/solana/blob/master/CONTRIBUTING.md).

So, my question is, what's the proper way to do this?

Actually, my question pertains to #30452, #31137, and #31201.

I've backported those PRs [in my repo](https://github.com/diman-io/solana/commits/diman/v1.14) just to demonstrate that all three have conflicts after cherry-picking.

Another issue is that they depend on each other.

So, from my end, I could open one PR, wait for it to be merged, and then open another 😭

Just let me know what you'd like me how to do.

**Comment by mvines** [comment]
> There's no information about non-Git automated backporting in the [CONTRIBUTING.md](https://github.com/solana-labs/solana/blob/master/CONTRIBUTING.md).

I guess that's somewhat deliberate. This is uncommon and might be not desirable, so some impedance here could be considered a feature. 

> So, my question is, what's the proper way to do this?

Manually send a PR to the desired release branch instead of `master`

> So, from my end, I could open one PR, wait for it to be merged, and then open another 😭

Yes, that's the approach that would need to be taken.

However in this case I wouldn't support a backport of those new features to any existing release branch. They will ship with the v1.16 release though.

Let's chat more in Discord though, #core-technology channel works
