### ISSUE TITLE
Prioritization fee usage in MNB 

### ISSUE THREAD

**Issue by tao-stones** [solana-labs/solana#31755]
#### Problem
A set of data that depicts: 
1. how prioritization fee is used in minnet-beta, in relation to signature fees and cost limits; 
2. how prioritization fees are set; (eg. was cu_limit requested or defaulted, was cu-price set, what's cu-price distribution, percentage of non-vote transactions set prioritization fee, etc)
can be useful in understanding how local fee market are utilized; how efficient it is; and to measure results should #31469 landsin miannet-beta. 

#### Proposed Solution
- use modified ledger-tool and script in #31753 to replay MNB ledger, generate metrics for analyzing and comparison.

**Comment by taozhu-chicago** [comment]
```

Slot 189234458 block_cost 42378601 [88.28%] largest_account_cost 11981610 [99.84%]
    priority fee distribution: (cu_price, occurances, occurances%, avg lamports paid)
      0 1896 94.32% 0
      5 9 0.44% 7
      10 1 0.04% 14
      51 1 0.04% 510
      56 1 0.04% 560
      59 14 0.69% 590
      100 3 0.14% 336.667
      110 1 0.04% 22
      120 1 0.04% 24
      130 1 0.04% 26
      140 1 0.04% 28
      150 1 0.04% 30
      160 1 0.04% 32
      188 1 0.04% 264
      189 1 0.04% 265
      252 4 0.19% 506
      500 1 0.04% 375
      900 1 0.04% 1260
      1000 50 2.48% 218
      2000 1 0.04% 2400
      10000 1 0.04% 6000
      30101 19 0.94% 42142
Slot 189234459 block_cost 26010409 [54.18%] largest_account_cost 11981610 [99.84%]
    priority fee distribution: (cu_price, occurances, occurances%, avg lamports paid)
      0 797 94.65% 0
      2 1 0.11% 3
      5 9 1.06% 7
      10 1 0.11% 1
      27 1 0.11% 6
      50 2 0.23% 70
      59 1 0.11% 590
      110 1 0.11% 22
      120 1 0.11% 24
      130 1 0.11% 26
      140 1 0.11% 28
      150 1 0.11% 30
      160 1 0.11% 32
      170 1 0.11% 34
      180 1 0.11% 36
      190 1 0.11% 38
      500 1 0.11% 375
      1000 17 2.01% 177.647
      1001 1 0.11% 1001
      5000 2 0.23% 5000

---- fee stats ----
total transactions: 2852
total non-vote transactions: 468 [16.4%]
total non-vote transactions with CU-LIMIT: 277 [9.71%] close to 100% is better
total non-vote transactions with CU-PRICE: 169 [5.92%] lower is better when no congestion

total base fee: 15180854
total prio fee: 850234 [5.6%]
total sign fee: 14335000 [94.42%]

---- Anomalies count ----
vote sets cu price or limit: 0
uses deprecating CB ix: 23
calculated fee not match: 19
set CU limit above MAX: 22
set CU price without setting limit: 25
set CU price without congestion: 87 [51.47%] lower is better
```

**Comment by taozhu-chicago** [comment]
replay with a larger MNB ledger, got stats below. Few highlights:
1. the total prio-fee paid is only 6.64% of total base fee; 
2. only 6.03% non-vote TXs set cu_limit. need to push it close to 100%
3. conservatively consider "congestion" being tracked CU > 75% of CU_Limit, there are still 31.27% non-vote TXs set CU_price. Ideally no one would want to set priority when there's no congestion.

```
---- fee stats ----
total transactions: 49857481
total non-vote transactions: 5414935 [10.86%]
total non-vote transactions with CU-LIMIT: 3008625 [6.03%] close to 100% is better
total non-vote transactions with CU-PRICE: 1798904 [3.6%] lower is better when no congestion

total base fee: 268209993407
total prio fee: 17821423466 [6.64%]
total sign fee: 250230250000 [93.29%]

---- Anomalies count ----
vote sets cu price or limit: 0
uses deprecating CB ix: 313212
calculated fee not match: 95412
set CU limit above MAX: 97407
set CU price without setting limit: 219317
set CU price without congestion: 562524 [31.27%] lower is better
```

**Comment by taozhu-chicago** [comment]
To get an idea about what'd happen to prioritization fee after rounding, I aggregated about per-slot priority fee distributions of 501 MNB slots (total 118_157 non-vote transactions), the aggregated distribution looks like this: 
<img width="608" alt="image" src="https://github.com/solana-labs/solana/assets/82401714/be601940-4635-4690-90a0-2edcc92220b8">
in this data set:
- about 2/3 non-vote transactions set cu-price to `0` (eg, not setting priority), 
- the second largest pie,`11.9%` non-vote transactions, set cu-prince to `1_000`. 
- not shown in the chart are: there are 654 different values of cu-price, [few rare case](https://explorer.solana.com/tx/4pcFXCKL3z616jzg3gKnaZpteogGM6D8fff9AKfb4rFXJqsNNmhUZWmNLCrWu2BgMb4pppyytxWbpGDVpPwg4Rqd) cu-price was set as high as `5_767_168`

If round to lamport, as proposed, and assuming every transactions that current use priority still want to use priority, then almost all of them will be setting cu-price to `1_000_000`: 
<img width="607" alt="image" src="https://github.com/solana-labs/solana/assets/82401714/21c071a1-2270-4721-816a-b193c33541b7">
It probably not even close to reality, many transactions more likely to stop setting priority due to higher cost.

If round to 0.001 lamports, as community members [suggest](https://github.com/solana-labs/solana/issues/31453#issuecomment-1573810611), still assume transactions want to maintain same relative priority, so each will increase cu-price to nearest milli-lamport, then the distribution will look like this: 
<img width="607" alt="image" src="https://github.com/solana-labs/solana/assets/82401714/9a46c6f4-3932-4045-bfc6-a990205a34e2">
1_000 micro-lamports (or 0.001 lamport) as prioritization fee unit at this point does look like a sweet spot, while still have some percentage of TXs at higher priority.
