### ISSUE TITLE
Stake amount not updating when withdrawing funds

### ISSUE THREAD

**Issue by anbud** [solana-labs/solana#31942]
### Problem
Delegated stake amount in the stake account is not updated properly when withdrawing specific amounts from the stake account.

#### Steps to reproduce:

1. Stake an arbitrary amount of SOL that's bigger than the rent exempt reserve (`2282881` lamports should work)
https://solscan.io/tx/jiG1ftnqVoJbqx51fRLjrZMx2kj6mS1LF92MpVhoHaHBdaw7GzADvcEigB4Rn3dR34XxDEUq14TdXY2r6nuR9Jq

2. Deactivate the stake account
https://solscan.io/tx/tf2ZWc6Z8m542FBqReSucDDnp1wbSe2XQfi6E2GUvHDTXRL48WZETMWYQtoxXVDETPDaShG6ba5dxVt7Uq8TMJa

3. Withdraw the exact amount from the stake account that only leaves the rent exempt reserve on the account (`1` lamport in our case)
https://solscan.io/tx/62SxXKVcRL1KQHxyziGqWb3rntpHdrUUFgAVzN3P5rycaTpa5vfSchVtDD2gru2vpM984TwT5kfLVSrdabVkKBad

4. Check the stake account data
https://explorer.solana.com/address/2cXru5ghQjRwHva8sXvLzY3EPxZTNME9NMrstLNEMHMW

As you can see, the `u64` that holds the stake amount (`delegation.stake`) was not properly updated to reflect the withdrawal and it still shows the full staked amount, even though it's not available anymore. The value of the `stake` field is currently `0100000000000000` even though it should be `0`.

`getStakeActivation` RPC call is not affected by this and returns `0` for both `active` and `inactive` balances.

**Comment by CriesofCarrots** [comment]
This is expected behavior. Once a stake account is deactivated, the previous `delegation` struct no longer has any relevance, so the value is not adjusted by any withdrawals. If you performed the same process with an amount that left more than the required minimum stake (currently 1 lamport) and then delegated the account anew, then you would see the `delegation` amount updated.

That said, the explorer could probably handle display of deactivated stake better. Perhaps it should not even display the Stake Delegation block at all when it is "inactive". If you care to weigh in, please open an issue on the [explorer repo](https://github.com/solana-labs/explorer/)
