### ISSUE TITLE
Evaluate effectiveness of current Weight calculation in gossip

### ISSUE THREAD

**Issue by sagar-solana** [solana-labs/solana#3205]
#### Problem

Gossip currently decide's node weights based on ln(stake) * time_since_last_picked. This was chosen to allow lowly staked nodes a shot at being picked for push messages instead of relying entirely on pulls. 

#### Proposed Solution

Taking the log of the stake in weight calculation creates a possible attack vector where unstaked or lowly staked nodes have a stronger chance of getting picked as time passes. This creates a way for unstaked/lowly staked gossip peers to spam the network. 

We could add an additional parameter to weight; the "time since last received from". This parameter is unsecure and would need to be treated carefully and maybe set to the minimum value for unstaked nodes.

Tag: @aeyakovenko

**Comment by aeyakovenko** [comment]
time_since_last_picked Is secure. 

It’s taking the log of the stake weight that creates an attack vector.  2 stakes have a higher weight than 1 of equal size to the sum. 

We could do an additional parameter to weight the time since last received message.  This parameter is insecure and would need to be treated carefully.  Maybe set to the minimum value for unstaked nodes.
