### ISSUE TITLE
JSON RPC Method `getBlocksWithLimit` Requires 2 Parameters but Docs Say 1

### ISSUE THREAD

**Issue by buffalojoec** [solana-labs/solana#32696]
#### Problem
The JSON RPC method `getBlocksWithLimit` is [documented](https://docs.solana.com/api/http#getblockswithlimit) to say that only `start_slot: u64` is required, while `limit: u64` is optional.

However, this does not match the behavior of the RPC method.

```shell
curl https://api.mainnet-beta.solana.com -X POST -H "Content-Type: application/json" -d '{ "jsonrpc": "2.0", "id":1, "method":"getBlocksWithLimit", "params":[5] }'

{"jsonrpc":"2.0","error":{"code":-32602,"message":"`params` should have at least 2 argument(s)"},"id":1}
```

#### Proposed Solution
We can choose to either:
- Give `limit` a default value and make it truly optional
- Update the documentation

I get the sense that it shouldn't be optional, considering a sensible default value is hard to nominate:
- 500,000 (max) will default to 500,000 blocks response
- 0 (min) will give 0 blocks

**Comment by steviez** [comment]
The code matches your findings that the limit is NOT optional; note that limit is a `usize` and not an `Option<usize>`:
https://github.com/solana-labs/solana/blob/8c148868912bcb7e8ea419965d0fc37dcaab4b67/rpc/src/rpc.rs#L3351-L3358

It looks like this function has always had `limit` as a required argument since it was added in https://github.com/solana-labs/solana/commit/75b621160ea. I'm a little conflicted on whether the arg should be required or not:
- On one hand, making `limit` optional for `getBlocksWithLimit` with 500k default would make `getBlocksWithLimit` consistent with `getBlocks` in the sense that `end_slot` is optional for `getBlocks`.
- On the other hand, the function contains `WithLimit` in the name, so I think it would be reasonable to expect a user to specify a limit.

I think we are at liberty to change the argument to optional if we wanted to as making it optional is more relaxed. (Whereas, changing from optional to required would be a breaking change.) I'm probably leaning towards leaving as required and updating docs, but I'll tag @CriesofCarrots in for an option too.

**Comment by buffalojoec** [comment]
Cool, thanks for checking on this! 

I would say considering your second bullet combined with your point of not introducing a breaking change, updating the docs sounds like the right play.

I'm happy to do this via PR, since we are finding some minor errors in the JSON RPC docs as we build out the new Web3 JS SDK.

**Comment by steviez** [comment]
> updating the docs sounds like the right play.

👍 

> I'm happy to do this via PR

Cool, feel free to add me as a reviewer if you'd like
