### ISSUE TITLE
Last restart slot is part of every slot's accounts delta hash

### ISSUE THREAD

**Issue by ripatel-fd** [solana-labs/solana#32805]
#### Problem

On current Solana master, the last restart slot sysvar is hashed into every slot's account delta hash, even when the account doesn't change. This behavior diverges from every other account on the network.

**Comment by steviez** [comment]
Something like this commit should do the trick: https://github.com/steviez/solana/commit/fca3733fbf7b2f6f819a9a26bd09069cc7594f09. However, I'd also like to confirm that this is expected behavior / not a bug somewhere else.

As a little context, the last restart slot is currently checked for update every slot once the feature has been activated; here is the function:
https://github.com/solana-labs/solana/blob/ce63640d6deb29e78d6de9727afbbdc4bb1bcdca/runtime/src/bank.rs#L2110-L2136

The `self.update_sysvar_account()` eventually calls `AccountsDb::store_accounts_cached()`; so, this is getting called every slot with the same payload (assuming no new hard forks show up).

@jeffwashington - Just to make sure, is this account showing up as dirty (ie in the accounts delta hash) every slot (even though the account contents written every slot is the same data) consistent with how you expect things should work? That is, the caller (ie the `Bank` function) should perform the sanity check to only restore the account when the value has changed instead of relying on AccountsDb to detect that the account data has not actually changed

**Comment by jeffwashington** [comment]
if I understand correctly what you're asking:
accounts db does not care if an account is changed. rewrites occur on every slot right now anyway and for rent exempt accounts, nothing should change (apart from rent_epoch, which will soon not change).
if the bank writes it to accounts db, then it gets written at the new slot, included in the delta hash, and in the accounts hash, and supersedes the prior version of the account at an older slot.

**Comment by steviez** [comment]
> if the bank writes it to accounts db, then it gets written at the new slot, included in the delta hash, and in the accounts hash, and supersedes the prior version of the account at an older slot.

Good deal, thank you @jeffwashington. This is what I expected but just wanted to make sure. The path forward is being smarter about not rewriting the account every time like my PR proposes ... I will proceed with that
