### ISSUE TITLE
Enhancing Solana's Staking Ecosystem: Enabling Native Program Interaction with SPL Tokens

### ISSUE THREAD

**Issue by SyedGhazanferAnwar** [solana-labs/solana#33434]
#### Problem
I am currently exploring the capabilities of the Solana blockchain and wanted to investigate the feasibility of extending Solana's staking functionality to include SPL tokens. However, I've encountered a challenge due to the differing nature of SPL tokens (BPF-loaded) and the staking program (native).

#### Proposed Solution
I propose exploring potential methods or interfaces that would allow native programs to interact with SPL tokens, enabling the movement and management of SPL tokens within the Solana ecosystem. This would facilitate a more seamless integration of staking features with SPL tokens, enhancing the versatility and utility of the Solana blockchain.

I am seeking guidance, recommendations, or insights from the Solana development community on how to achieve this integration or if there are any existing plans or solutions in progress to bridge this gap between native programs and BPF-loaded SPL tokens.

**Comment by buffalojoec** [comment]
Hello, I'm not totally sure if this is the right place to discuss a topic like this, but for context I'll share a couple of points.

For starters, it doesn't make sense for a _native_ program to be able to interact with a _non-native_ SPL token. In fact, not even the SPL Token Program itself is a native program!

It's also not possible to stake with anything but the SOL token since it's the native network token used specifically for staking, ie. securing the network.

It seems, at first thought, what you're actually interested in exploring is something like _liquid staking_, where someone could interact with your protocol by "staking" SPL tokens with you, while you convert the tokens to native SOL and stake that instead.

I'm not sure if this is what you're looking for, but if you want to discuss further I suggest creating a, sRFC on the Solana forums at https://forum.solana.com/
