### ISSUE TITLE
solana-cli v1.16.15 crate missing

### ISSUE THREAD

**Issue by andreisilviudragnea** [solana-labs/solana#33557]
#### Problem

solana-cli v1.16.15 is missing from https://crates.io/crates/solana-cli/versions

#### Proposed Solution
Add the missing crate release.

**Comment by CriesofCarrots** [comment]
Thanks for the heads up. Missing crates have been published.

For posterity, the issue was `solana-cli-output`, which was using a `chrono` method that has been deprecated in a recent version. `cargo publish` was pulling in this newer version of `chrono` and failing on the deprecation warning:
```
Compiling solana-cli-output v1.16.15 (/solana/target/package/solana-cli-output-1.16.15)
warning: use of deprecated associated function `chrono::DateTime::<Tz>::from_utc`: Use TimeZone::from_utc_datetime() or DateTime::from_naive_utc_and_offset instead
   --> /display.rs:719:39
       Some(ndt) => DateTime::<Utc>::from_utc(ndt, Utc).to_rfc3339_opts(SecondsFormat::Secs, true),
                                                            ^^^^^^^^
```
Resolved by pinning `chrono` in Cargo.toml.
