### ISSUE TITLE
Allowing entries containing transactions with conflicting accounts in Banking stage

### ISSUE THREAD

**Issue by talalim** [solana-labs/solana#33899]
#### Problem
TPU has to make entries using only “disjoint” transactions because TVU makes some overly strict assumptions, i.e: 
- That assumption seems to be that the TVU will break up a batch and execute individual transactions in parallel. In reality, this is not the case.
- Actually the TVU tries to execute multiple entries/batches in parallel using Rayon hence each transaction of a batch is executed sequentially in the scope of that batch
- This scheduling assumption severely limits any innovation in scheduling strategies 

#### Proposed Solution
 
We've figured out that if we allow transactions with conflicting accounts in an entry for a flexible scheduling of transactions by changing the locking function in a way that it allows transactions with conflicting accounts in an entry, It doesn't break the execution of transactions on replay side. As it parallelize entries for execution and not individual transactions in an entry.
It looks like the way locking is implemented in execution the assumption is that the replay side will execute individual transactions in parallel, which doesn't seem to be the case.
The only thing that can break from our exploration is the rebatching logic in TVU, which can also be fixed by changing it a little e.g acquiring locks after rebatching is done.
We think if this overstrict requirement of making disjoint entries can be changed to allow entries with transactions of conflicting accounts, the performance of the banking stage can be improved by scheduling the transactions in a way that CPU utilization can be improved.

Do you guys have anything else in mind which can be affected by allowing entries with conflicting transactions 

@steviez @apfitzge @jstarry @buffalu

**Comment by steviez** [comment]
Thanks for posting the issue @talalim; much less likely to get lost here. This week is a little busy with Breakpoint going on, but I will try to refresh myself on the matter and give an answer next week

**Comment by talalim** [comment]
thanks @steviez 
Looking forward to your feedback.

**Comment by apfitzge** [comment]
@talalim, thanks for creating an issue. This is something that has been on the map for a while, but held back by work on other work.
As some of the scheduler work is beginning to wind down, this is one of the things I am hoping to begin work on.
Although I doubt we'll get much pushback, in my view since this is a base protocol change, it should be going through the SIMD process, even if as a formality.

WRT to actual implementation, I don't think it's as simple as described here.

> That assumption seems to be that the TVU will break up a batch and execute individual transactions in parallel. In reality, this is not the case.

We currently do re-batching on the entries we are processing. If we removed the re-batching and used entries directly, we can guarantee that we are processing the entries (potentially self-conflicting, but not conflicting with eachother) and there are no issues with parallel access.
However, part of the reason we do re-batching is to help mitigate an attack vector where the leader maliciously creates entries that take a long time to process. So I'm not convinced we will want to just remove that immediately.

Other than that, it's just simply re-working the current implementation. The current batch processing of transactions does not simply loop over transactions, but does sections of work for all transactions. This requires some re-writing of code, since we can no longer load all our accounts up front, since for some shared writable account the state may have changed. 

All that's not to say this shouldn't be done; it should. Just giving an overview of how I've viewed the problem, and why it hasn't been done yet.

**Comment by apfitzge** [comment]
Created a SIMD here: https://github.com/solana-foundation/solana-improvement-documents/pull/83
In terms of priority, I think it sits behind 0082; but these are very much changes that could be done in parallel

**Comment by talalim** [comment]
Hey @apfitzge 
We looked at the SIMD and its exactly what we're are talking about that the constraint on entries should be relaxed.
We implemented and tested the required changes to enable self conflicting entries in our lab setup and this improves the performance alot depending on how you schdule the transactions on every execution thread. 
The changes include: 
- changing account locking function
- carrying temporary account state within the execution with every transaction in an entry

We can make a PR for these changes which allows all of this for community to review this.

**Comment by steviez** [comment]
@Huzaifa696 - Thanks for your continued interest / efforts on this problem! As mentioned in this comment:
https://github.com/solana-foundation/solana-improvement-documents/pull/83#discussion_r1393594573

The order we'll follow is `SIMD approval ==> Feature Gate Issue ==> PR with SIMD implementation behind feature gate`. So, I think we need to get agreement on the SIMD across the ecosystem before we jump in with the implementation. As such, I am going to wait on looking at the code in the PR you linked until we get the SIMD approved. Hopefully we are able to reach agreement on the SIMD, and your code can accelerate getting that feature implemented and eventually deployed!
