### ISSUE TITLE
Feature Gate: Disable bpf loader management instructions

### ISSUE THREAD

**Issue by HaoranYi** [solana-labs/solana#34424]
### SIMD

[Disable bpf loader V1 program deployment](https://github.com/solana-foundation/solana-improvement-documents/pull/93)

### Description

bpf loader still reads and writes account `executable` meta to check and set whether an account is executable. Therefore, it is a blocker to deprecate `executable` meta on the accounts. 
This feature, when activated, will make sure that there will no more bpf loader program deployment on chain. Then, we can safely deprecate account `executable` meta. 

### Feature ID

7WeS1vfPRgeeoXArLh7879YcB9mgE9ktjPDtajXeWfXn

### Activation Method

Single Core Contributor

### Deployment Considerations

NA

### Minimum Beta Version

v1.17.20

### Minimum Stable Version

v1.17.20

### Testnet Activation Epoch

608

### Devnet Activation Epoch

659

### Mainnet-Beta Activation Epoch

601

**Comment by CriesofCarrots** [comment]
SIMD link does not link to a SIMD

**Comment by HaoranYi** [comment]
> SIMD link does not link to a SIMD

Added.

**Comment by HaoranYi** [comment]
feature has been activated on mainnet.

**Comment by bshumi** [comment]
Hi @HaoranYi, I was trying to deploy a solana program and accidentally used solana cli 1.14.29 with "solana deploy" instead of "solana program deploy". The deployment txs failed with the following errors:

> BPF loader management instructions are no longer supported
> Program returned error: Unsupported program id

It created an account that belongs to BPFLoader2 and took about 3 SOL. As a result, I can't close it. How can I get my SOL back? Is there any instruction that allows me to recover my funds?

**Comment by HaoranYi** [comment]
I am not aware of any instruction to with draw these fund. 
I am at @Lichtso to see if he knows more to help you.

**Comment by Lichtso** [comment]
If you created the account with BPFLoader2 as owner (instead of gifting the account during program initialization), then it is finalized and thus the funds are burnt unfortunately. We should deactivate the CLI of the older loaders to prevent others from stepping in the same issue.

**Comment by bshumi** [comment]
@Lichtso Thanks for your response! Is there any chance of adding a 'rescue' instruction to BPFLoader2? I have the account keypair, and I think I should be eligible to recover my funds. The issue seems to have happened because the CLI wasn't deactivated earlier.

Another possibility could be to return the funds through a bug bounty—I'm happy to work something out if this can help improve the system and prevent others from facing the same problem. Let me know if this could be an option!
