### ISSUE TITLE
Unreserve transaction costs from QoS service for unexecuted transactions

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#34807]
#### Problem
In banking stage, the qos service cost tracker reserves cost for all transactions in a batch until all executable transactions are loaded, executed, and committed. This means that any transactions that aren't executed due to "account in use" errors will not have their costs removed from the cost tracker until after processing the full batch. This means that for a short duration, the cost tracker's block cost is over reserved and could prevent other threads from committing more transactions near the end of the block.

https://github.com/solana-labs/solana/blob/79b9999f0890ae67078056b8951be8617d7f2870/core/src/banking_stage/consumer.rs#L462-L486

credit: @crispheaney

#### Proposed Solution
Immediately free up transaction cost from the cost tracker in banking stage if transaction locks fail

cc @taozhu-chicago

**Comment by crispheaney** [comment]
Also, if im reading it correctly, the banking stage thread first filters out tx based on max block cu limits and then tries to acquire the write lock for tx afterwards

Might it be better if it filters out tx that are already locked before checking the max block cu limits?

I have a hunch that that during volatile periods, tx that can be executed are getting dropped prematurely because tx with hot accounts, that cant be executed because of write locks, are spending all the compute units in the cost tracker.

**Comment by taozhu-chicago** [comment]
> Also, if im reading it correctly, the banking stage thread first filters out tx based on max block cu limits and then tries to acquire the write lock for tx afterwards
> 
> Might it be better if it filters out tx that are already locked before checking the max block cu limits?
> 
> I have a hunch that that during volatile periods, tx that can be executed are getting dropped prematurely because tx with hot accounts, that cant be executed because of write locks, are spending all the compute units in the cost tracker.

It probably is better to first check if transaction can fit into block (then reserve its space) before locking accounts it needs.

**Comment by crispheaney** [comment]
The scenario i'm imagining is that there are 10 tx with hot accounts at front of buffer with max cu request of 1.4m, they max out the cost tracker cus and all the tx after the first 10 hit the WouldExceedBlockMaxLimit. And if those 10 accounts cant be executed because of write lock contention, then you probably prematurely dropped tx's the could have actually be included.

I just started looking into this because there are a lot of dropped tx during volatile times: https://github.com/Block-Logic/dropped_solana_txs

But my understanding of scheduler is limited so this could easily be wrong

**Comment by taozhu-chicago** [comment]
Right, so the 11th TX will be tried after first batch of 10 TXs failed to lock accounts, then free up block space. 

This issue is to free up space quicker -- as soon as those TXs failed to grab lock, space reserved for them will be freed for queued txs

**Comment by jstarry** [comment]
> Might it be better if it filters out tx that are already locked before checking the max block cu limits?

I'll create a new issue for this, thanks for raising!

**Comment by jstarry** [comment]
Superseded by https://github.com/solana-labs/solana/issues/34825
