### ISSUE TITLE
getStakeActivation rpc method incorrect inactive balance

### ISSUE THREAD

**Issue by xdzurman** [solana-labs/solana#35111]
#### Problem

When funds are sent to an active stake account (by mistake or by e.g. JITO pools), the result of `getStakeActivation` remains unchanged. While `active` stake balance remains correct, I'd expect the `inactive` stake balance to not be 0, but be equal to the sent amount. Example:

before:
```
    "result": {
        "active": 100000000,
        "inactive": 0,
        "state": "active"
    },
```
-- send 0.1 SOL to the stake account
after:
```
    "result": {
        "active": 100000000,
        "inactive": 0,
        "state": "active"
    },
```
However, this state would be expected:
```
    "result": {
        "active": 100000000,
        "inactive": 100000000,
        "state": "active"
    },
```

#### Proposed Solution
Do not hardcode "0" inactiveBalance if the stake account is in an 'active' state, but calculate the inactiveBalance correctly (e.g. `balance - activeStake - rentAmount`)

**Comment by CriesofCarrots** [comment]
Good point. It looks like the `deactivating` and `inactive` cases already take the total lamports into account.
I have a PR up to make inactive_stake consistent across all states: https://github.com/solana-labs/solana/pull/35116

The one case where my patch might be a little unintuitive is `activating`:

before:
```
"result": {
    "active": 0,
    "inactive": 1000000000,
    "state": "activating"
  }
```

Send 1 SOL to the stake account.
after:
```
"result": {
    "active": 0,
    "inactive": 2000000000,
    "state": "activating"
  }
```

Epoch boundary passes.
then:
```
"result": {
    "active": 1000000000,
    "inactive": 1000000000,
    "state": "active"
  }
```

ie. just because an account is "activating" does not been the total "inactive" amount is what will activate. I think this is actually more correct.

**Comment by xdzurman** [comment]
Thanks for the speedy response!
