### ISSUE TITLE
Exchange: No way for investor to update an existing trade request besides cancelling it

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#3852]
Investors may want to update a trade request at a high frequency based on some external market information.  Rather than requiring an investor to cancel and create a new trade request the exchange program should support trade request updates.

If trade request updates are allowed then the trade update instruction should also include a sequence id so a broker an make a best guess as to the latest update that the investor intended if the update requests come out of order.

**Comment by amrali** [comment]
Instead of a new instruction how about we modify the trade data structure to include a version number (a monotonic integer) where the trader would use the same instruction as if he was recreating the same trade object but require increasing the version number by one for at trade request validation.

That way we also don't need to add special handling for updates but just to accept any changes for the same trade request iff the version number of incoming is greater than the local trade request's.
