### ISSUE TITLE
Circular dependency in cargo packages

### ISSUE THREAD

**Issue by danpaul000** [solana-labs/solana#3965]
#### Problem
The below circular dependency is breaking the publishing script (ci/publish_crate.sh) to push releases to crates.io

Runtime package has a dependency on vote-api:
https://github.com/solana-labs/solana/blob/master/runtime/Cargo.toml#L29

Vote-api has a dev-dependency on runtime:
https://github.com/solana-labs/solana/blob/master/programs/vote_api/Cargo.toml#L21

#### Proposed Solution
Remove the circular dep.

**Comment by mvines** [comment]
It would be so nice to have a tool that audits our internal Cargo.toml dependencies for errors like this, and turn CI red immediately.

**Comment by danpaul000** [comment]
@mvines who is the right person to take this one?  We should try to get this fixed today if possible, so 0.14 might actually get published.

**Comment by mvines** [comment]
I think this'll require some Rust rework of how `sdk/`, `runtime/`, `vote_api/` use each other, probably moving parts of `vote_api/` into `sdk/` that `runtime/` depend on.   I bumped this issue to v0.15 because while annoying for 0.14, nothing really _bad_ will happen if we don't fix it until v0.15 and I want to keep v0.14 a very focused release.

**Comment by danpaul000** [comment]
Okay, understood.

**Comment by rob-solana** [comment]
it'd be nice to get bank out of vote_program, but we need something like what's in instruction_processor in the SDK to do so

**Comment by rob-solana** [comment]
this was bugging me all weekend, taking it up
