### ISSUE TITLE
Need better architecture for transaction forwarding 

### ISSUE THREAD

**Issue by pgarg66** [solana-labs/solana#4071]
#### Problem
The current transaction forwarding logic may not keep up with leader rotation, and in turn cause unnecessary load on network

#### Proposed Solution
1. Forward the transactions to a node that's not the leader yet, but will be leader soon (within half a slot)
2. That'll give that node some head start to pre-process the transactions and be ready to commit the transaction in it's leader slot
3. This will "kind of" guarantee that the transaction will be processed by one of the node, and prevent unnecessary re-transmissions after first forward.

**Comment by pgarg66** [comment]
@aeyakovenko Just FYI

**Comment by aeyakovenko** [comment]
The validator should retry on every block.  

So check the tx is valid, and when a new leader starts a block send it to that leader until  the tx appears in blocktree.

**Comment by carllin** [comment]
@aeyakovenko, so the first validator that gets a tx will own that transaction, and is in charge of forwarding it to every leader it detects until the transaction gets included in some block? Should the validator also ensure that the block be a descendant of the fork its currently voting on before removing that tx from its cache?

**Comment by aeyakovenko** [comment]
@carllin I don’t know how much that matters. We might have clients ask the validator to retry until N confirmations. That’s V2.  I imagine leaders will slurp any transactions that they can from failed forks as well.

**Comment by carllin** [comment]
@aeyakovenko, right now each in the forwarding logic there are 3 cases

1) The validator forwards the batch of transactions that they could not process in their leader slot. 

2) If a validator is not the leader but will be the next leader, they cache the transactions for processing later (@pgarg66  feel free to correct me here).

3) Otherwise, drop the txs

The question is, what benefits do you see from having each validator "own" the forwarding responsibility for the set of txs they get from the client? In our current implementation, forwarding shouldn't snowball the number of unprocessed txs (you can only forward at most as many txs as you've received). One potential benefit I see with your approach is that you can distribute the responsibility of expiring txs and the network resources for forwarding batches of txs across many validators. Could you expand on that?

**Comment by aeyakovenko** [comment]
@carllin because clients can ingress at any point without caring who the leader is.  And validators can verify and batch everything, and leders can QoS by stake weight.

**Comment by pgarg66** [comment]
The client transaction should be forwarded to the leader for slot = (current slot + 1)

**Comment by pgarg66** [comment]
Capturing discussion from our meeting today.

1. We'll look into preprocessing the transactions on the nodes that are soon to be leader. This could help create a pipeline of transaction processing on the nodes that are not leader yet, and possibly squeeze out some performance gain.

2. We'll hold off on implementing the design proposal for a node to own the client transaction (where it forwards the transaction to leader nodes until its processed or expired).

3. As another optimization, a node can check the block hash of a transaction before forwarding it to other nodes. This will help filter out transactions that are too old and expired.

**Comment by pgarg66** [comment]
Created the issue for pending work, as it is not a requirement for mainnet MVP
