### ISSUE TITLE
Resume fullnode from snapshot

### ISSUE THREAD

**Issue by sambley** [solana-labs/solana#4156]
#### Problem
To speed up node restart, the bank state information is saved and restored from the snapshot rather than having to replay the transactions from the ledger. Need a way to figure out how to replay entries after loading the snapshot which could mean figuring out which entries in blocktree has already been played.

#### Proposed Solution
Look into restoring the forking information and any additional information that may be needed to resume the node restart.

@carllin, @aeyakovenko, @rob-solana

**Comment by carllin** [comment]
To my understanding, the snapshot is currently of the state of BankForks? To figure out where to start replaying from blocktree, it seems like the snapshot also needs to be augmented with some version of the `progress` hashmap which currently lives in replay_stage and tracks which entries have been played on each live bank here: https://github.com/solana-labs/solana/blob/master/core/src/replay_stage.rs#L113

**Comment by sambley** [comment]
@carllin, after resuming blocktree.get_slots_since() from below location always returns empty, would saving the version of progress resolve this as well?
https://github.com/solana-labs/solana/blob/master/core/src/replay_stage.rs#L575

**Comment by carllin** [comment]
@sambley, given a set of slots X, get_slots_since(X) will only give you any new slots that are descendants of any slot x (its how we hand new slots on a fork to replay_stage), so on restart, if the set X is the latest from the snapshot, and blocktree hasn't received any new slots from the network, get_slots_since() will not return anything.

**Comment by sambley** [comment]
@carllin, do you have an idea what information may be missing and needs to be restored currently to make it resume from the last snapshot point.

**Comment by carllin** [comment]
@sambley, based on this code here: https://github.com/solana-labs/solana/pull/3671/files#diff-0e517bfb897cd6ee46d83d239efb1cb7R144,  snapshots should only be of banks that have been frozen/completed right? If so, I don't think you need any extra information from blocktree, because there are no "partial banks" stored in the snapshot. What should happen is that once the BankForks is restored, replay_stage will naturally take care of pulling and replaying the necessary next slots/entries from Blocktree.

There is this separate issue that because we don't currently track a validator's past votes, after reloading a snapshot replay stage might vote again on different/conflicting slots because it  may observes forks in a different order after a restart, but this is a separate issue tracked here: https://github.com/solana-labs/solana/issues/4132. @sagar-solana

**Comment by aeyakovenko** [comment]
@carllin we should be able to just resume the state after restart.

**Comment by carllin** [comment]
@aeyakovenko, yup seems like it :D

**Comment by sambley** [comment]
Looks like the run.sh was creating a new leader pubkey each time it was started and hence the leader id was not matching up in subsequent runs after restoring from snapshot. After making the leader pubkey to stay the same across runs, it now seems to resume but the votes are not getting recorded and new roots to not get set.

**Comment by carllin** [comment]
Are you running with just one node? A validator won't vote for a bank unless it sees transactions in that bank

**Comment by sambley** [comment]
Looks like snapshot was not stored for slot 0 and hence the vote accounts were not being found on restore. Saving and restoring slot 0 seems to have resolved the issue and run.sh that just runs one node seems to resume successfully after killing and restarting it.

**Comment by carllin** [comment]
Ah, good catch!

**Comment by sagar-solana** [comment]
@carllin with #4622 do we have locktower state/voting history being preserved as well?
