### ISSUE TITLE
Rust BPF: Unable to run Rust's sysroot tests to validate Rust language compliance

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#4390]
#### Problem

Rust has a ton of built-in tests to validate its own behavior.  Being able to run these tests within a BPF program would help improve confidence in our implementation and point out areas that need to be improved.

**Comment by jackcmay** [comment]
@dmakarov What work is left to run the Rust language tests for BPF?

**Comment by dmakarov** [comment]
Standard libraries contain both integration and unit tests. These are invoked when for example the following command is used
```
./x.py test --stage 1 --target bpfel-unknown-unknown --no-doc library/alloc
```
The above runs the tests for the alloc library compiled to BPF target. The libraries built for BPF are alloc, compiler_builtins, core, and std.  Currently, only compiler_builtins is tested for the BPF target.  Of the remaining libraries core compiles but doesn't run any tests, because the generated .so file doesn't contain a .text section, something that has to do with no entrypoint function being found, probably.  The other two libraries alloc and std tests currently don't compile for BPF because of using features unsupported for BPF. The tests are driven by `cargo test` command and with the tool that I wrote `cargo run-bpf-tests` they can be executed on the RBPF, if I can get them to compile for BPF.

There's another set of rust tests driven by compiletest utility (src/tools/comiletest).   These tests include so called UI tests (testing how rustc frontend behaves and reports syntax errors), and also codegen tests.  The compiletest tool may have to be adapted to running tests for the BPF target. These tests may not need to be executed on the RBPF, so it could be easy to adjust compiletest to work for the BPF target.

Before spending time on compiletest utility, I'd like to see how BPF tests will be executed in the upstream rust CI. BPF is a tier 3 target since the release 1.54.0, and it is expected to move to tier 2 in a couple of releases. At that point the upstream rust will include BPF target in their CI testing. I'd like to see how this will work.

**Comment by dmakarov** [comment]
@alessandrod your help on this issue would be much appreciated.

**Comment by alessandrod** [comment]
Alright, I spent the last couple of days spiking on this as a practical excuse to start learning the code base and to see how far I could get.

As Dimitry said, rustc unit tests are regular `#[test]` functions compiled and executed with `cargo test` as usual. Therefore as a first step, I set out to get `cargo test --target=bpfel-unknown-unknown` working:

```sh
mb in bpf-tests on  master ❯ cargo +sol test  --target=bpfel-unknown-unknown 
   Compiling bpf-tests v0.1.0 (/Users/alessandro/src/solana/bpf-tests)
    Finished test [unoptimized + debuginfo] target(s) in 0.14s
     Running unittests (target/bpfel-unknown-unknown/debug/deps/bpf_tests-7f90eaff9a5acebb)
Executed /Users/alessandro/src/solana/bpf-tests/target/bpfel-unknown-unknown/debug/deps/bpf_tests-7f90eaff9a5acebb.so 27700 instructions in 0.00s.

running 3 tests
test foo::tests::test_bar ... ok
test tests::test_that ... ok
test tests::test_this ... ok

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

mb in bpf-tests on  master ❯ 
```

This works by having the following in `.cargo/config.toml`: 

```toml
[target.bpfel-unknown-unknown]
runner = "cargo-run-bpf-tests"
```

Cargo will compile the tests as a `cdylib` crate, using `rustc --test`, which uses `libtest` to generate a function that invokes all the `#[test]` functions sequentially.

Then to run the tests cargo invokes the given `runner` with the test `cdylib` passed as an argument. The runner I'm using is a hacked up version of `cargo-run-bpf-tests`.

With that working, after working around an issue with LTO (rust tests are compiled in `--release` mode, which runs thin LTO by default, which for... reasons was killing all the test symbols), I got basic rustc tests working too:

```sh
mb in rust on  solana-1.56.0 took 3s ❯ python3 ./x.py test --stage 1  --target=bpfel-unknown-unknown library/core        
Updating only changed submodules
Submodules updated in 0.04 seconds
    Finished dev [unoptimized + debuginfo] target(s) in 0.54s
Building stage0 std artifacts (x86_64-apple-darwin -> x86_64-apple-darwin)
    Finished release [optimized + debuginfo] target(s) in 0.19s
Copying stage0 std from stage0 (x86_64-apple-darwin -> x86_64-apple-darwin / x86_64-apple-darwin)
Building stage0 compiler artifacts (x86_64-apple-darwin -> x86_64-apple-darwin)
    Finished release [optimized + debuginfo] target(s) in 0.54s
Copying stage0 rustc from stage0 (x86_64-apple-darwin -> x86_64-apple-darwin / x86_64-apple-darwin)
Assembling stage1 compiler (x86_64-apple-darwin)
Building stage1 std artifacts (x86_64-apple-darwin -> bpfel-unknown-unknown)
warning: dropping unsupported crate type `dylib` for target `bpfel-unknown-unknown`

warning: `std` (lib) generated 1 warning
warning: `test` (lib) generated 1 warning (1 duplicate)
    Finished release [optimized + debuginfo] target(s) in 0.18s
Copying stage1 std from stage1 (x86_64-apple-darwin -> x86_64-apple-darwin / bpfel-unknown-unknown)
Building rustdoc for stage1 (x86_64-apple-darwin)
    Finished release [optimized + debuginfo] target(s) in 0.30s
Testing core stage1 (x86_64-apple-darwin -> bpfel-unknown-unknown)
   Compiling core v0.0.0 (/Users/alessandro/src/solana/rust/library/core)
    Finished release [optimized + debuginfo] target(s) in 15.67s
     Running tests/lib.rs (build/x86_64-apple-darwin/stage1-std/bpfel-unknown-unknown/release/deps/coretests-bc0f5984685efb6e)
Executed /Users/alessandro/src/solana/rust/build/x86_64-apple-darwin/stage1-std/bpfel-unknown-unknown/release/deps/coretests-bc0f5984685efb6e.so 227729 instructions in 0.00s.

running 12 tests
test hash::sip::test_hash_idempotent ... ok
test hash::sip::test_hash_no_bytes_dropped_32 ... ok
test hash::sip::test_hash_no_bytes_dropped_64 ... ok
test hash::sip::test_hash_no_concat_alias ... ok
test hash::sip::test_hash_usize ... ok
test hash::sip::test_siphash_1_3 ... ok
test hash::sip::test_siphash_2_4 ... ok
test hash::sip::test_write_short_works ... ok
test hash::test_build_hasher_object_safe ... error: test failed, to rerun pass '-p core --test coretests'

command did not execute successfully: "/Users/alessandro/src/solana/rust/build/x86_64-apple-darwin/stage0/bin/cargo" "test" "--target" "bpfel-unknown-unknown" "-Zbinary-dep-depinfo" "-j" "16" "--release" "--features" "panic-unwind backtrace compiler-builtins-c" "--manifest-path" "/Users/alessandro/src/solana/rust/library/test/Cargo.toml" "-p" "core" "--" "--quiet"
expected success, got: exit status: 1

Build completed unsuccessfully in 0:00:19
```

Success! Kinda.

I think in principle we can make this work. There are two large-ish issues I can see at the moment though:

- `libtest` generates a single function we invoke from the entrypoint to run all the tests. Since we abort on panic, the first panic stops all the tests. This is a problem of course because some tests panic intentionally to check that APIs... panic.
- We never deallocate memory, so tests quickly run out of memory.

**Comment by dmakarov** [comment]
This is really great. For now, tests that panic intentionally can probably be disabled for the bpf target until we either change the harness that runs them or change how panic is handled.

**Comment by dmakarov** [comment]
It looks like the VM that we create in cargo-run-bpf-tests has heap size only 32K. For running the tests we can probably make a lot larger heap, which should alleviate at least to some degree the problem of running out of memory. I assume it's the heap the VM allocates for the entrypoint program that is never being deallocated.

**Comment by alessandrod** [comment]
> It looks like the VM that we create in cargo-run-bpf-tests has heap size only 32K. For running the tests we can probably make a lot larger heap, which should alleviate at least to some degree the problem of running out of memory. I assume it's the heap the VM allocates for the entrypoint program that is never being deallocated.

Yup increasing the heap helped. I hacked a few more things and now:

```
test result: ok. 518 passed; 0 failed; 0 ignored; 0 measured; 23 filtered out; finished in 0.00s
```

Most tests pass. Some don't (including a nice LLVM crash!) so I disabled them for now. I'll get what I've done so far in a commitable state now then we can go back and actually fix the tests.

**Comment by alessandrod** [comment]
See https://github.com/solana-labs/cargo-run-bpf-tests/pull/10 and https://github.com/solana-labs/rust/pull/33

**Comment by dmakarov** [comment]
It seems we can close this issue now, correct?  We have the library tests running in our CI for rust.  Not all tests are enabled and not for all libraries yet, but we probably don't need to keep this issue open to fix that? If no objections, I'll close the issue as resolved.  Huge thank you to @alessandrod for really great work!

**Comment by alessandrod** [comment]
Yup we can track new issues we encounter running tests separately!

**Comment by dmakarov** [comment]
Resolved by this PR https://github.com/solana-labs/rust/pull/35
