### ISSUE TITLE
windows validator port: resolve blockstream.rs EntryWriter::write() stub

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#4547]
To support a windows validator, we need to replace the EntryWriter::write() stub in #4546 with a real implementation probably using named pipes.

**Comment by lazaridiscom** [comment]
add label `windows`

**Comment by gabriel-viviani** [comment]
Hey @mvines is this still needed? If so I'd like to pick it. Although I'd need some guidance. Thanks!

**Comment by mvines** [comment]
Sure, supporting the full validator on windows would definitely be nice.  There’s been very little interest in making this happen though as Linux works really nicely, and MacOS is well supported for development too.

**Comment by CriesofCarrots** [comment]
> Sure, supporting the full validator on windows would definitely be nice. There’s been very little interest in making this happen though as Linux works really nicely, and MacOS is well supported for development too.

This particular windows accommodation isn't needed, though, since Blockstreamer no longer exists...
@gabriel-viviani , I'm going to close this issue since it's obsolete, but if the windows-validator project interests you, perhaps the following issue would be a good place for updates or discussion: https://github.com/solana-labs/solana/issues/4608
