### ISSUE TITLE
Put an upper bound on memory consumption with sync_channel

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#464]
Can we demonstrate that using `sync_channel` everywhere instead of `channel` puts an upper bound on memory consumption between stages. What's its impact on performance over time?

**Comment by aeyakovenko** [comment]
We should monitor the sizes of the queues instead of adding a limit. If you limit a queue in the middle, you will push the failures back until you start seeing more network drops, instead of observing the queue size jump and seeing what stage is stalled. 


 If you look at the counter graphs, the gap between the stages should be the amount of memory we have allocated. For some reason the banking stage has a huge ramp up
