### ISSUE TITLE
Don't share mint.json / Download genesis.log from drone or a bootnode

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#502]
solana-drone should generate genesis.log from its mint.json and then tuck away mint.json.  All fullnodes should then download genesis.log from the drone.

**Comment by mvines** [comment]
> It's strange how setup.sh creates those files for all fullnodes.
solana-drone and solana-genesis require the's mint's private key, which is in mint.json.
solana-fullnode requires leader.json for a leader, and requires both leader.json and [I think] a unique validator.json for each validator.
solana-wallet requires leader.json and a unique mint.json (which is simply used to generate a private key for the client).
By downloading the leader's mint.json, you're giving the client access to all the tokens instead of just the tokens the solana-drone delivers by airdrop.

**Comment by mvines** [comment]
Also:
> @mvines, I bet it'd help if wallet stopped using mint.json files for the only purpose of storing a keypair. We can switch it to a standard file format.

**Comment by mvines** [comment]
#518 makes mint.json private, which resolves part of this issue.

What remains is making genesis.log available from the drone or a boot node (which is a concept that doesn't exist in the code base yet), instead of fetching it from the leader.   Presumably the transactions that follow the genesis.log would also be fetched from the drone/bootnode as well

**Comment by garious** [comment]
No, only the genesis.log, who's generation depends on mint.json. We only need to solve the problem of keeping that mint.json as inaccessible as possible. Even going as far as moving it to cold storage after the network has a copy of genesis.log.
