### ISSUE TITLE
Archivers should only store rooted slots

### ISSUE THREAD

**Issue by sagar-solana** [solana-labs/solana#5022]
#### Problem

A storage segment is a continuous set of slots (currently 1024).  But only some of those slots might be on the rooted path (main fork). 

- The non-root path slots could be different on different validators and that will impact their ability to verify a replicator's proof
- There is no benefit in storing non-root slots
- Repairing non-rooted slots might cause problems since some might be empty (and repair can't handle that)

#### Proposed Solution

- A segment needs to be redefined as some number of rooted slots instead of just any continuous set of slots (this is doable via storage_stage, it can share its rooted slot count instead of the root slot itself). 
- Replicators should only store rooted slots and completely skip downloading anything that isn't rooted (repair needs to be updated to repair N rooted slots starting at some offset)

Tag: @sakridge @carllin @aeyakovenko

**Comment by carllin** [comment]
Should a segment be defined as some number of rooted slots or just all the rooted slots within a range?

Right now in blocktree its quite efficient to query for whether a particular slot is a rooted slot (it's in the index), but you would have to traverse all the rooted slots in order to find the Nth rooted slot.

Also, if we want to eventually support using replicators as queryable backups, it's probably less intuitive to query for the nth rooted slot rather than a specific range of slots?

**Comment by sagar-solana** [comment]
I think you're right. So the correct design to keep the same "segment" ranges but make sure that only rooted slots are stored within those ranges. Validators must also make sure to only use rooted slots to perform verification.

**Comment by ryoqun** [comment]
I think we can close this for now. (let's reduce open issues!)
