### ISSUE TITLE
Facility to a validator to prune older parts of the ledger 

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#5051]
#### Problem
Validators that don't care to retain the full ledger have no mechanism to manage their disk space beyond periodically stopping, deleting the ledger, and restarting from a snapshot.

#### Proposed Solution
Actively prune older slots out of blocktree, perhaps around here: https://github.com/solana-labs/solana/blob/9f58318fc59da276bc8b4014760032319b2263b6/core/src/bank_forks.rs#L138
The trick is that once the validator starts discarding old ledger, it can no longer participate in repairing other nodes that are behind the discard point.   So we'd want to keep some amount of ledger (maybe an hour or so of data at least) around to help out the nodes that are trying to catch up from a recent snapshot

**Comment by aeyakovenko** [comment]
@carllin can you take a look how hard this would be?  A lot of validators will be surprised if they need to store 20TB of ledger.  We can dump anything that’s older than a few hours.

**Comment by jaygaga** [comment]
Wow 20 TB is quite massive,

**Comment by carllin** [comment]
@aeyakovenko, I'm guessing we can set a marker in blocktree indicating that all slots before that point are cleared. The only bit that will need cleanup I think is any code right now that assumes that fetching a blob before the root will be there, for instance - repair.

**Comment by sagar-solana** [comment]
@carllin @aeyakovenko, the current plan for this PR is to drop (delete) anything that's 5 segments or older. 

This purged ledger probably won't "verify" via ledger tool, so that's something im not sure how to handle right now. When a node restarts, it will pick up from the most recent snapshot it has and it should be fine. 

Does that sound okay ?

**Comment by mvines** [comment]
> This purged ledger probably won't "verify" via ledger tool, so that's something im not sure how to handle right now.

Same issue already exists for ledgers booted from a snapshot.

How long is 5 segments in terms of slots?

**Comment by sagar-solana** [comment]
Oh sorry I meant epochs, not segments. So that's 8192 * 5 = 40,960 slots. Will that be too much ? I think we should definitely be more than 3 epochs. 

Also, Rollbacks will only work as long as there's a snapshot at some point before the rollback height. Because the ledger won't have everything from `0..rollback_height`.

**Comment by mvines** [comment]
5 epochs (~5 hours) sgtm
