### ISSUE TITLE
Test partitions and convergence

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#6209]

**Comment by danpaul000** [comment]
I got a lot of feedback from @carllin and @sagar-solana on this topic during our sync.  I see two main thrusts of work on this topic.  The first is clearly a dependency of the second.  Bullet points under each area are just copied from my notes in the sync meetings as ideas came up.

1). The need for a testing framework that can force/control/resolve network partitions, packet loss and latency hooked in to either our local cluster tests or our fullstack testnets

- Pass a testing configuration that works on local cluster, but runs remotely.  Need some external hook.  A rust test that launches external computers.
- Maybe NEAR or another Rust based project has a test framework we can leverage for partition testing
- Can't say our consensus mechanism really works unless it works under all bad network conditions (partitions, huge delays, etc).  Tie consensus testing to partition testing (50/50, 30/30/30, partitions partitioning themselves again)  Need a framework that can force these conditions.
- How do we indicate consensus quantitatively, or do we always need a human observer?
- Estimate a few weeks to build out such a testing framework feature complete.

2) Need to define and implement various test cases within this framework to stress the software.

- Need to define and build a real world test suite with all of the attack/failure modes defined and implemented
- Nodes dropping off without deallocating their stake.  Causes empty slots in leader schedule, leading to poor network perf.
- Network latency.  Test with nodes in far flung locations (Africa)
- Fork testing.  High load testnets have been falling apart.  We only have been short lived forks, no tests with long-lives forks. (sagar)
- What happens if you have two nearly-identically staked networks that occasionally talk to one another? (sagar)

**Comment by carllin** [comment]
@danpaul000 Any blocks on the minor fork will be rolled back upon reconvergence. 

After a partition point, the supermajority on both forks should be the same within the same epoch, unless we add some sort of leaking/penalty for inactivity. If the forks don't reconverge within an epoch and neither has supermajority, then the network is dead.

**Comment by pgarg66** [comment]
Kudelski security report also suggests running the partitioning tests. The following list has all the scenarios they talk about.

- [ ] Various number of partitions
- [ ] Partitions dynamically introduced during runtime
- [ ] Recovery from multiple partitioning after extended period of time (6.3.2.2.1.5)
- [ ] Recovery among multiple partitions after one of the partitions is never resolved (6.3.2.2.1.6)
- [ ] Permanent partitioning where partitions have unequal stakes. The two partitions continue driving their own forks ((6.3.2.2.1.7, 6.3.2.2.1.8)
- [ ] Network partitioning tests among/between Turbine neighborhoods.
