### ISSUE TITLE
Include validator-info data for SLP1 validators in the genesis block

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#6373]
solana-cli `validator-info` also uses Config. Maybe not a necessity for SLP1, but it would be a nice-to-have for participating validators (vis-a-vis network explorer display)

_Originally posted by @CriesofCarrots in https://github.com/solana-labs/solana/pull/6369#issuecomment-542407359_

**Comment by jackcmay** [comment]
@CriesofCarrots Can you expand on what action item is covered by this issue?

**Comment by CriesofCarrots** [comment]
@jackcmay 
Action item is namely the issue title: include validator-info data for SLP1 validators in the genesis block
The more granular action items are: figure out which validators will be participating in our SLP1 launch; collect validator-info from them (could be pulled from TdS registration or actual validator-info from TdS dryruns or Stage 1, depending on when that happens, if they are TdS participants).

The problem more explicitly: The solana-cli `validator-info` api uses the Config program to initialize validator info accounts and store/update data. Since the Config program will not be available in SLP1, we need to pre-initialize validator-info accounts for participating validators, if we want them to exist.
My impression is that validator-info has been helpful for validators participating in the dryruns (troubleshooting and monitoring their nodes, esp on the Network Explorer), but may not be a necessity or worth the LOE for SLP1 participants.

**Comment by mvines** [comment]
I think we can just close this, it doesn't seem too important in retrospect.

**Comment by CriesofCarrots** [comment]
Wfm
