### ISSUE TITLE
move rent collection to store_account in bank

### ISSUE THREAD

**Issue by ParthDesai** [solana-labs/solana#7056]
#### Problem
Currently, rent deduction code is in `deposit` as per #6947 

Moving rent collection to `store_account` in bank is better design that gives us assurance that all load and store paths are covered even in future, and no accidental rent leakage. 

#### Proposed Solution
- [ ] have another interface on bank to store account as it is i.e without deducting rent. (only for unit tests)
- [ ] Move rent collection to `store_account`
- [ ] Fix broken tests due to above changes

**Comment by ryoqun** [comment]
This is slightly related to #10468 .

Also, I think we can't easily move the rent collection to `Bank::store_account()` because the function is too generic/broad while it's the best place to enforce rent collection.

Consider this: what happens to collected rents while doing `distribute_rent()`? (recursive rent handling!)
