### ISSUE TITLE
Support creating nonced transactions with a nonce account

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#7121]
#### Problem
The CLI and SDK currently do not support creating valid nonced transactions. A nonced transaction needs to use a "nonce blockhash" as its "recent blockhash" and needs to begin with a `nonce_instruction::Nonce` instruction which references an initialized nonce account. Lastly, the transaction needs to be signed by the nonce account's authorized key.  _(The blockhash in the initialized nonce account must match the "nonce blockhash" used for the transaction's "recent blockhash")_

Depends on https://github.com/solana-labs/solana/issues/6872 for passing in the nonce blockhash (can be queried directly on an online machine)
Depends on https://github.com/solana-labs/solana/pull/6845 for nonce instruction structure/design

#### Proposed Solution
* Add `--nonce-account` arg to `pay`, `delegate-stake` and `deactivate-stake` cli commands
  * `--blockhash` is required if `--sign-only` is present, otherwise fetch via RPC
  * If `--nonce-keypair` is a public key, assume that the nonce authority is the identity keypair
  * If `--sign-only` is *not* used, verify that the nonce authority is one of the signers
* Add new SDK convenience method for creating a nonced transaction from a nonce public key, nonce blockhash, list of instructions and list of signer keypairs

**Comment by mvines** [comment]
@jstarry - maybe you can yank this from @t-nelson later in the week once Rampy is working harder?

**Comment by jstarry** [comment]
Yes! That's the plan 👍

**Comment by t-nelson** [comment]
Proposal looks good!

I think I'd prefer `--nonce-account` since the parameter can be a keypair _or_ pubkey.

> If --sign-only is not used, verify that the nonce authority is one of the signers

How do we determine the authority identity?  It may be different from the account pubkey.  Note that this issue isn't unique to nonce it occurs with all of the account roles that can be assigned and authority and there is a similar ergonomic problem with specifying an offline fee payer.

Documenting this shortcoming may be sufficient for now.  I think we're going to need to rethink how the signing happens to make this feel right
