### ISSUE TITLE
Malicious leader can flood cluster with excessive pre-processed transactions

### ISSUE THREAD

**Issue by pgarg66** [solana-labs/solana#7531]
#### Problem
A malicious node can determine its next leader slot in an epoch. It can generate/cache excessive number of pre-processed transactions such that

1. When the malicious node becomes leader it injects all these transactions into system, and is able to commit/record and broadcast them to validators
2. The peer validators are unable to keep up with the volume, as the transactions were not pre-processed on those nodes.

The `nonce` accounts and instructions allow the transactions to be generated and pre-processed days in advance. That makes this attack even more feasible.

The attack can overload peer nodes, and cause resource exhaustion. That can result in node failures, partitioning, etc.

Reference 6.5.2.1, 6.5.2.2, 6.5.2.3

#### Proposed Solution
1. Soft limit the number of `shreds` in a block. Truncate the block at the last complete entry before the shred count goes past the limit.
2. The limit can be set to N times more TPS that the cluster can currently handle.
3. Datapoint/metrics to detect when the limits for a block is getting reached.
4. If the cluster is reaching the limit for majority of blocks, it could be an indication that cluster can handle more transactions in a block. The limit should be recomputed at that point in time, and cluster should be upgraded.

**Comment by sagar-solana** [comment]
A few questions and observations from just thinking about this issue. 

- The only thing they can pre-compute is the transaction's signature right? 
  - They can't compute the shreds in advance since the entries in that slot will have to chain to some PoH and if they chain incorrectly (not from the heaviest fork) their slot gets ignored? 
  - They can't compute the state transition in advance as changes could have occurred on the main fork. This doesn't hold true for Nonce accounts
- Lets say they can shred this stuff super quick, and send it to everyone. What's the worst that happens?
  - Window service spends a bunch of time verifying these shreds, forks slow down and don't make progress, but that sounds like a consistent stall across the cluster, it will cause many short lived forks as leaders keep proposing blocks that aren't getting delivered. This is the only bad thing I think this causes
  - If everyone completes the slot, they'll try to play it, which could take really long. But during that time no new blocks will be produced, immediately after everyone will either vote and reset or just carry on(start a bunch of little forks and reconverge). 

I think I might be missing the worst part about this. Or is this enough of a reason to limit the maximum number of shreds per slot ? 

@aeyakovenko @carllin

**Comment by aeyakovenko** [comment]
@sagar-solana you are correct.  But we don’t want a low staked leader to be able to ddos the network by producing large useless blocks that get rejected.
