### ISSUE TITLE
Add validator option to not advertise RPC in gossip even when enabled

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#7942]
In production it's generally expected that most validators choosing to keep RPC enabled will firewall it from the public, keeping it available only for internal use.   Doing so right now will still cause the validator to advertise the RPC service on gossip, and clients may will try to connect (and fail/timeout).

There should be a mechanism, perhaps a `--private-rpc-port` validator command-line option (that conflicts with the existing `--rpc-port`, that enables RPC but keeps it out of gossip so other cluster participants won't know it exists

**Comment by ank-everstake** [comment]
While setting Nginx reverse proxy for  Solana TDS RPC we noticed following about next flag:
`--private-rpc                                          Do not publish the RPC port for use by other nodes`


1. This flag doesn`t block external requests
2. Absence of this flag means that we share our RPC ports in the gossip and perform reachability tests to RPC+WS ports from nodes in cluster
3. We may need to separate ports which we want to bind on and ports that we want to pass to gossip, because we may use load-balancer
4. If we cannot make this separation, maybe it will be good idea to make another flag, 
like `--disable-rpc-check` , so it makes possible to publish, but disable check.
5. We may consider changing flag description, so it's more obvious:
```
Do not publish the RPC port for use by other nodes
[please, change your firewall to block requests to them]
```

**Comment by mvines** [comment]
> We may need to separate ports which we want to bind on and ports that we want to pass to gossip, because we may use load-balancer

Interesting.  Load balancing RPC through gossip isn't going to work without some rework, I hadn't considered that case.   But that would just be for validators trying to boot.   The end-user RPC client would just go through a well-known entrypoint, such as api.mainnet-beta.solana.com, which is not advertised in gossip
