### ISSUE TITLE
solana-cli does not allow a conversion from wallclock date to epoch

### ISSUE THREAD

**Issue by danpaul000** [solana-labs/solana#8842]
#### Problem
`solana stake-set-lockup` does not provide a way on the CLI to convert a target lockup date into a number of epochs, but we have this method available in code, to set a number of years (ex: 0.75) and have the account reflect 9 months worth of epochs in lock.

**Comment by danpaul000** [comment]
cc: @garious

**Comment by garious** [comment]
Here's where it's done in code:
https://github.com/solana-labs/solana/blob/master/genesis/src/stakes.rs#L29

And the resulting epoch is from genesis.

We want to be able to things like adding 6 months of lockup, so would need to ask "how many epochs is 0.5 years"?  And then use that to call `solana stake-set-lockup --lockup-epoch <EPOCH>` with a higher epoch.

Note: we don't need to make this infinitely flexible, since the custodian will be the only user of this functionality, and with any luck, only needs to use it a few times this next year and then never again.

**Comment by garious** [comment]
@danpaul000, I think we can ignore this issue for the foreseeable future if we switch all stake accounts from setting `--lockup-epoch` to  `--lockup-date`.
