### ISSUE TITLE
cli: add `solana stake-authorize` command that moves both staker and withdrawer key at once

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#8910]
When transferring a stake account into custody, it is desirable to move both the staker and withdrawer key into custody.   If only the staker key is moved, the funds could still be withdrawn from custody if the original withdrawer key is later compromised.

Currently this would be accomplished by running two separate CLI commands:
```
$ solana stake-authorize-withdrawer
$ solana stake-authorize-staker
```
which is clumsy, error-prone, and not-atomic.

Let's offer a `solana stake-authorize` with options to set the withdrawer, staker, or both keys in a single Transaction.

**Comment by garious** [comment]
I'll micromanage on this one, since there's already precedent with `stake-set-lockup`. Each command-line option should map to an `Option`, such that the command sets the keys that are provided and leaves the others alone.  `solana stake-authorize-staker <PUBKEY>` should be the equivalent, for example, to `solana stake-authorize --stake-authority <PUBKEY>`.

Usage:

```bash
solana stake-authorize [--withdraw-authority=<PUBKEY>] [--stake-authority=<PUBKEY>]
```

Also please consider a couple *additional* options:

```bash
solana stake-authorize [--withdraw-authority-keypair=<KEYPAIR>] [--stake-authority-keypair=<KEYPAIR>]
```

Personally, I'm super uncomfortable transferring authority without certainty that someone is holding that private key.
