### ISSUE TITLE
GCE Testnet validator failing to catch up after unpacking snapshot

### ISSUE THREAD

**Issue by danpaul000** [solana-labs/solana#9146]
#### Problem
Running a 5-node GCE testnet on the latest v1.1 or master tarballs, the 1 of the 5 validators consistently fails to catch up after downloading the snapshot from the bootstrapper.   It is consistently the first validator to be brought up after the bootstrapper that is failing.  All other nodes catchup and complete.  The first & failing node does not progress past the snapshot slot.

In the attached logs, each validator gets the same snap shot from bootstrapper at slot 100, but one never advances its root after unpacking.

[validator-failed-catchup.log](https://github.com/solana-labs/solana/files/4398220/validator-failed-catchup.log)
[validator-succeed-catchup.log](https://github.com/solana-labs/solana/files/4398222/validator-succeed-catchup.log)

STR:
```
net/gce.sh create -d pd-ssd -n 5 -c 2 --custom-machine-type '--machine-type n1-standard-16' -P -z us-west1-a --self-destruct-hours 0 --dedicated
net/net.sh start -t edge
```
The `net.sh start` command will hang on the "starting validator" section, ex:
```
--- Starting validator: 34.82.119.213
start log: /Users/dan/repos/danpaul000/solana/net/log/validator-34.82.119.213.log
getNodeType: 35.185.193.236
getNodeType: validator (5)
--- Starting validator: 35.185.193.236
start log: /Users/dan/repos/danpaul000/solana/net/log/validator-35.185.193.236.log
```
Looking at `net/log/validator-[PID].log` files shows that all but one of the validators has finished booting and one is still waiting for `solana catchup` to return.  Running the catchup command manully shows the stuck validator never got past the snapshot slot.

**Comment by danpaul000** [comment]
cc @mvines @ryoqun

**Comment by danpaul000** [comment]
Starting with no client nodes does not reproduce this behavior, so seems likely related to the large snapshot file size from all the bench-tps client accounts.

**Comment by mvines** [comment]
The problem looks to be the known issue/feature that repair only works in the current epoch.  If a validator boots in an earlier epoch it will never catch up.

Looking at the two logs I see that the failed validator came online with a snapshot of slot 100 (in epoch 2, slots 95..224) when everybody else was now in epoch 3 (slots 224..480) so it has no chance.

Possible short term possible fix: Use `--snapshot-interval-slots 250` in `multinode-demo/`, to ensure that the first snapshot is at slot 250 (epoch 3, giving nodes ~1 min 40 secs to catch up) instead of slot 100 (epoch 2, giving nodes ~50 secs to catch up)

Longer-term fix: Rework `net/`'s `solana-genesis` usage so that all the validators are `--bootstrap-validator`'s, then start each with `--wait-for-supermajority 0` so that all the validators synchronize at slot 0 before starting

**Comment by mvines** [comment]
Obsolete
