### ISSUE TITLE
CLI doesn't handle "429 Too Many Requests" properly 

### ISSUE THREAD

**Issue by vkomenda** [solana-labs/solana#9856]
#### Problem

`solana transfer` either
* fails after a couple confirmations with
```
Error: HTTP status client error (429 Too Many Requests) for url (http://tds.solana.com/)
```
or
* hangs after a few confirmations and stops displaying any status updates.

**UPDATE:** other commands also behave the same. Tried `create-stake-account` as well. Possibly a more general issue with the RPC rather than with CLI.

#### Proposed Solution

All the transactions I made were eventually successful, which suggests that the CLI should try waiting longer and possibly that the error 429 shouldn't be critical.

**Comment by mvines** [comment]
I recently added a per-ip rate limit of 2 requests per section, so that's why we see the 429 error.  The cli should not bail on a 429 though, but instead just retry a little later.

But in the meantime I've also increased the rate limit, if you still see 429s during normal operations @vkomenda please let me know here and I'll make further adjustments!

**Comment by mvines** [comment]
(solana-web3.js needs to handle this as well)
